<?php

    // Iniciamos o "contador"
    list($usec, $sec) = explode(' ', microtime());
    $script_start = (float) $sec + (float) $usec;

?>
<!doctype html>
<!--[if lt IE 8]><html class="no-js lt-ie8"> <![endif]-->
<html class="no-js">
    <head>
        <meta charset="utf-8">
        <base href="<?php echo $this->system_path; ?>" />
        <title><?= $this->module_title ?></title>
        <!-- Mobile specific metas -->
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <!-- Force IE9 to render in normal mode -->
        <!--[if IE]><meta http-equiv="x-ua-compatible" content="IE=9" /><![endif]-->
        <meta name="author" content="Híbrida" />
        <meta name="description" content="Sistema Administrativo 2.0" />
        <meta name="keywords" content="sistema, system, gerenciador, admin, cms" />
        <meta name="application-name" content="Sistema Administrativo 2.0" />
        <!-- Import google fonts - Heading first/ text second -->
        <link href="//fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet" type="text/css">
        <link href="//fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet" type="text/css">
        
        <!-- Css files -->
        <!-- Icons -->
        <link href="<?php echo $this->main_template;?>css/icons.css" rel="stylesheet" />
        <!-- Bootstrap stylesheets (included template modifications) -->
        <link href="<?php echo $this->main_template;?>css/bootstrap.css" rel="stylesheet" />
        <!-- Plugins stylesheets (all plugin custom css) -->
        <link href="<?php echo $this->main_template;?>css/plugins.css" rel="stylesheet" />
        <!-- Main stylesheets (template main css file) -->
        <link href="<?php echo $this->main_template;?>css/main.css" rel="stylesheet" />
        <!-- Custom stylesheets ( Put your own changes here ) -->
        <link href="<?php echo $this->main_template;?>css/custom.css" rel="stylesheet" />
        
        <link href="<?php echo $this->main_template;?>plugins/ui/bootstrap-sweetalert/new-version/sweetalert.css" rel="stylesheet" />
        <!-- Fav and touch icons -->
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="<?php echo $this->logo_client;?>">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?php echo $this->logo_client;?>">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?php echo $this->logo_client;?>">
        <link rel="apple-touch-icon-precomposed" href="<?php echo $this->logo_client;?>">
        <link rel="icon" type="image/x-icon" href="<?php echo $this->logo_client;?>">
        <!-- Windows8 touch icon ( http://www.buildmypinnedsite.com/ )-->
        
        <meta name="msapplication-TileColor" content="#3399cc" />
        
        <script type="text/javascript">
            var root_path = "<?php echo $this->root_path ?>";
            var system_path = "<?php echo $this->system_path ?>";
            var main_template = "<?php echo $this->main_template ?>";
            var main_scripts = "<?php echo $this->main_scripts ?>";
        </script>