
<!-- / #wrapper -->
<!-- Back to top -->
<div id="back-to-top"><a href="#">Back to Top</a>
</div>
<!-- Javascripts -->
<!-- Load pace first -->
<!-- <script src="<?= $this->main_template;?>plugins/core/pace/pace.min.js"></script> -->
<!-- Important javascript libs(put in all pages) -->
<script src="<?= $this->main_template;?>js/jquery-2.1.1.min.js"></script>
<script>
window.jQuery || document.write('<script src="<?= $this->main_template;?>js/libs/jquery-2.1.1.min.js">\x3C/script>')
</script>
<script src="<?= $this->main_template;?>js/jquery-ui-1.10.4.js"></script>
<script>
window.jQuery || document.write('<script src="<?= $this->main_template;?>js/libs/jquery-ui-1.10.4.min.js">\x3C/script>')
</script>
<script src="<?= $this->main_template;?>js/jquery-migrate-1.2.1.min.js"></script>
<script>
window.jQuery || document.write('<script src="<?= $this->main_template;?>js/libs/jquery-migrate-1.2.1.min.js">\x3C/script>')
</script>

<script type="text/javascript" src="<?= $this->main_template;?>js/jquery.mousewheel.js"></script>
<script type="text/javascript" src="<?= $this->main_template;?>js/jquery.scrollTo.js"></script>

<!-- Form plugins -->
<script type="text/javascript" src="<?= $this->main_template;?>plugins/forms/clickform/jquery.clickform.js"></script>

<!--[if lt IE 9]>
<script type="text/javascript" src="<?= $this->main_template;?>js/libs/excanvas.min.js"></script>
<script type="text/javascript" src="<?= $this->main_template;?>http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<script type="text/javascript" src="<?= $this->main_template;?>js/libs/respond.min.js"></script>
<![endif]-->
<!-- Bootstrap plugins -->
<script src="<?= $this->main_template;?>js/bootstrap/bootstrap.js"></script>
<!-- Core plugins ( not remove ) -->
<script src="<?= $this->main_template;?>js/libs/modernizr.custom.js"></script>
<!-- Handle responsive view functions -->
<script src="<?= $this->main_template;?>js/jRespond.min.js"></script>
<!-- Custom scroll for sidebars,tables and etc. -->
<script src="<?= $this->main_template;?>plugins/core/slimscroll/jquery.slimscroll.min.js"></script>
<script src="<?= $this->main_template;?>plugins/core/slimscroll/jquery.slimscroll.horizontal.min.js"></script>
<!-- Remove click delay in touch -->
<!-- <script src="<?= $this->main_template;?>plugins/core/fastclick/fastclick.js"></script> -->
<!-- Increase jquery animation speed -->
<script src="<?= $this->main_template;?>plugins/core/velocity/jquery.velocity.min.js"></script>
<!-- Quick search plugin (fast search for many widgets) -->
<script src="<?= $this->main_template;?>plugins/core/quicksearch/jquery.quicksearch.js"></script>
<!-- Bootbox fast bootstrap modals -->
<script src="<?= $this->main_template;?>plugins/ui/bootbox/bootbox.js"></script>
<!-- Other plugins ( load only nessesary plugins for every page) -->
<script src="<?= $this->main_template;?>plugins/charts/sparklines/jquery.sparkline.js"></script>

<script src="<?= $this->main_template;?>plugins/forms/autosize/jquery.autosize.js"></script>

<script src="<?= $this->main_template;?>plugins/ui/title-notifier/title_notifier.js"></script>
<script src="<?= $this->main_template;?>plugins/ui/notify/jquery.gritter.js"></script>
<script src="<?= $this->main_template;?>plugins/ui/bootstrap-sweetalert/new-version/sweetalert-dev.js"></script>
<script src="<?= $this->main_template;?>js/jquery.supr.js"></script>
<script src="<?= $this->main_template;?>js/main.js"></script>

<script src="<?= $this->main_template;?>plugins/forms/bootstrap-datepicker/bootstrap-datepicker.js"></script>
<script type="text/javascript" src="<?= $this->main_template;?>js/jquery.mask.min.js"></script>
<script src="<?= $this->main_template;?>js/system_scripts.js?984681486168186"></script>

<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.7.5/angular.min.js"></script>

<script src="//rawcdn.githack.com/CarlosBonetti/jquery-loading/v1.3.0/dist/jquery.loading.js"></script>
<link href="//rawcdn.githack.com/CarlosBonetti/jquery-loading/v1.3.0/dist/jquery.loading.css" type="text/css" rel="stylesheet" />

<script src="<?= $this->main_template;?>js/novaServices.js"></script>