<?php require_once $this->main_layouts."headers.phtml";?>
    <link href="<?= $this->main_template ?>plugins/tables/dataTables/jquery.dataTables.css" type="text/css" rel="stylesheet" />
    <link href="<?= $this->main_template ?>plugins/tables/dataTables/TableTools.css" type="text/css" rel="stylesheet" />
    <script type="text/javascript">
        var pagina = "<?= $this->getPath(); ?>";
        var permissao = "<?= $this->permissao_ref; ?>";
        var controller = "<?= $this->getModule(); ?>";
    </script>
    </head>  
    <body ng-app='nova' ng-controller="Ctrl as ctrl" style='display:none' ng-init='ctrl.onInit()'>
	<?php require_once $this->main_layouts."header.phtml"; ?>
        <div id="wrapper">
	    <?php require_once $this->main_layouts."sidebar.phtml"; ?>
            <div id="content" class="page-content clearfix">
                <div class="contentwrapper">
                    <div class="heading">
                        <h3><?= $this->module_title; ?></h3>
                        <ul class="breadcrumb">
                            <li>Você está aqui:</li>
                            <li> <a href="#" class="tip" title="Painel"> <i class="s16 icomoon-icon-screen-2"></i> </a> <span class="divider"> <i class="s16 icomoon-icon-arrow-right-3"></i> </span> </li>
                            <li class="active"><?= $this->module_title;?></li>
                        </ul>
                    </div>
                    <div class="row">
                        <div class="col-md-3 col-sm-3 col-xs-6">
                            <a href="#" class="chartShortcuts no-hover">
                                <span class="head">Total de Pets</span>
                                <span class="number"><?php echo $this->indicacoes ?></span>
                            </a>
                        </div>
                        <div class="col-md-3 col-sm-3 col-xs-6">
                            <a href="#" class="chartShortcuts no-hover">
                                <span class="head">Pets Pendentes</span>
                                <span class="number"><?php echo $this->indicacoes_pendentes ?></span>
                            </a>
                        </div>
                        <div class="col-md-3 col-sm-3 col-xs-6">
                            <a href="#" class="chartShortcuts no-hover">
                                <span class="head">Pets Arquivados</span>
                                <span class="number"><?php echo $this->indicacoes_arquivadas ?></span>
                            </a>
                        </div>
                        <div class="col-md-3 col-sm-3 col-xs-6">
                            <a href="#" class="chartShortcuts no-hover">
                                <span class="head">Pets Ativados</span>
                                <span class="number"><?php echo $this->indicacoes_ativadas ?></span>
                            </a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="panel panel-default toggle ">
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <i class="icomoon-icon-stats-up"></i> Total de pets nos Últimos 30 dias
                                        <input class="date box-header-date de datepicker" name="de_visitors_chart" type="text" placeholder="De: ">
                                        <input class="date box-header-date ate datepicker" name="ate_visitors_chart" type="text" placeholder="Até: ">
                                    </h4>
                                </div>
                                <div class="panel-body" >
                                    <div class="vital-stats">
                                        <div class="visitors-chart" style="height: 230px;width:100%;margin-top:15px; margin-bottom:15px;"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row" style="display: flex; justify-content: flex-end; margin-right: -9px;">
                        <div class="dropdown mb10 mr10">
                            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false"> Relatórios <span class="caret"></span> </button>
                            <ul class="dropdown-menu right animated fadeIn" role="menu">
                                <li><a onclick="openRel('<?php echo $this->getPath(); ?>/exporttab')" ><span class="s14 icomoon-icon-new-tab color-black"></span>Relatório na tela</a></li>
                                <li><a onclick="openRel('<?php echo $this->getPath(); ?>/export')" ><span class="s14 icomoon-icon-file-excel color-black"></span>Baixar Relatório em Excel</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="panel panel-default toggle">
                                <div class="panel-heading">
                                    <h4 class="panel-title"><i class="<?= $this->module_icon ?>"></i><?= $this->module_title;?></h4>
                                </div>
                                <div class="panel-body">
                                <div class="col-md-12 filters" >
                                        <i class="fa fa-filter"></i>
                                        
                                        <button class='btn-filter'> Especie
                                            <div class="panel groupfilter" style='display:none'>
                                                <div class="panel-body" >
                                                    <form class="form-horizontal" >
                                                        <div class="col-md-12 form-group box-filter">
                                                            <div class="input-group input-icon">
                                                                <input type="text" class="form-control" placeholder="Filtrar ..." ng-model="especieFiltro">
                                                                <span class="input-group-addon"><i class="icomoon-icon-search-3 s16"></i></span>
                                                            </div>
                                                            <div class="checkbox-custom" style='text-align: left;' ng-repeat='row in ctrl.listEspecies | filter:especieFiltro'>
                                                                <input type="checkbox" id="especies{{$index}}" ng-true-value='"{{row.id}}"' ng-false-value="''" ng-model='ctrl.especies[row.id]'>
                                                                <label for="especies{{$index}}" >{{row.titulo}}</label>
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <div class="col-lg-12">
                                                                <a ng-click='ctrl.filter()' class="btn btn-default btn-filtrar">Filtrar</a>
                                                            </div>
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </button>

                                        <button class='btn-filter'> Raça
                                            <div class="panel groupfilter" style='display:none'>
                                                <div class="panel-body" >
                                                    <form class="form-horizontal" >
                                                        <div class="col-md-12 form-group box-filter">
                                                            <div class="input-group input-icon">
                                                                <input type="text" class="form-control" placeholder="Filtrar ..." ng-model="racasFiltro">
                                                                <span class="input-group-addon"><i class="icomoon-icon-search-3 s16"></i></span>
                                                            </div>
                                                            <div class="checkbox-custom" style='text-align: left;' ng-repeat='row in ctrl.listRacas | filter:racasFiltro'>
                                                                <input type="checkbox" id="racas{{$index}}" ng-true-value='"{{row.id}}"' ng-false-value="''" ng-model='ctrl.racas[row.id]'>
                                                                <label for="racas{{$index}}" >{{row.titulo}}</label>
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <div class="col-lg-12">
                                                                <a ng-click='ctrl.filter()' class="btn btn-default btn-filtrar">Filtrar</a>
                                                            </div>
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </button>

                                        <button class='btn-filter'> Status
                                            <div class="panel groupfilter" style='display:none'>
                                                <div class="panel-body" >
                                                    <form class="form-horizontal" >
                                                        <div class="col-md-12 form-group box-filter">
                                                        <div class="checkbox-custom" style='text-align: left;'>
                                                                <input type="checkbox" id="status0" ng-true-value='"Pendente"' ng-false-value="''" ng-model='ctrl.status[0]'>
                                                                <label for="status0">Pendente</label>
                                                            </div>
                                                            <div class="checkbox-custom" style='text-align: left;'>
                                                                <input type="checkbox" id="status1" ng-true-value='"Ativada"' ng-false-value="''" ng-model='ctrl.status[1]'>
                                                                <label for="status1">Ativada</label>
                                                            </div>
                                                            <div class="checkbox-custom" style='text-align: left;'>
                                                                <input type="checkbox" id="status3" ng-true-value='"Cancelado"' ng-false-value="''" ng-model='ctrl.status[2]'>
                                                                <label for="status3">Cancelado</label>
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <div class="col-lg-12">
                                                                <a ng-click='ctrl.filter()' class="btn btn-default btn-filtrar">Filtrar</a>
                                                            </div>
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </button>
                                        
                                        <button class='btn-filter'> Planos
                                            <div class="panel groupfilter" style='display:none'>
                                                <div class="panel-body" >
                                                    <form class="form-horizontal" >
                                                        <div class="col-md-12 form-group box-filter">
                                                            <div class="input-group input-icon">
                                                                <input type="text" class="form-control" placeholder="Filtrar ..." ng-model="planoFiltro">
                                                                <span class="input-group-addon"><i class="icomoon-icon-search-3 s16"></i></span>
                                                            </div>
                                                            <div class="checkbox-custom" style='text-align: left;' ng-repeat='row in ctrl.listPlanos | filter:planoFiltro'>
                                                                <input type="checkbox" id="plano{{$index}}" ng-true-value='"{{row.id}}"' ng-false-value="''" ng-model='ctrl.plano[row.id]'>
                                                                <label for="plano{{$index}}" >{{row.titulo}}</label>
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <div class="col-lg-12">
                                                                <a ng-click='ctrl.filter()' class="btn btn-default btn-filtrar">Filtrar</a>
                                                            </div>
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </button>

                                        <i ng-click='ctrl.clearFilter()' class="icomoon-icon-remove-3 btn-filter cursor tip" data-original-title="Limpar Filtros"></i>
                                    </div>

                                    <table cellpadding="0" cellspacing="0" border="0" class="tabletools-async table table-striped table-bordered" width="100%">
                                        <thead>
                                            <tr>
                                                <th class="tal" >ID</th>
                                                <th class="tal" >Nome do Pet</th>
                                                <th class="tal" >Nome do Tutor</th>
                                                <th class="tal" >Espécie</th>
                                                <th class="tal" >Raça</th>
                                                <th class="tal" >Nome do Plano</th>
                                                <th class="tal" >Valor do Plano</th>
                                                <th class="tal" >Situação</th>
                                                <th width="100px" class="center">Ação</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php require_once $this->main_layouts."options.phtml"; ?>
                </div>
            </div>
        <?php require_once $this->main_layouts."footer.phtml"; ?>
        </div>
        <?php require_once $this->main_layouts."plugins.phtml"; ?>
        <script src="<?= $this->main_template ?>plugins/tables/dataTables/jquery.dataTables.js"></script>
        <script src="<?= $this->main_template ?>plugins/tables/dataTables/dataTables.tableTools.js"></script>
        <script src="<?= $this->main_template ?>plugins/tables/dataTables/dataTables.bootstrap.js"></script>
        <script src="<?= $this->main_template ?>plugins/tables/dataTables/dataTables.responsive.js"></script>
        <script src="<?php echo $this->main_template; ?>plugins/charts/flot/jquery.flot.custom.js"></script>
        <script src="<?php echo $this->main_template; ?>plugins/charts/flot/jquery.flot.pie.js"></script>
        <script src="<?php echo $this->main_template; ?>plugins/charts/flot/jquery.flot.resize.js"></script>
        <script src="<?php echo $this->main_template; ?>plugins/charts/flot/jquery.flot.time.js"></script>
        <script src="<?php echo $this->main_template; ?>plugins/charts/flot/jquery.flot.orderBars.js"></script>
        <script src="<?php echo $this->main_template; ?>plugins/charts/flot/jquery.flot.tooltip.min.js"></script>
        <script type="text/javascript">
            var oTable;
            var totalReg = 0;
            var chartColours = ['#88bbc8', '#ed7a53', '#9FC569', '#bbdce3', '#9a3b1b', '#5a8022', '#2c7282'];
            $(document).ready(function() {

                $(".datepicker").mask("##/##/####");
                $(".datepicker").datepicker({
                });

                $('.de').val(`<?= date('d/m/Y', strtotime("-30 days", strtotime(date('Y-m-d')))); ?>` );
                $('.ate').val(`<?= date('d/m/Y'); ?>`);


                oTable = $('.tabletools-async').dataTable({
                    "bProcessing": true,
                    "bServerSide": true,
                    "sAjaxSource": "<?= $this->system_path.$this->getPath();?>/datatable",
                    "fnServerParams": function ( aoData ) {
                        getParameter(aoData);
                    },
                    "fnServerData": function ( sSource, aoData, fnCallback, oSettings ) {
                        oSettings.jqXHR = $.ajax( { "dataType": 'json', "type": "POST", "url": sSource, "data": aoData, "success": fnCallback })
                        .done(function(data){ 
                            totalReg = Number(data.iTotalDisplayRecords); 
                            uniform(); $('.notsort').removeClass('sorting'); 
                            $("td:has(> .pendente)").css('background-color', "#F2F167");
                            $("td:has(> .ativada)").css('background-color', "#82F683");
                            $("td:has(> .arquivada)").css('background-color', "#EF6563");
                        });
                    },
                    "sDom": "<'row'<'col-lg-1'l><'col-lg-11'f>r>t<'row'<'col-lg-6'i><'col-lg-6'p>>",
                    "sPaginationType": "bootstrap",
                    "bJQueryUI": false,
                    "bAutoWidth": false,
                    "iDisplayLength": 50,
                    "oLanguage": { "sProcessing": "<img src='<?= $this->main_template; ?>images/loaders/horizontal/006.gif'><br>Processando...", "sLengthMenu": "_MENU_", "sZeroRecords": "Não foram encontrados resultados", "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros", "sInfoEmpty": "Mostrando de 0 até 0 de 0 registros", "sInfoFiltered": "", "sInfoPostFix": "", "sSearch": "", "sUrl": "", "oPaginate": { "sFirst": "Primeiro", "sPrevious": "Anterior", "sNext": "Seguinte", "sLast": "Último" } },
                });
                $(".dataTables_filter input").attr('title', "Tecle ENTER Para Pesquisar");
                $(".dataTables_filter input").unbind();
                $(".dataTables_filter input").removeClass('input-sm');
                $(".dataTables_filter input").keyup( function (e) { if (e.keyCode == 13) oTable.fnFilter(this.value); });

                <?php if ($this->dados_grafico->num_rows): ?>
					$(function () {
						var d1 = [<?php foreach ($this->dados_grafico->rows as $key => $dia) {echo "[$key,".$dia['indicacoes']."]";if ($key < (count($this->dados_grafico->rows) - 1)) {
                            echo ",";
                        }
                        }?>];
						var ticks = [<?php foreach ($this->dados_grafico->rows as $key => $dia) {echo "[$key,'".$dia['dia_mes']."']";if ($key < (count($this->dados_grafico->rows) - 1)) {
                            echo ",";
                        }
                        }?>];
						var placeholder = $(".visitors-chart");
						var options = {
							grid: {
								show: true,
								aboveData: true,
								color: "#3f3f3f" ,
								labelMargin: 5,
								axisMargin: 0,
								borderWidth: 0,
								borderColor:null,
								minBorderMargin: 5 ,
								clickable: true,
								hoverable: true,
								autoHighlight: true,
								mouseActiveRadius: 20
							},
							series: {
								grow: {
									active: false,
									stepMode: "linear",
									steps: 50,
									stepDelay: true
								},
								lines: {
									show: true,
									fill: true,
									lineWidth: 4,
									steps: false
									},
								points: {
									show:true,
									radius: 5,
									symbol: "circle",
									fill: true,
									borderColor: "#fff"
								}
							},
							legend: {
								position: "ne",
								margin: [0,-25],
								noColumns: 0,
								labelBoxBorderColor: null,
								labelFormatter: function(label, series) {
									return label+'&nbsp;&nbsp;';
								}
							},
							yaxis: { min: 0 },
							xaxis: {ticks:ticks, tickDecimals: 0},
							colors: chartColours,
							shadowSize:1,
							tooltip: true,
							tooltipOpts: {
								content: "%s : %y.0",
								shifts: {
									x: -30,
									y: -50
								}
							}
						};
						$.plot(placeholder, [
							{
								label: "Indicações",
								data: d1,
								lines: {fillColor: "#f2f7f9"},
								points: {fillColor: "#88bbc8"}
							}
						], options);
					});
					$("input[name='de_visitors_chart'],input[name='ate_visitors_chart']").on("change", function(){
						var de_chart = $("input[name='de_visitors_chart']").val();
						var ate_chart = $("input[name='ate_visitors_chart']").val();
						var de = de_chart.split("/");
						var ate = ate_chart.split("/");
						de = de[2] + '-' + de[1] + '-' + de[0];
						ate = ate[2] + '-' + ate[1] + '-' + ate[0];
						if (ate < de) {
							$(".visitors-chart").html('<div class="well" style="color:black">A data final não pode ser menor que a data inicial!</div>');
						} else {
							if (de_chart.length && ate_chart.length){
								$(".visitors-chart").html("<center><img alt='Carregando...' src='images/loaders/circular/055.gif'/></center>");
								$.ajax({
									url: "<?php echo $this->getPath() ?>/chart",
									type: 'POST',
									data: {
										de : de,
										ate : ate
									},
									//dataType: 'json',
									success: function(dt){
										$(".visitors-chart").html(dt);
									}, complete: function() {
									}
								});
							}
						}
					});
                <?php endif;?>
            });

            var querystring = '<?=$_SERVER["QUERY_STRING"]?>';
            function queryFilter(aoData) {
                if(querystring === null) window.history.replaceState(null, '','<?=$this->system_path.$this->getPath();?>/?'+$.param(aoData));
                else if(querystring !== '') aoData = decodeURIComponent(querystring);
                querystring = null;
                return aoData;
            }
            angular.module('nova', ['novaServices'])
            .controller('Ctrl',function($scope, $http, $sce, NS, $window) {
                this.tipos = [];
                
                this.listPlanos = <?=json_encode(array_values($this->planos));?>;
                this.listEspecies = <?=json_encode(array_values($this->especies));?>;
                this.listRacas = <?=json_encode(array_values($this->racas));?>;
                this.especies = [];
                this.racas = [];
                this.status = [];
                this.plano = [];

                this.onInit = () => {
                    $('body').show();
                    this.especies = getParam('especies',true);
                    this.racas = getParam('racas',true);
                    this.status = getParam('status',true);
                    this.plano = getParam('plano',true);
                }

                $window.getParameter = (aoData) => {
                    aoData.push({ "name": 'especies', "value": this.especies });
                    aoData.push({ "name": 'racas', "value": this.racas });
                    aoData.push({ "name": 'status', "value": this.status });
                    aoData.push({ "name": 'plano', "value": this.plano });
                }

                this.clearFilter = () => {
                    this.especies = [];
                    this.racas = [];
                    this.status = [];
                    this.plano = [];
                    oTable.fnFilter('');
                }

                this.filter = () => {
                    $('.groupfilter').hide();
                    oTable.fnFilter();
                }
                getParam = (prop, mult = false) => {
                    let params = new URLSearchParams(querystring);
                    if(mult) {
                        let a = [];
                        (params.get(prop) || '').split(",").forEach(x => { a[x] = x; });
                        return a;
                    } else return params.get(prop);
                }
            });
           
            function openRel(url) {
                if(totalReg > 5000) { if(!confirm(`Há ${$("#totalwp").html()} registros selecionados, um numero grande de registros que pode gerar erros. Filtros podem diminuir essa quantidade. \nDeseja continuar?`)) return; }
                window.open(url);
            }
            function openRelPDF(url) {
                if(totalReg > 1000) {
                    alert(`Há ${$("#totalwp").html()} registros selecionados, um numero grande de registros que pode gerar erros. No máximo 1.000 registros. Adicione Filtros para diminuir essa quantidade.`);
                    // if(!confirm(`Há ${$("#totalwp").html()} registros selecionados, um numero grande de registros que pode gerar erros. Filtros podem diminuir essa quantidade. \nDeseja continuar?`)) return;
                } else {
                    window.open(url);
                }
            }
        </script>
    </body>
</html>
