<?php require_once $this->main_layouts . "headers.phtml"; ?>
    <script type="text/javascript">
        var pagina = "<?php echo $this->getPath(); ?>";
        var permissao = "<?php echo $this->permissao_ref; ?>";
        var controller = "<?php echo $this->getPath(); ?>";
    </script>
    </head>
    <body>
        <?php require_once $this->main_layouts . "header.phtml"; ?>
        <div id="wrapper">
            <?php require_once $this->main_layouts . "sidebar.phtml"; ?>
            <div id="content" class="page-content clearfix">
                <div class="contentwrapper">
                    <div class="heading">
                        <h3><?php echo $this->module_title; ?></h3>
                        <ul class="breadcrumb">
                            <li>Você está aqui:</li>
                            <li>
                                <a href="#" class="tip" title="Painel">
                                    <i class="s16 icomoon-icon-screen-2"></i>
                                </a>
                                <span class="divider">
                                    <i class="s16 icomoon-icon-arrow-right-3"></i>
                                </span>
                            </li>
                            <li class="active"><?php echo $this->module_title; ?></li>
                        </ul>
                    </div>
                    <?php if ($this->pendentes->num_rows) : ?>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default ">
                                    <div class="panel-heading">
                                        <h4 class="panel-title"><i class="<?php echo $this->module_icon ?>"></i> Tabela de Módulos Pendentes</h4>
                                    </div>
                                    <div class="panel-body">
                                        <table border="0" class="table table-striped table-bordered" width="100%">
                                            <thead>
                                                <tr>
                                                    <th width="35%" class="tal">Cliente</th>
                                                    <th width="20%" class="tal">Evento</th>
                                                    <th width="15%" class="tal">Valor</th>
                                                    <th width="15%" class="tal">Data de Vencimento</th>
                                                    <th width="15%" class="tal">Data de Renovação</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <?php foreach ($this->pendentes->rows as $registro) : ?>
                                                    <tr>
                                                        <td class="tal"><a href="<?php echo $this->getPath() ?>/edit/id/<?php echo $registro['id_cliente']; ?>"><?php echo $registro['nickname']; ?></a></td>
                                                        <td class="tal"><a href="<?php echo $this->getPath() ?>/edit/id/<?php echo $registro['id_cliente']; ?>"><?php echo $registro['nome']; ?></a></td>
                                                        <td class="tal"><a href="<?php echo $this->getPath() ?>/edit/id/<?php echo $registro['id_cliente']; ?>"><?php echo $this->formataMoedaDeBanco($registro['valor']); ?></a></td>
                                                        <td class="tal"><a href="<?php echo $this->getPath() ?>/edit/id/<?php echo $registro['id_cliente']; ?>"><?php echo ($registro['data_vencimento'] ? $this->formataDataDeBanco($registro['data_vencimento']) : null); ?></a></td>
                                                        <td class="tal"><a href="<?php echo $this->getPath() ?>/edit/id/<?php echo $registro['id_cliente']; ?>"><?php echo ($registro['data_aviso_renovacao'] ? $this->formataDataDeBanco($registro['data_aviso_renovacao']) : null); ?></a></td>
                                                    </tr>
                                                <?php endforeach; ?>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>
                    <div class="row">
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-6">
                            <a href="#" class="chartShortcuts">
                                <span class="head">Clientes Registrados</span>
                                <span class="number"><?php echo $this->total ?></span>
                            </a>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-6">
                            <a href="#" class="chartShortcuts">
                                <span class="head">Clientes Desativados</span>
                                <span class="number"><?php echo $this->inactives ?></span>
                            </a>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-6">
                            <a href="#" class="chartShortcuts">
                                <span class="head">Clientes Ativos</span>
                                <span class="number"><?php echo $this->actives ?></span>
                            </a>
                        </div>
                    </div>
                    <?php if ($this->permissions[$this->permissao_ref]['gravar']) : ?>
                        <div class="row">
                            <div class="col-lg-12">
                                <a href="<?php echo $this->getPath(); ?>/create"><button type="button" class="btn btn-default mr5 mb10"><i class="glyphicon glyphicon-plus mr5"></i> Novo cliente</button></a>
                            </div>
                        </div>
                    <?php endif; ?>                    
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="panel panel-default toggle panelClose">
                                <!-- Start .panel -->
                                <div class="panel-heading">
                                    <h4 class="panel-title"><i class="<?php echo $this->module_icon ?>"></i> Tabela de Clientes</h4>
                                </div>
                                <div class="panel-body">
                                    <table cellpadding="0" cellspacing="0" border="0" class="tabletools table table-striped table-bordered" width="100%">
                                        <thead>
                                            <tr>
                                                <th style="display:none;"></th>
                                                <th width="20%" class="tal">Criado em</th>
                                                <th width="20%" class="tal">Identificador</th>
                                                <th width="30%" class="tal">Nome</th>
                                                <th width="30%" class="tal">Telefone</th>
                                                <th width="10%" class="center">Módulos</th>
                                                <th style="min-width: 120px" class="center">Ação</th>
                                                <th style="display:none" class="center"></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php foreach ($this->list->rows as $registro) : ?>
                                                <tr id="<?php echo $registro['id']; ?>">
                                                    <th style="display:none;"><?php echo $registro['registrado_em'] ?></th>
                                                    <td class="center"><a href="<?php echo $this->getPath() ?>/edit/id/<?php echo $registro['id']; ?>"><?php echo $registro['registrado_em_']; ?></a></td>
                                                    <td class="center"><a href="<?php echo $this->getPath() ?>/edit/id/<?php echo $registro['id']; ?>"><?php echo $registro['nickname']; ?></a></td>
                                                    <td class="tal"><a href="<?php echo $this->getPath() ?>/edit/id/<?php echo $registro['id']; ?>"><?php echo $registro['nome_fantasia']; ?></a></td>
                                                    <td class="tal"><a href="<?php echo $this->getPath() ?>/edit/id/<?php echo $registro['id']; ?>"><?php echo $registro['telefone']; ?></a></td>
                                                    <td class="tal"><a href="<?php echo $this->getPath() ?>/edit/id/<?php echo $registro['id']; ?>"><?php echo $registro['modulos']; ?></a></td>
                                                    <td style="display:none"><?= $registro['stats'] ?></td>
                                                    <td class="center">
                                                        <?php if ($registro['stats'] == 0) { ?>
                                                            <a href="#" class="bt_system_stats" data-permit="<?php echo $this->permissao_ref ?>" data-table="<?php echo $this->table; ?>" data-action="ativar" data-id="<?php echo $registro['id']; ?>" data-db="cms"><img src="<?php echo $this->main_template; ?>images/status_vermelho.png" alt="Ativar"></a>
                                                        <?php } else { ?>
                                                            <a href="#" class="bt_system_stats" data-permit="<?php echo $this->permissao_ref ?>" data-table="<?php echo $this->table; ?>" data-action="desativar" data-id="<?php echo $registro['id']; ?>" data-db="cms"><img src="<?php echo $this->main_template; ?>images/status_verde.png" alt="Desativar"></a>
                                                        <?php } ?>
                                                        <a href="<?php echo $this->getPath() ?>/edit/id/<?php echo $registro['id']; ?>"><i class="s12 icomoon-icon-pencil"></i></a>
                                                        <?php if ($this->permissions[$this->permissao_ref]['excluir']) : ?>
                                                            <a class="bt_system_delete" data-controller="<?php echo $this->getPath() ?>" data-id="<?php echo $registro['id']; ?>" href="#"><i class="s12 icomoon-icon-remove"></i></a>
                                                        <?php endif ?>
                                                    </td>
                                                </tr>
                                            <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php require_once $this->main_layouts . "options.phtml"; ?>
                </div>
            </div>
            <?php require_once $this->main_layouts . "footer.phtml"; ?>
        </div>
        <?php require_once $this->main_layouts . "plugins.phtml"; ?>
        <script src="<?php echo $this->main_template;?>plugins/tables/dataTables/jquery.dataTables.js"></script>
        <script src="<?php echo $this->main_template;?>plugins/tables/dataTables/dataTables.tableTools.js"></script>
        <script src="<?php echo $this->main_template;?>plugins/tables/dataTables/dataTables.bootstrap.js"></script>
        <script src="<?php echo $this->main_template;?>plugins/tables/dataTables/dataTables.responsive.js"></script>
        <script type="text/javascript">
            $(document).ready(function() {  
                if ($('table').hasClass('tabletools')) {
                    $('.tabletools').dataTable({
                        "pageLength": 25,
                        "oLanguage": { "sSearch": "", "sLengthMenu": "<span>_MENU_</span>", "sProcessing": "Processando...", "sZeroRecords": "Não foram encontrados resultados", "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros", "sInfoEmpty": "Mostrando de 0 até 0 de 0 registros", "sInfoFiltered": "(filtrado de _MAX_ registros no total)", "sInfoPostFix": "", "sUrl": "", "oPaginate": { "sFirst": "Primeiro", "sPrevious": "Anterior", "sNext": "Seguinte", "sLast": "Último" } },
                        "sDom": "T<'row'<'col-md-6 col-xs-12 'l><'col-md-6 col-xs-12'f>r>t<'row'<'col-md-4 col-xs-12'i><'col-md-8 col-xs-12'p>>",
                        "aaSorting": [ [0, "desc"] ],
                        tableTools: {
                            "sSwfPath": "http://cdn.datatables.net/tabletools/2.2.2/swf/copy_csv_xls_pdf.swf",
                            "aButtons": []
                        }
                    });
                }
            });
        </script>
    </body>
    </html>