<?php
require_once $this->main_layouts . "headers.phtml";
?>
<script type="text/javascript">
    var pagina = "<?php echo $this->getPath(); ?>";
    var permissao = "<?php echo $this->permissao_ref; ?>";
    var controller = "<?php echo $this->getPath(); ?>/save";
    var retorno = "<?php echo $this->retorno; ?>";
</script>
</head>

<body>
    <?php require_once $this->main_layouts . "header.phtml"; ?>
    <div id="wrapper">
        <?php require_once $this->main_layouts . "sidebar.phtml"; ?>
        <div id="content" class="page-content clearfix">
            <div class="contentwrapper">
                <div class="heading">
                    <h3><?php echo $this->module_title; ?></h3>
                    <ul class="breadcrumb">
                        <li>Você está aqui:</li>
                        <li>
                            <a href="#" class="tip" title="Painel">
                                <i class="s16 icomoon-icon-screen-2"></i>
                            </a>
                            <span class="divider">
                                <i class="s16 icomoon-icon-arrow-right-3"></i>
                            </span>
                        </li>
                        <li>
                            <a class="tip" title="<?php echo $this->module_title; ?>" href="<?php echo $this->getPath(); ?>">
                                <i class="s16 <?php echo $this->module_icon; ?>"></i>
                            </a>
                        </li>
                        <span class="divider">
                            <i class="s16 icomoon-icon-arrow-right-3"></i>
                        </span>
                        <li class="active">Registro</li>
                    </ul>
                </div>
                <form name="main" enctype="multipart/form-data" method="post" class="form-horizontal group-border">
                    <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
                    <input type="hidden" name="retorno" value="<?php echo $this->retorno; ?>">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="panel panel-default toggle">
                                <div class="panel-heading">
                                    <h4 class="panel-title">Dados da transação</h4>
                                </div>
                                <div class="panel-body">
                                    <div class="form-group">
                                        <label class="col-lg-2 control-label" for="titulo">Detalhes:</label>
                                        <div class="col-lg-10">
                                            <pre style="height: 800px;" class="form-control"><?= json_encode($this->registro, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) ?></pre>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </form>
            </div>
        </div>
        <?php require_once $this->main_layouts . "footer.phtml"; ?>
    </div>
    <?php require_once $this->main_layouts . "plugins.phtml"; ?>
    <script src="<?php echo $this->main_template; ?>plugins/forms/autosize/jquery.autosize.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('.elastic').autosize();
        });
    </script>
</body>

</html>