<?php require_once $this->main_layouts . "headers.phtml"; ?>
    <script type="text/javascript">
        var pagina = "<?php echo $this->getPath(); ?>";
        var permissao = "<?php echo $this->permissao_ref; ?>";
        var controller = "<?php echo $this->getPath(); ?>";
        var retorno = "<?php echo $this->getPath(); ?>";
    </script>
    </head>  
    <body>
        <?php require_once $this->main_layouts . "header.phtml"; ?>
        <div id="wrapper">
            <?php require_once $this->main_layouts . "sidebar.phtml"; ?>
            <div id="content" class="page-content clearfix">
                <div class="contentwrapper">
                    <div class="heading">
                        <h3><?php echo $this->module_title; ?></h3>
                        <ul class="breadcrumb">
                            <li>Você está aqui:</li>
                            <li> <a href="#" class="tip" title="Painel"> <i class="s16 icomoon-icon-screen-2"></i> </a> <span class="divider"> <i class="s16 icomoon-icon-arrow-right-3"></i> </span> </li>
                            <li class="active"><?php echo $this->module_title;?></li>
                        </ul>
                    </div>
                    <form name="save_configs" enctype="multipart/form-data" method="post" class="form-horizontal group-border">
                        <input type="hidden" name="retorno" value="<?php echo $this->retorno; ?>">
                        <input type="hidden" name="id" value="<?php echo $this->registro['id'] ?>">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default toggle">
                                    <div class="panel-heading">
                                        <h4 class="panel-title"><?php echo $this->module_title; ?></h4>
                                    </div>
                                    <?php require_once dirname(dirname(__DIR__))."/config-form.php"; ?>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default toggle">
                                    <div class="panel-heading">
                                        <h4 class="panel-title">Notificações</h4>
                                    </div>
                                    <div class="panel-body">
                                        <div class="form-group">
                                            <div class="col-lg-12">
                                                <div class="leftBox">
                                                    <h4>Não recebe</h4>
                                                    <select id="box1View" multiple="multiple" class="multiple nostyle form-control" style="height:300px;">
                                                        <?php 
                                                            $array_user_id = array();
                                                            if($this->notificacoes->num_rows){
                                                                foreach ($this->notificacoes->rows as $notifica) {
                                                                    $array_user_id[] = $notifica['id_usuario'];
                                                                }
                                                            }
                                                        ?>
                                                        <?php if ($this->users->num_rows): ?>
                                                            <?php foreach ($this->users->rows as $user): ?>
                                                                <?php if (!in_array($user['id'],$array_user_id)): ?>
                                                                    <option value="<?php echo $user['id'] ?>"><?php echo $user['nome'] . " - " .$user['email'] ?></option>
                                                                <?php endif ?>
                                                            <?php endforeach ?>
                                                        <?php endif ?>
                                                    </select>
                                                </div>
                                                <div class="dualBtn">
                                                    <button id="to2" type="button" class="btn" ><span class="icon12 minia-icon-arrow-right-3"></span></button>
                                                    <button id="allTo2" type="button" class="btn" ><span class="icon12 iconic-icon-last"></span></button>
                                                    <button id="to1" type="button" class="btn marginT5"><span class="icon12 minia-icon-arrow-left-3"></span></button>
                                                    <button id="allTo1" type="button"class="btn marginT5" ><span class="icon12 iconic-icon-first"></span></button>
                                                </div>
                                                <div class="rightBox">
                                                    <h4>Recebe</h4>
                                                    <select id="box2View" multiple="multiple" name="emails[]" class="multiple nostyle form-control" style="height:300px;">
                                                        <?php if ($this->notificacoes->num_rows): ?>
                                                            <?php
                                                                $notifica_user = array();
                                                                $i = 0;
                                                                foreach ($this->notificacoes->rows as $notifica) {
                                                                    echo json_encode($notifica);
                                                                    foreach($this->users->rows as $user){
                                                                        if($notifica['id_usuario'] == $user['id']){
                                                                            echo $notifica['id_usuario'];
                                                                            $notifica_user[$i] = $notifica;
                                                                            $notifica_user[$i]['id'] = $user['id'];
                                                                            $notifica_user[$i]['nome'] = $user['nome'];
                                                                            $notifica_user[$i]['email'] = $user['email'];
                                                                            $i++;
                                                                        }
                                                                    }
                                                                }
                                                            ?>
                                                            <?php foreach ($notifica_user as $user): ?>
                                                                    <option value="<?php echo $user['id'] ?>"><?php echo $user['nome'] . " - " .$user['email'] ?></option>
                                                            <?php endforeach ?>
                                                        <?php endif ?>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                        <?php if (!$this->permissions[$this->permissao_ref]['editar']): ?>
                                            <div class="form-group">
                                                <div class="col-lg-offset-2 col-lg-10">
                                                    <span class="label label-warning"><span class="icon24 icomoon-icon-warning "></span>Você não tem permissão para editar esta função.</span>
                                                </div>
                                            </div>
                                        <?php else: ?>
                                            <div class="form-group">
                                                <div class="col-lg-offset-2 col-lg-10" style="text-align:right;">
                                                    <button type="button" class="btn btn-info clickformsubmit btn-lg">Salvar alterações</button>
                                                </div>
                                            </div>
                                        <?php endif ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                    <div class="row">
                        <div class="col-lg-12">
                            <a href="<?php echo $this->getPath();?>/editSituacao"><button type="button" class="btn btn-default mr5 mb10"><i class="glyphicon glyphicon-plus mr5"></i> Nova situação</button></a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="panel panel-default toggle panelClose">
                                <div class="panel-heading">
                                    <h4 class="panel-title"><i class="<?php echo $this->module_icon ?>"></i> Tabela de Situações
                                    </h4>
                                </div>
                                <div class="panel-body">
                                    <table cellpadding="0" cellspacing="0" border="0" class="tabletools table table-striped table-bordered sortable_free" data-sortable-action="desk/trabalheconoscoconfiguracao/orderSituacao" width="100%">
                                        <thead>
                                            <tr>
                                                <th width="10%" class="center">Ordem</th>
                                                <th width="80%" class="tal">Nome</th>
                                                <th style="min-width: 120px" class="center">Ação</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php if ($this->listSituacoes->num_rows) : ?>
                                            <?php $ordem=1; ?>
                                                <?php foreach($this->listSituacoes->rows as $registro):?>
                                                    <tr id="<?php echo $registro['id'];?>">
                                                        <td class="center"><?php echo $ordem ?></td>
                                                        <td class="tal"><a href="<?php echo $this->getPath()?>/editSituacao/id/<?php echo $registro['id']; ?>"><?php echo $registro['nome']; ?></a></td>
                                                        <td class="center">
                                                            <a href="<?php echo $this->getPath()?>/editSituacao/id/<?php echo $registro['id']; ?>"><i class="s12 icomoon-icon-pencil"></i></a>
                                                            <?php if ($this->permissions[$this->permissao_ref]['excluir']): ?>
                                                                <a class="bt_system_delete" data-controller="<?php echo $this->getPath()?>" data-id="<?php echo $registro['id']; ?>" data-del="delSituacao" href="#"><i class="s12 icomoon-icon-remove"></i></a>
                                                            <?php endif ?>
                                                        </td>
                                                    </tr>
                                                    <?php $ordem++; ?>
                                                <?php endforeach; ?>
                                            <?php endif; ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php require_once $this->main_layouts . "options.phtml"; ?>
                </div>
            </div>
            <?php require_once $this->main_layouts . "footer.phtml"; ?>
        </div>
        <?php require_once $this->main_layouts . "plugins.phtml"; ?>
        <script src="<?php echo $this->main_template;?>plugins/tables/dataTables/jquery.dataTables.js"></script>
        <script src="<?php echo $this->main_template;?>plugins/tables/dataTables/dataTables.tableTools.js"></script>
        <script src="<?php echo $this->main_template;?>plugins/tables/dataTables/dataTables.bootstrap.js"></script>
        <script src="<?php echo $this->main_template;?>plugins/tables/dataTables/dataTables.responsive.js"></script>
        <script src="<?php echo $this->main_template;?>plugins/forms/dualselect/jquery.dualListBox-1.3.min.js"></script>
        <script src="<?php echo $this->main_template;?>plugins/forms/summernote/summernote.js"></script>
        <script type="text/javascript">
            $(document).ready(function(){
                $.configureBoxes();
                $('.summernote').summernote({ disableDragAndDrop: true, toolbar: [ ['style', ['bold', 'italic', 'underline', 'clear']], ['color', ['color']], ['insert', ['link']]], height: 100 });
                if($('table').hasClass('tabletools')) {
                    $('.tabletools').dataTable( {
                        "oLanguage": { "sSearch": "", "sLengthMenu": "<span>_MENU_</span>", "sProcessing": "Processando...", "sZeroRecords": "Não foram encontrados resultados", "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros", "sInfoEmpty": "Mostrando de 0 até 0 de 0 registros", "sInfoFiltered": "(filtrado de _MAX_ registros no total)", "sInfoPostFix": "", "sUrl": "", "oPaginate": { "sFirst": "Primeiro", "sPrevious": "Anterior", "sNext": "Seguinte", "sLast": "Último" } },
                        "sDom": "T<'row'<'col-md-6 col-xs-12 'l><'col-md-6 col-xs-12'f>r>t<'row'<'col-md-4 col-xs-12'i><'col-md-8 col-xs-12'p>>",
                        "aaSorting":[[0,"asc"]],
                        tableTools: {
                            "sSwfPath": "http://cdn.datatables.net/tabletools/2.2.2/swf/copy_csv_xls_pdf.swf",
                            "aButtons": [ ]
                        }
                    });
                }
                $("form[name=save_configs]").clickform({"validateUrl": controller+'/saveConfig'}, function (data) {
                    if (data.type == "success") {
                        if (typeof data.retorno != 'undefined')
                            window.location.href = data.retorno;
                        else
                            window.location.href = retorno;
                    }else if(typeof data.login != 'undefined'){
                        var popup = document.createElement("div");
                        popup.setAttribute("id", "popup_login");
                        popup.innerHTML = data.content;
                        $(document.body).append(popup);
                    }
                });
                var order = '';
                var sortable_array = [];
                var controlerAction = '';
                var conta = 0;
                var totalSortable = $("table.sortable_free").length;
                $(".sortable_livre .sortablelivresubmit").click(function (e) {
                    e.preventDefault();
                    $(".fixed_options_footer, .fixed_option_space, .sortable_livre").hide();
                    $("table.sortable_free").fadeTo(500, 0.5, function () {
                        var _self = $(this);
                        $.post(system_path + _self.attr('data-sortable-action'), {"array": sortable_array}, function (data) {
                            _self.fadeTo(500, 1);
                        });
                    });
                });
                $("table.sortable_free").sortable({
                    opacity: 0.7, cursor: 'move', axis: 'y', items: "tbody tr", update: function (e, ui) {
                        sortable_array = $(this).sortable("toArray");
                        order = $(this).find(".order").attr("data-order");
                        $(".fixed_options_footer, .fixed_option_space, .sortable_livre").show();
                    }
                });
            });
        </script>
    </body>
</html>
