<?php require_once $this->main_layouts . "headers.phtml"; ?>
<script type="text/javascript">
    var pagina = "<?php echo $this->getPath(); ?>";
    var permissao = "<?php echo $this->permissao_ref; ?>";
    var controller = "<?php echo $this->getPath(); ?>/save";
    var retorno = "<?php echo $this->retorno; ?>";
</script>
</head>
<body>
<?php require_once $this->main_layouts . "header.phtml"; ?>
<div id="wrapper">
    <?php require_once $this->main_layouts . "sidebar.phtml"; ?>
    <div id="content" class="page-content clearfix">
        <div class="contentwrapper">
            <div class="heading">
                <h3><?php echo $this->module_title; ?></h3>
                <ul class="breadcrumb">
                    <li>Você está aqui:</li>
                    <li>
                        <a href="#" class="tip" title="Painel">
                            <i class="s16 icomoon-icon-screen-2"></i>
                        </a>
                        <span class="divider">
                            <i class="s16 icomoon-icon-arrow-right-3"></i>
                        </span>
                    </li>
                    <li>
                        <a class="tip" title="<?php echo $this->module_title; ?>" href="<?php echo $this->module_link; ?>">
                            <i class="s16 <?php echo $this->module_icon; ?>"></i>
                        </a>
                    </li>
                    <span class="divider">
                        <i class="s16 icomoon-icon-arrow-right-3"></i>
                    </span>
                    <li class="active">Registro</li>
                </ul>
            </div>
            <form name="main" enctype="multipart/form-data" method="post" class="form-horizontal group-border">
                <input type="hidden" name="id" value="<?php echo $this->id; ?>"/>
                <input type="hidden" name="retorno" value="<?php echo $this->retorno; ?>">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="panel panel-default toggle">
                            <div class="panel-heading">
                                <h4 class="panel-title">Dados Sobre</h4>
                            </div>
                            <div class="panel-body">
                                <div class="form-group target_toggle">
                                    <label class="col-lg-2 control-label" for="texto">Texto:</label>
                                    <div class="col-lg-10">
                                        <textarea class="form-control elastic tinymce" name="texto" id="texto"><?php echo $this->registro['texto']; ?></textarea>
                                    </div>
                                </div>
                                <div class="form-group target_toggle">
                                    <label class="col-lg-2 control-label" for="fileupload">Imagem:</label>
                                    <div class="col-lg-10">
                                        <label class="fileupload" for="fileupload">
                                            <?php if ($this->registro['imagem'] == "") : ?>
                                                <img src="http://placehold.it/<?= $this->crop_sizes[0]['width']; ?>x<?= $this->crop_sizes[0]['height']; ?>?text=<?= $this->crop_sizes[0]['width']; ?>x<?= $this->crop_sizes[0]['height']; ?>" alt="" class="image marginR10"/>
                                            <?php else : ?>
                                                <img src="<?php echo $this->getImageFileSized($this->registro['imagem'],$this->crop_sizes[0]['width'],$this->crop_sizes[0]['height']); ?>" alt="" class="image marginR10"/>
                                            <?php endif; ?>
                                        </label>
                                        <input type="file" name="fileupload" id="fileupload" class="files btn btn-default"/>
                                        <span class="help-block blue">a imagem será apresentada na seguinte proporção <?= $this->crop_sizes[0]['width']; ?>x<?= $this->crop_sizes[0]['height']; ?> pixels.</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="panel panel-default toggle ">
                            <div class="panel-heading">
                                <h4 class="panel-title">Galeria</h4>
                            </div>
                            <div class="panel-body">
                                <div class="row" id="table-gallery">
                                    <div class="col-lg-12">
                                        <a href="cms/sobre_galerias/edit/id_sobre/<?php echo $this->id; ?>">
                                            <button type="button" class="btn btn-default mr5 mb10"><i class="glyphicon glyphicon-plus mr5"></i> Novo registro</button>
                                        </a>
                                    </div>
                                </div>
                                <table cellpadding="0" cellspacing="0" border="0" class="tabletools table table-striped table-bordered sortable" width="100%">
                                    <thead>
                                    <tr>
                                        <th width="5%" class="center">Ordem</th>
                                        <th width="75%" class="tal">Título</th>
                                        <th width="10%" class="center">Status</th>
                                        <th style="min-width: 120px" class="center">Ação</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php if (!empty($this->galeria)) : ?>
                                        <?php $index = 1; ?>
                                        <?php foreach ($this->galeria as $registro) : ?>
                                            <tr id="<?php echo $registro['id']; ?>" class="order" data-order="cms/sobre-galerias/orderGallery">
                                                <td class="center"><a class="confirm_redirect" data-id="<?php echo $registro['id']; ?>" data-controller="cms/sobre_galerias" href="cms/sobre_galerias/edit/id/<?php echo $registro['id']; ?>/id_sobre/<?php echo $this->id; ?>"><?php echo $index; ?></a></td>
                                                <td class="tal"><a class="confirm_redirect" data-id="<?php echo $registro['id']; ?>" data-controller="cms/sobre_galerias" href="cms/sobre_galerias/edit/id/<?php echo $registro['id']; ?>/id_sobre/<?php echo $this->id; ?>"><?php echo $registro['titulo']; ?></a></td>
                                                <td class="center">
                                                    <?php if ($registro['stats'] == 0) : ?>
                                                        <a href="#" class="bt_system_stats" data-permit="<?php echo $this->permissao_ref; ?>" data-table="hbrd_cms_sobre_galerias" data-action="ativar" data-id="<?php echo $registro['id']; ?>" data-db="cms"><img src="<?php echo $this->main_template; ?>images/status_vermelho.png" alt="Ativar"></a>
                                                    <?php else : ?>
                                                        <a href="#" class="bt_system_stats" data-permit="<?php echo $this->permissao_ref; ?>" data-table="hbrd_cms_sobre_galerias" data-action="desativar" data-id="<?php echo $registro['id']; ?>" data-db="cms"><img src="<?php echo $this->main_template; ?>images/status_verde.png" alt="Desativar"></a>
                                                    <?php endif; ?>
                                                </td>
                                                <td class="center">
                                                    <a href="cms/sobre_galerias/edit/id/<?php echo $registro['id']; ?>/id_sobre/<?php echo $this->id; ?>"><i class="s12 icomoon-icon-pencil"></i></a>
                                                    <?php if ($this->permissions[$this->permissao_ref]['excluir']): ?>
                                                        <a class="bt_system_delete" data-controller="cms/sobre_galerias" data-id="<?php echo $registro['id']; ?>" href="#"><i class="s12 icomoon-icon-remove"></i></a>
                                                    <?php endif; ?>
                                                </td>
                                            </tr>
                                            <?php $index++; ?>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <?php if ($this->id == "") : ?>
                        <?php if (!$this->permissions[$this->permissao_ref]['gravar']) : ?>
                            <div class="form-group">
                                <div class="col-lg-offset-2 col-lg-10">
                                    <span class="label label-warning "><span class="icon24 typ-icon-warning"></span>Você não tem permissão para gravar esta função.</span>
                                </div>
                            </div>
                        <?php else : ?>
                            <div class="form-group">
                                <div class="col-lg-offset-2 col-lg-10">
                                    <button type="button" class="btn btn-info clickformsubmit">Salvar novo</button>
                                </div>
                            </div>
                        <?php endif; ?>
                    <?php else : ?>
                        <?php if (!$this->permissions[$this->permissao_ref]['editar']) : ?>
                            <div class="form-group">
                                <div class="col-lg-offset-2 col-lg-10">
                                    <span class="label label-warning">
                                        <span class="icon24 icomoon-icon-warning "></span>
                                        Você não tem permissão para editar esta função.
                                    </span>
                                </div>
                            </div>
                        <?php else : ?>
                            <div class="form-group">
                                <div class="col-lg-offset-2 col-lg-10">
                                    <button type="button" class="btn btn-info clickformsubmit">Salvar alterações</button>
                                </div>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>
                </div>
            </form>
        </div>
    </div>
    <?php require_once $this->main_layouts . "footer.phtml"; ?>
</div>
<?php require_once $this->main_layouts . "plugins.phtml"; ?>
<script src="<?php echo $this->main_template; ?>plugins/forms/autosize/jquery.autosize.js"></script>
<script src="<?php echo $this->main_template; ?>plugins/forms/tiny_mce/tinymce.min.js"></script>
<script type="text/javascript" src="<?php echo $this->main_template; ?>plugins/forms/dualselect/jquery.dualListBox-1.3.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $.configureBoxes();
        saveKey(true);
        tinymceInit({css:'tinymce.css'});
        $('.elastic').autosize();
    });
</script>
</body>
</html>
