<?php
 $data = $this->DB_fetch_array("SELECT * FROM hbrd_adm_company where id = 1", 'string')->rows[0]['logo'];
 $base64 = 'data:image/jpeg;base64,' . base64_encode($data);
?>
<html>
<head>
	<style>
	table {
		border-collapse: collapse;
		width: 100%;
	}
	td, th {
		border: 1px solid #dddddd;
		text-align: center;
		padding: 3px;
	}
	tr:nth-child(even) {
		background-color: #dddddd;
	}
	table *{
		vertical-align: middle;
	}
	.footer-table td {
		font-weight: bold;
	}
	.main div img {
		float: left;
	}
	.blue th, .blue td {
		background : #0f243f;
		color: white;
		height: 30px;
	}
	.main div {
		padding : 20px;
	}
	.linhas td {
		height: 20px;
	}
	.logo{
		margin-right: 10px;
	}
	</style>
</head>
<body>
	<div class='main'>
		<div>
			<img class="logo" width='150' src="<?php echo $base64; ?>" alt="Página Inicial" />
			<h2>Relatório de Doações</h2>
			<i>Emitido em <b><?php echo date("d/m/Y H:i:s"); ?></b> por <b><?php echo $_SESSION["admin_nome"]; ?></b>.</i>
		</div>
		<table>
			<tr class='blue'>
	     		<th style='width: 40%;'>Nome do doador</th>
				<th style='width: 10%;'>Campanha</th>
				<th style='width: 10%;'>Telefone</th>
				<th style='width: 10%;'>Email</th>
				<th style='width: 10%;'>Data</th>
				<th style='width: 10%;'>Tipo</th>
				<th style='width: 10%;'>Valor</th>
			</tr>
			<?php foreach ($Doacoes->rows as $registro) : ?>
				<tr class='linhas'>
				<td><?php echo ($registro["nome_doador"] ?? '' ); ?></td>
				<td><?php echo ($registro["campanha"] ?? '' ); ?></td>
				<td><?php echo ($registro["telefone_doador"] ?? ''); ?></td>
				<td><?php echo ($registro["email_doador"] ?? ''); ?></td>
				<td><?php echo ($registro['criacao'] ?? ''); ?></td>
				<td><?php echo (ucfirst($registro['tipo'] ?? '')); ?></td>
				<td style="text-align:right"><?php echo ($this->formataMoedaDeBanco($registro['valor'] ?? '')); ?></td>
				</tr>
			<?php endforeach ?>
			<tr class='footer-table blue'>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
		</table>
	</div>
	<br>
	<br>
	<i>Gerenciado por <b><?php echo $this->root_path ?></b></i>
</body>
</html>