<?php require_once $this->main_layouts."headers.phtml"; ?>
    <link href="<?= $this->main_template; ?>plugins/gallery/jpages/jPages.css" rel="stylesheet" type="text/css" />
    <link href="<?= $this->main_template; ?>plugins/forms/select/select2.css" type="text/css" rel="stylesheet" />
    <script type="text/javascript">
        var pagina = "<?= $this->getPath(); ?>";
        var permissao = "<?= $this->permissao_ref; ?>";
        var controller = "<?= $this->getPath(); ?>/save";
        var retorno = "<?= $this->retorno; ?>";
    </script>
    </head>  
    <body ng-app='nova' ng-controller="EditCtrl as ctrl" style='display:none' ng-init='ctrl.onInit()'>
        <?php require_once $this->main_layouts."header.phtml"; ?>
        <div id="wrapper">
            <?php require_once $this->main_layouts."sidebar.phtml"; ?>
            <div id="content" class="page-content clearfix">
                <div class="contentwrapper">
                    <div class="heading">
                        <h3><?= $this->module_title; ?></h3>
                        <ul class="breadcrumb">
                            <li>Você está aqui</li>
                            <li><a href="#" class="tip" title="Painel"><i class="s16 icomoon-icon-screen-2"></i></a>
                                <span class="divider"><i class="s16 icomoon-icon-arrow-right-3"></i></span>
                            </li>
                            <li><a class="tip" title="<?= $this->module_title; ?>" href="<?= $this->module_link;?>"><i class="s16 <?= $this->module_icon; ?>"></i></a></li>
                            <span class="divider"><i class="s16 icomoon-icon-arrow-right-3"></i></span>
                            <li class="active">Registro</li>
                        </ul>
                    </div>

                    <form class="form-horizontal group-border" ng-submit='ctrl.submitData()'>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default toggle">
                                    <div class="panel-heading">
                                        <h4 class="panel-title">Dados do Campanha de Doação</h4>
                                    </div>
                                    <div class="panel-body">
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="nome">Nome</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" ng-model='ctrl.data.nome' />
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="relato">Descrição da Doação</label>
                                            <div class="col-lg-10">
                                                <textarea class="form-control" rows='5' ng-model='ctrl.data.descricao'></textarea>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="nome">Responsavel</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" ng-model='ctrl.data.responsavel' />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="row">
                            <?php if ($this->id==""): ?>
                                <?php if (!$this->permissions[$this->permissao_ref]['gravar']): ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <span class="label label-warning "><span class="icon24 typ-icon-warning"></span>Você não tem permissão para gravar esta função.</span>
                                        </div>
                                    </div>   
                                <?php else: ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <button type="submit" class="btn btn-info">Salvar novo</button>
                                        </div>
                                    </div>
                                <?php endif ?>
                            <?php else: ?>
                                <?php if (!$this->permissions[$this->permissao_ref]['editar']): ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <span class="label label-warning"><span class="icon24 icomoon-icon-warning "></span>Você não tem permissão para editar esta função.</span>
                                        </div>
                                    </div>   
                                <?php else: ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <button type="submit" class="btn btn-info">Salvar alterações</button>
                                        </div>
                                    </div>
                                <?php endif ?>
                            <?php endif ?>
                        </div>
                        
                    </form>
                </div>
            </div>
            <?php require_once $this->main_layouts."footer.phtml"; ?>
        </div>

        <div id="modalvariaveis" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title">Palavras-chaves</h4>
                    </div>
                    <div class="modal-body">
                        <ul class="list-group">
                            <?php foreach($this->items as $item) : ?>
                            <li ng-click='ctrl.copy("<?= $item['variavel'] ?>")' class="cursor list-group-item"><strong><?= $item['variavel'] ?></strong> - <?= $item['descricao'] ?></li>
                            <?php endforeach ?>
                        </ul>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                    </div>
                </div>
            </div>
        </div>
        
        <?php require_once $this->main_layouts."plugins.phtml"; ?>
        <script type="text/javascript" src="<?= $this->main_template; ?>plugins/forms/dualselect/jquery.dualListBox-1.3.min.js"></script>
        <script type="text/javascript" src="<?= $this->main_template; ?>plugins/forms/timeentry/jquery.timeentry.min.js"></script>
        <script type="text/javascript" src="<?= $this->main_template; ?>plugins/forms/select/select2.js"></script>

        <script type="text/javascript">
            $(document).ready(function(){
                $(".select2").select2();
            });

            angular.module('nova', ['novaServices'])
            .controller('EditCtrl',function($scope, $http, $sce, NS, $window) {
                this.data = <?= json_encode($this->registro); ?>;

                this.onInit = () => {
                    $('body').show();
                }

                this.submitData = async () => {
                    await NS.actionHandler($http.post(`<?= $this->getPath();?>/save`,this.data));
                    location.href= pagina;
                }

                this.copy = async (text) => {
                    await navigator.clipboard.writeText(text);
                    NS.notifSucess('Variável copiada');
                    $('#modalvariaveis').modal('toggle');
                }
            })
        </script>
    </body>
</html>
