<?php require_once $this->main_layouts . "headers.phtml"; ?>
    <script type="text/javascript">
        var pagina = "<?php echo $this->getPath(); ?>";
        var permissao = "<?php echo $this->permissao_ref; ?>";
        var controller = "<?php echo $this->getPath(); ?>/save";
        var retorno = "<?php echo $this->retorno; ?>";
    </script>
    </head> 
    <body ng-app='nova' ng-controller="Ctrl as ctrl" style='display:none' ng-init='ctrl.onInit()'>
    <?php  require_once $this->main_layouts . "header.phtml"; ?>
        <div id="wrapper">
        <?php  require_once $this->main_layouts . "sidebar.phtml"; ?>
            <div id="content" class="page-content clearfix">
                <div class="contentwrapper">
                    <div class="heading">
                        <h3><?php echo $this->module_title; ?></h3>
                        <ul class="breadcrumb">
                            <li>Você está aqui:</li>
                            <li> <a href="#" class="tip" title="Painel"> <i class="s16 icomoon-icon-screen-2"></i> </a> <span class="divider"> <i class="s16 icomoon-icon-arrow-right-3"></i> </span> </li>
                            <li class="active"><?php echo $this->module_title;?></li>
                        </ul>
                    </div>                    
                    <div class="row">
                        <div class="col-lg-12">
                            <a href="<?php echo $this->getPath(); ?>/edit"><button type="button" class="btn btn-default mr5 mb10"><i class="glyphicon glyphicon-plus mr5"></i> Novo registro</button></a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="panel panel-default toggle panelClose">
                                <!-- Start .panel -->
                                <div class="panel-heading">
                                    <h4 class="panel-title"><i class="<?php echo $this->module_icon ?>"></i> Tabela de Raças
                                        <label class="select-all">Selecionar estes <input type="checkbox" id="apagar_todos"></label>
                                    </h4>
                                </div>
                                <div class="panel-body">
                                    <div class="col-md-12 filters" >
                                    <i class="fa fa-filter"></i>
                                        <button class='btn-filter'> Especie
                                            <div class="panel groupfilter" style='display:none'>
                                                <div class="panel-body" >
                                                    <form class="form-horizontal" >
                                                        <div class="col-md-12 form-group box-filter">
                                                            <div class="input-group input-icon">
                                                                <input type="text" class="form-control" placeholder="Filtrar ..." ng-model="especieFiltro">
                                                                <span class="input-group-addon"><i class="icomoon-icon-search-3 s16"></i></span>
                                                            </div>
                                                            <div class="checkbox-custom" style='text-align: left;' ng-repeat='row in ctrl.listEspecies | filter:especieFiltro'>
                                                                <input type="checkbox" id="especies{{$index}}" ng-true-value='"{{row.id}}"' ng-false-value="''" ng-model='ctrl.especies[row.id]'>
                                                                <label for="especies{{$index}}" >{{row.titulo}}</label>
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <div class="col-lg-12">
                                                                <a ng-click='ctrl.filter()' class="btn btn-default btn-filtrar">Filtrar</a>
                                                            </div>
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </button>
                                        <i ng-click='ctrl.clearFilter()' class="icomoon-icon-remove-3 btn-filter cursor tip" data-original-title="Limpar Filtros"></i>
                                    </div>

                                    <table cellpadding="0" cellspacing="0" border="0" class="tabletools table table-striped table-bordered" width="100%">
                                        <thead>
                                            <tr>
                                                <th width="60%" class="tal">Nome</th>
                                                <th width="20%" class="tal">Espécie</th>
                                                <th style="min-width: 120px" class="center">Ação</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php if($this->list->num_rows): ?>
                                                <tr ng-repeat="row in ctrl.racas">
                                                    <td class="tal"><a href="<?php echo $this->getPath(); ?>/edit/id/{{row.id}}">{{row.titulo}}</a></td>
                                                    <td class="tal"><a href="<?php echo $this->getPath(); ?>/edit/id/{{row.id}}">{{row.especie}}</a></td>
                                                    <td class="center">
                                                        <a href="<?php echo $this->getPath()?>/edit/id/{{row.id}}"><i class="s12 icomoon-icon-pencil"></i></a>
                                                        <?php if ($this->permissions[$this->permissao_ref]['excluir']): ?>
                                                            <a class="bt_system_delete" data-controller="<?php echo $this->getPath()?>" data-id="{{row.id}}" href="#"><i class="s12 icomoon-icon-remove"></i></a>
                                                            <input type="checkbox" id="del_{{row.id}}" value="{{row.id}}" class="del-this">
                                                        <?php endif ?>
                                                    </td>
                                                </tr>
                                            <?php endif ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php require_once $this->main_layouts . "options.phtml"; ?>
                </div>
                <!-- End contentwrapper -->
            </div>
            <!-- End #content -->
            
            
<?php  require_once $this->main_layouts . "footer.phtml"; ?>
        
        </div>
        
<?php  require_once $this->main_layouts . "plugins.phtml"; ?>
        <!-- Table plugins -->
        <script src="<?php echo $this->main_template;?>plugins/tables/dataTables/jquery.dataTables.js"></script>
        <script src="<?php echo $this->main_template;?>plugins/tables/dataTables/dataTables.tableTools.js"></script>
        <script src="<?php echo $this->main_template;?>plugins/tables/dataTables/dataTables.bootstrap.js"></script>
        <script src="<?php echo $this->main_template;?>plugins/tables/dataTables/dataTables.responsive.js"></script>
        <script type="text/javascript">
            $(document).ready(function(){

                //--------------- Data tables ------------------//
                if($('table').hasClass('tabletools')){
                    $('.tabletools').dataTable( {
                        "oLanguage": {
                            "sSearch": "",
                            "sLengthMenu": "<span>_MENU_</span>",
                            "sProcessing":   "Processando...",                    
                            "sZeroRecords":  "Não foram encontrados resultados",
                            "sInfo":         "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                            "sInfoEmpty":    "Mostrando de 0 até 0 de 0 registros",
                            "sInfoFiltered": "(filtrado de _MAX_ registros no total)",
                            "sInfoPostFix":  "",
                            "sUrl":         "",

                            "oPaginate": {
                                "sFirst":    "Primeiro",
                                "sPrevious": "Anterior",
                                "sNext":     "Seguinte",
                                "sLast":     "Último"
                            }
                        },
                        "sDom": "T<'row'<'col-md-6 col-xs-12 'l><'col-md-6 col-xs-12'f>r>t<'row'<'col-md-4 col-xs-12'i><'col-md-8 col-xs-12'p>>",
                        "aaSorting":[[0,"asc"]], "iDisplayLength": 50,
                        tableTools: {
                            "sSwfPath": "http://cdn.datatables.net/tabletools/2.2.2/swf/copy_csv_xls_pdf.swf",
                            "aButtons": [
                          ]
                        }


                    });

                }

            });

            var querystring = '<?=$_SERVER["QUERY_STRING"]?>';
            angular.module('nova', ['novaServices'])
            .controller('Ctrl',function($scope, $http, $sce, NS, $window){
                this.listEspecies = <?=json_encode(array_values($this->especies));?>;
                this.especies = [];
                this.racas = <?=json_encode(array_values($this->list->rows));?>;

                this.onInit = () => {
                    $('body').show();
                    this.especies = getParam('especies',true);
                }

                this.filter = async () => {
                    $('.groupfilter').hide();
                    let res = await NS.actionHandler($http.post("<?= $this->system_path . $this->getPath(); ?>/getRacas", {
                        especies: this.especies.join(',')
                    }));
                    this.racas = res.data['aaData'];
                    $scope.$digest();
                }

                this.clearFilter = async () => {
                    this.especies = [];
                    let res = await NS.actionHandler($http.post("<?= $this->system_path . $this->getPath(); ?>/getRacas"));
                    this.racas = res.data['aaData'];
                    $scope.$digest();
                }

                getParam = (prop, mult = false) => {
                    let params = new URLSearchParams(querystring);
                    if(mult) {
                        let a = [];
                        (params.get(prop) || '').split(",").forEach(x => { a[x] = x; });
                        return a;
                    } else return params.get(prop);
                }
            });
        </script>
    </body>
</html>
