<?php require_once $this->main_layouts . "headers.phtml"; ?>
<script type="text/javascript">
    var pagina = "<?php echo $this->getPath(); ?>";
    var permissao = "<?php echo $this->permissao_ref; ?>";
    var controller = "<?php echo $this->getPath(); ?>";
</script>
</head>
<body>
<?php require_once $this->main_layouts . "header.phtml"; ?>
<!-- / #header -->
<div id="wrapper">
<!-- #wrapper -->
<?php require_once $this->main_layouts . "sidebar.phtml"; ?>
    <!--Body content-->
    <div id="content" class="page-content clearfix">
        <div class="contentwrapper">
            <!--Content wrapper-->
            <div class="heading">
                <!--  .heading-->
                <h3><?php echo $this->module_title; ?></h3>

                <ul class="breadcrumb">
                    <li>Você está aqui:</li>
                    <li>
                        <a href="#" class="tip" title="Painel">
                            <i class="s16 icomoon-icon-screen-2"></i>
                        </a>
                        <span class="divider">
                            <i class="s16 icomoon-icon-arrow-right-3"></i>
                        </span>
                    </li>
                    <li class="active"><?php echo $this->module_title;?></li>
                </ul>
            </div>
            <!-- End  / heading-->
            <!-- Start .row -->
            <div class="row">
                <div class="col-lg-12" style="text-align: right;"><a style="margin-bottom: 10px" href="<?php echo $this->system_path.$this->getPath();?>/exportContacts" class="btn btn-info"><span class="s14 icomoon-icon-file-excel color-white"></span> Exportar dados</a></div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default toggle panelClose">
                        <!-- Start .panel -->
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <i class="<?php echo $this->module_icon ?>"></i> Tabela de Contatos
                                <label class="select-all">Selecionar estes <input type="checkbox" id="apagar_todos"></label>
                            </h4>
                        </div>
                        <div class="panel-body">
                            <table cellpadding="0" cellspacing="0" border="0" class="tabletools table table-striped table-bordered" width="100%">
                                <thead>
                                    <tr>
                                        <th style="display:none"></th>
                                        <th class="tal" width="10%">Data</th>
                                        <th class="tal" width="15%">Nome</th>
                                        <th class="tal" width="15%">E-mail</th>
                                        <th class="tal" width="15%">Telefone</th>
                                        <th class="tal" width="15%">Situação</th>
                                        <th class="tal" width="10%">UTM Campaign UTM Source</th>
                                        <th class="tal" width="10%">Checkbox1 / Checkbox2</th>
                                        <th style="min-width: 120px" class="center">Ação</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php if ($this->list->num_rows) : ?>
                                        <?php foreach($this->list->rows as $registro):?>
                                            <tr>
                                                <td style="display:none"><a href="<?php echo $this->getPath()?>/edit/id/<?php echo $registro['id']; ?>"><?php echo $registro['data'];?></a></td>
                                                <td class="tal"><a href="<?php echo $this->getPath()?>/edit/id/<?php echo $registro['id']; ?>"><?php echo $registro['registro'];?></a></td>
                                                <td class="tal"><a href="<?php echo $this->getPath()?>/edit/id/<?php echo $registro['id']; ?>"><?php echo $registro['nome'];?></a></td>
                                                <td class="tal"><a href="<?php echo $this->getPath()?>/edit/id/<?php echo $registro['id']; ?>"><?php echo $registro['email'];?></a></td>
                                                <td class="tal"><a href="<?php echo $this->getPath()?>/edit/id/<?php echo $registro['id']; ?>"><?php echo $registro['telefone'];?></a></td>
                                                <td class="tal"><a href="<?php echo $this->getPath()?>/edit/id/<?php echo $registro['id']; ?>"><?php echo $registro['situacao'];?></a></td>
                                                <td class="tal"><a href="<?= $this->getPath()?>/edit/id/<?= $registro['id']; ?>"><?= $registro['utm_campaign'].' '.$registro['utm_source'];?></a></td>
                                                <td class="tal"><a href="<?= $this->getPath()?>/edit/id/<?= $registro['id']; ?>"><?= ($registro['checkbox1'] == 1 ? 'Sim' : 'Não').' / '.($registro['checkbox2'] == 1 ? 'Sim' : 'Nao');?></a></td>
                                                <td class="center">
                                                    <a href="<?php echo $this->getPath()?>/edit/id/<?php echo $registro['id']; ?>"><i class="s12 icomoon-icon-pencil"></i></a>
                                                    <?php if ($this->permissions[$this->permissao_ref]['excluir']): ?>
                                                        <a class="bt_system_delete" data-controller="<?php echo $this->getPath()?>" data-id="<?php echo $registro['id']; ?>" href="#"><i class="s12 icomoon-icon-remove"></i></a>
                                                        <input type="checkbox" id="del_<?php echo $registro['id']; ?>" value="<?php echo $registro['id']; ?>" class="del-this">
                                                    <?php endif ?>
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div><!-- End .row -->
            <?php  require_once $this->main_layouts . "options.phtml"; ?>
        </div>
        <!-- End contentwrapper -->
    </div>
    <!-- End #content -->
<?php   require_once $this->main_layouts . "footer.phtml"; ?>
</div>
<?php   require_once $this->main_layouts . "plugins.phtml"; ?>
<!-- Table plugins -->
<script src="<?php echo $this->main_template;?>plugins/tables/dataTables/jquery.dataTables.js"></script>
<script src="<?php echo $this->main_template;?>plugins/tables/dataTables/dataTables.tableTools.js"></script>
<script src="<?php echo $this->main_template;?>plugins/tables/dataTables/dataTables.bootstrap.js"></script>
<script src="<?php echo $this->main_template;?>plugins/tables/dataTables/dataTables.responsive.js"></script>
<script src="<?php echo $this->main_template;?>plugins/forms/tiny_mce/tinymce.min.js"></script>
<!-- Init plugins only for page -->
<script type="text/javascript">
    $(document).ready(function(){
        tinymceInit({'galeria':false});
        //--------------- Data tables ------------------//
        if($('table').hasClass('tabletools')){
            $('.tabletools').dataTable( {

                "oLanguage": {
                    "sSearch": "",
                    "sLengthMenu": "<span>_MENU_</span>",
                    "sProcessing":   "Processando...",
                    "sZeroRecords":  "Não foram encontrados resultados",
                    "sInfo":         "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                    "sInfoEmpty":    "Mostrando de 0 até 0 de 0 registros",
                    "sInfoFiltered": "(filtrado de _MAX_ registros no total)",
                    "sInfoPostFix":  "",
                    "sUrl":         "",
                    "oPaginate": {
                        "sFirst":    "Primeiro",
                        "sPrevious": "Anterior",
                        "sNext":     "Seguinte",
                        "sLast":     "Último"
                    }
                },
                "sDom": "T<'row'<'col-md-6 col-xs-12 'l><'col-md-6 col-xs-12'f>r>t<'row'<'col-md-4 col-xs-12'i><'col-md-8 col-xs-12'p>>",
                "aaSorting":[[0,"desc"]],
                "iDisplayLength": 50,
                tableTools: {
                    "sSwfPath": "http://cdn.datatables.net/tabletools/2.2.2/swf/copy_csv_xls_pdf.swf",
                    "aButtons": [
                  ]
                }
            });
        }
        $(".bt_system_edit_situacao").click(function (e) {
            e.preventDefault();
            if (confirm("Deseja realmente alterar o status de todos registros selecionados?")) {
                var registros = $(".del-registros").val().split(','); //valor vindo da input del-registros, array do lista_del
                var ids = []; //aqui será guardado as ids dos registros que não foram possíveis de serem apagados
                var mensagem = null; //mensagem, caso exita, será apresentado como alert
                //caso exista um controller alternativo especificado, ele substituirá o controller padrão da página
                var controle = $(".data-controller").val();
                if (controle)
                    controller = controle;
                var situacao = $("#situacao").val();
                //laço com método post ajax que enviará ao controller os registros (ids) que deverão ser alterados
                    jQuery.ajax({
                        url: "<?php echo $this->getModule();?>/editSituation",
                        type: 'POST',
                        data: {i: registros, situacao: situacao},
                        async: true,
                        jsonp: false,
                        success: function (dt) {
                            if (dt) {
                                alert(dt);
                            } else {
                                window.location.reload();
                            }
                        },
                        complete: function () {
                        }
                    });
                return true;
            } else {
                //caso o usuário desista de apagar os registros selecionados
                return false;
            }
        });
    });
</script>
</body>
</html>
