<?php require_once $this->main_layouts . "headers.phtml"; ?>
<script type="text/javascript">
	var pagina = "<?= $this->getPath(); ?>";
	var permissao = "<?= $this->permissao_ref; ?>";
	var controller = "<?= $this->getPath(); ?>/save";
	var retorno = "<?= $this->retorno; ?>";
	var itemContrller = "<?= $this->getPath(); ?>/item";
</script>
</head>
<body ng-app='nova' ng-controller="EditCtrl as ctrl" ng-init='ctrl.onInit()' style='display:none;'>
	<?php require_once $this->main_layouts . "header.phtml"; ?>
	<div id="wrapper">
		<?php require_once $this->main_layouts . "sidebar.phtml"; ?>
		<div id="content" class="page-content clearfix">
			<div class="contentwrapper">
				<div class="heading">
					<h3><?= $this->module_title; ?></h3>
					<ul class="breadcrumb">
						<li>Você está aqui:</li>
						<li><a href="#" class="tip" title="Painel"><i class="s16 icomoon-icon-screen-2"></i></a><span class="divider"><i class="s16 icomoon-icon-arrow-right-3"></i></span></li>
						<li><a class="tip" title="<?= $this->module_title; ?>" href="<?= $this->module_link; ?>"><i class="s16 <?= $this->module_icon; ?>"></i></a></li>
						<span class="divider"><i class="s16 icomoon-icon-arrow-right-3"></i></span>
						<li class="active">Registro</li>
					</ul>
				</div>
				<div class="form-horizontal group-border">
					<div class="row">
						<div class="col-lg-12">
							<div class="panel panel-default toggle">
								<div class="panel-heading">
									<h4 class="panel-title">Dados do modelo</h4>
								</div>
								<div class="panel-body">
									<form ng-submit='ctrl.submitForm()'>
										<div class="form-group">
											<label class="col-lg-2 control-label" for="nome">Descrição</label>
											<div class="col-lg-10">
												<input class="form-control" required ng-model='ctrl.data.descricao' />
											</div>
										</div>
										
										<div class="col-lg-12">
											<div class="form-group">
												<div class="col-lg-offset-2 col-lg-10">
													<button type="submit" class="btn btn-info">{{ctrl.data.id ? 'Alterar descrição' : 'Criar modelo'}}</button>
												</div>
											</div>
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
				<?php if((bool)$this->id) : ?>
				<div class="form-horizontal group-border">
					<div class="row">
						<div class="col-lg-12">
							<div class="panel panel-default toggle">
								<div class="panel-heading">
									<h4 class="panel-title">Itens do modelo</h4>
									<div style='float:right' data-toggle="tooltip" data-placement="top" data-original-title="Ordenar">
										<a href="<?= $this->retorno; ?>/ordenarItems/id/<?= $this->id ?>"><i class="s16 icomoon-icon-move cursor" style='margin: 8px 11px;'></i></a>
									</div>
								</div>
								<div class="panel-body">
									<div class="form-group">
										<div class="col-lg-10">
											<button ng-click='ctrl.itemModal({})' ng-if='ctrl.data.id' type="button" class="btn btn-info">Criar item</button>
										</div>
									</div>
									<div class="form-group">
										<div class="col-md-4" ng-repeat='row in ctrl.items'>
											<div class="panel panel-default vistoria-panel">
												<div class="panel-heading">
													<h4 class="panel-title"><strong>{{row.descricao}} {{row.required == 1 ? '*' : ''}}</strong></h4>
													<div class="btn-group" role="group" style="">
														<a class="btn btn-default btn-link btn-sm cursor" style="width:50%; color:#000;" ng-click='ctrl.itemModal(row)'>
															<i class="fa fa-pencil mr5"></i>Editar
														</a>
														<a ng-click='ctrl.deleteItem(row)' class="btn btn-default btn-link btn-sm cursor" style="width:50%; color:#000;">
															<i class="fa fa-trash-o mr5"></i>Apagar
														</a>
													</div>
												</div>
												<div class="panel-body">
													<a class='cursor' ng-if='row.imagem' ng-click="ctrl.showImage(row.imagem)">
														<img style='max-height:260px' class='img-responsive' src="{{row.imagem}}">
													</a>
													<p ng-if='!row.imagem'>Sem imagem</p>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<?php endif ?>
				<div class="modal fade modal-style2" id="edit-image">
					<form class="form-horizontal mt20" ng-submit='ctrl.submitItem()'>
						<div class="modal-dialog">
							<div class="modal-content">
								<div class="modal-header">
									<button type="button" class="close" data-dismiss="modal">
										<span aria-hidden="true">&times;</span>
										<span class="sr-only">Close</span>
									</button>
									<h4 class="modal-title" id="exampleModalLabel"></h4>
								</div>
								<div class="modal-body item-vist">
									<div class='form-group'>
										<label class='col-lg-12 control-label' for=''>Descrição</label>
										<div class='col-lg-12'>
											<input class='form-control' ng-model='ctrl.item.descricao' />
										</div>
										<div class='col-lg-12' style='margin-top:20px;'>
											<input class='check' style='vertical-align: sub;' type='checkbox' ng-model='ctrl.item.lib_access' id='lib_access' ng-true-value="1" ng-false-value="0" />
											<label for='lib_access'>Acesso pela biblioteca?</label>
										</div>
										<div class='col-lg-12' style='margin-top:20px;'>
											<input class='check' style='vertical-align: sub;' type='checkbox' ng-model='ctrl.item.required' id='required' ng-true-value="1" ng-false-value="0" />
											<label for='required'>Imagem obrigatória?</label>
										</div>
									</div>
									<div class='form-group'>
										<label class='col-lg-12 control-label' for=''>Imagem exemplo</label>
										<div class='col-lg-12'>
											<input type='file' accept='image/*' imageread='ctrl.item.imagem_exemplo' />
										</div>
									</div>
								</div>
								<div class="modal-footer">
									<button type="button" data-dismiss="modal" class="btn btn-default">Cancelar</button>
									<button type="submit" class="btn btn-primary">Save</button>
								</div>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
		<?php require_once $this->main_layouts . "footer.phtml"; ?>
	</div>
	<?php require_once $this->main_layouts . "plugins.phtml"; ?>
	<?php require_once $this->main_layouts . "photoswipe.phtml"; ?>
	<script type="text/javascript">
		$(document).ready(function() {});
		angular.module('nova', ['novaServices'])
			.controller('EditCtrl', function($scope, $http, $sce, NS, $window) {
				this.data = <?= json_encode($this->registro); ?>;
				this.items = <?= json_encode(array_values($this->items)); ?>;
				this.onInit = () => {
					$('body').show();
				}
				this.submitForm = async () => {
					let res = await NS.actionHandler($http.post("<?= $this->getPath(); ?>/save", this.data));
					if (!this.data.id) location.href = retorno + '/edit/id/' + res.data;
					else location.reload();
				}
				this.itemModal = (item) => {
					this.item = item;
					$('#edit-image').modal("show");
				}
				this.submitItem = async () => {
					this.item.id_modelo = '<?= $this->id ?>';
					await NS.actionHandler($http.post("<?= $this->getPath(); ?>/item", this.item), '#edit-image');
					location.reload();
				}
				this.showImage = (url) => {
					singlePS(url);
				}
				this.deleteItem = async (item) => {
					if (!confirm(`Deletar item de modelo ${item.descricao}`)) return;
					await NS.actionHandler($http.delete("<?= $this->getPath(); ?>/deleteItem/" + item.id));
					location.reload();
				}
			});
	</script>
	<script src="<?= $this->main_template; ?>plugins/ui/lightbox/ekko-lightbox.js"></script>
	<style>
		.panel-controls {
			display: none;
		}
		.vistoria-panel {
			min-height: 400px;
			max-height: 400px;
		}
	</style>
</body>
</html>