<?php require_once $this->main_layouts . "headers.phtml"; ?>
    <script type="text/javascript">
        var pagina = "<?= $this->getPath(); ?>";
        var permissao = "<?= $this->permissao_ref; ?>";
        var controller = "<?= $this->getPath(); ?>/save";
        var retorno = "<?= $this->retorno; ?>";
    </script>
    </head>  
    <body ng-app='nova' ng-controller="Ctrl as ctrl" ng-init='ctrl.onInit()' style='display:none;'>
        <?php require_once $this->main_layouts . "header.phtml"; ?>
        <div id="wrapper">
        <?php require_once $this->main_layouts."sidebar.phtml"; ?>
            <div id="content" class="page-content clearfix">
                <div class="contentwrapper">
                    <div class="heading">
                        <h3><?= $this->module_title; ?></h3>
                        <ul class="breadcrumb">
                            <li>Você está aqui:</li>
                            <li><a href="#" class="tip" title="Painel"><i class="s16 icomoon-icon-screen-2"></i></a>
                                <span class="divider">
                                    <i class="s16 icomoon-icon-arrow-right-3"></i>
                                </span>
                            </li>
                            <li><a class="tip" title="<?= $this->module_title; ?>" href="<?= $this->module_link;?>"><i class="s16 <?= $this->module_icon; ?>"></i></a></li>
                            <span class="divider">
                                <i class="s16 icomoon-icon-arrow-right-3"></i>
                            </span>
                            <li class="active">Registro</li>
                        </ul>
                    </div>
                    <form ng-submit="ctrl.submitForm()" class="form-horizontal group-border">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default toggle">
                                    <div class="panel-heading">
                                        <h4 class="panel-title">Dados básicos</h4>
                                    </div>
                                    <div class="panel-body">
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="foto">Foto de Perfil</label>
                                            <div class="col-lg-10">
                                                <label class="logo" for="foto">
                                                    <?php if ($this->registro['foto'] == null): ?>
                                                        <img src="/main/templates/supradmin/images/SemImagem.png" alt="" class="image marginR10"/>
                                                    <?php else: ?>
                                                        <img style="object-fit: cover;height: 100px;" src="<?= $this->registro['foto'] ?>" alt="" class="image marginR10"/>
                                                    <?php endif ?>
                                                </label>
                                                <input type="file" accept='image/*' imageread="ctrl.registro.foto" class="files btn btn-default"/>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="nome">Nome Completo</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" ng-model="ctrl.registro.nome" />
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="cpf">CPF</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" mask-cpf ng-model="ctrl.registro.cpf" />
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="telefone">Telefone</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" mask-telefone ng-model="ctrl.registro.telefone" />
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" >Telefone secundário</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" mask-telefone ng-model="ctrl.registro.telefone2" />
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="email">E-mail principal</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" ng-model="ctrl.registro.email"/>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default toggle">
                                    <div class="panel-heading">
                                        <h4 class="panel-title">Acesso</h4>
                                    </div>
                                    <div class="panel-body">
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="senha">Senha</label>
                                            <div class="col-lg-10">
                                                <input class="form-control"  type="password"  ng-model="ctrl.registro.novaSenha" autocomplete="new-password"/>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="repetir_senha">Repetir Senha</label>
                                            <div class="col-lg-10">
                                                <input class="form-control"  autocomplete="off"  type="password" ng-model="ctrl.registro.novaSenha2" autocomplete="new-password"/>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                       
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default toggle">
                                    <div class="panel-heading">
                                        <h4 class="panel-title">Endereço</h4>
                                    </div>
                                    <div class="panel-body">
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="cep">CEP</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" mask-cep ng-model="ctrl.registro.cep" ng-change="ctrl.buscaCEP(ctrl.registro.cep)"/>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="rua">Logradouro</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" ng-model="ctrl.registro.rua" />
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="numero">Número</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" ng-model="ctrl.registro.numero"  />
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="complemento">Complemento</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" ng-model="ctrl.registro.complemento" />
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="id_estado">Estado</label>
                                            <div class="col-lg-10">
                                                <select class="form-control" ng-model="ctrl.registro.id_estado" >
                                                    <option value="" hidden>Selecione..</option>
                                                    <?php foreach ($this->estados->rows as $estado) : ?>
                                                    <option ng-value="<?= $estado['id']; ?>"><?= $estado['estado']; ?></option>
                                                    <?php endforeach; ?>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="id_cidade">Cidade</label>
                                            <div class="col-lg-10">
                                                <select class="form-control" ng-disabled="!ctrl.cidades.length" ng-model="ctrl.registro.id_cidade">
                                                    <option value="" hidden>Selecione..</option>
                                                    <option ng-repeat="row in ctrl.cidades" ng-value="row.id">{{ row.cidade }}</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="bairro">Bairro</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" ng-model="ctrl.registro.bairro" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?php if((bool)$this->id) : ?>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default toggle">
                                    <div class="panel-heading">
                                        <h4 class="panel-title">Pets</h4>
                                    </div>
                                    <div class="panel-body">
                                        <div class="form-group">
                                            <div class=" col-lg-12">
                                                <a type="button" class="btn btn-info" href="app/pets/edit/associado/<?= $this->id ?>">Adicionar</a>
                                            </div>
                                        </div>
                                        <table cellpadding="0" cellspacing="0" border="0" class="tabletools table table-striped table-bordered table-items" width="100%">
                                            <thead>
                                                <tr>
                                                    <th class="tal">ID</th>
                                                    <th class="tal">Nome</th>
                                                    <th class="tal">Especie</th>
                                                    <th class="tal">Raça</th>
                                                    <th class="tal">Sexo</th>
                                                    <th class="tal">Porte</th>
                                                    <th class="tal">Plano</th>
                                                    <th class="center" width="10%" class="tal">Ações</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <?php foreach ($this->pets as $row) : ?>
                                                <tr id='<?= $row['id'] ?>'>
                                                    <td class="tal"><a href="app/pets/edit/id/<?= $row['id'] ?>" ><?= $row['id'] ?></a></td>
                                                    <td class="tal"><a href="app/pets/edit/id/<?= $row['id'] ?>" ><?= $row['nome'] ?></a></td>
                                                    <td class="tal"><a href="app/pets/edit/id/<?= $row['id'] ?>" ><?= $row['especie'] ?></a></td>
                                                    <td class="tal"><a href="app/pets/edit/id/<?= $row['id'] ?>" ><?= $row['raca'] ?></a></td>
                                                    <td class="tal"><a href="app/pets/edit/id/<?= $row['id'] ?>" ><?= $row['sexo'] ?></a></td>
                                                    <td class="tal"><a href="app/pets/edit/id/<?= $row['id'] ?>" ><?= $row['porte'] ?></a></td>
                                                    <td class="tal"><a href="app/pets/edit/id/<?= $row['id'] ?>" >PLANO <?= $row['plano'] ?: 'GRATUITO' ?></a></td>
                                                    <td class="center">
                                                        <a href="#"  ><i class="s12 icomoon-icon-pencil"></i></a>
                                                    </td>
                                                </tr>
                                                <?php endforeach ?>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?php endif ?>
                        <div class="row">
                            <?php if ($this->id==""): ?>
                            <?php if (!$this->permissions[$this->permissao_ref]['gravar']): ?>
                            <div class="form-group">
                                <div class="col-lg-offset-2 col-lg-10">
                                    <span class="label label-warning "><span class="icon24 typ-icon-warning"></span>Você não tem permissão para gravar esta função.</span>
                                </div>
                            </div>   
                            <?php else: ?>
                            <div class="form-group">
                                <div class="col-lg-offset-2 col-lg-10">
                                    <button type="submit" class="btn btn-info">Salvar novo</button>
                                </div>
                            </div>
                            <?php endif ?>
                            <?php else: ?>
                            <?php if (!$this->permissions[$this->permissao_ref]['editar']): ?>
                            <div class="form-group">
                                <div class="col-lg-offset-2 col-lg-10">
                                    <span class="label label-warning"><span class="icon24 icomoon-icon-warning "></span>Você não tem permissão para editar esta função.</span>
                                </div>
                            </div>
                            <?php else: ?>
                            <div class="form-group">
                                <div class="col-lg-offset-2 col-lg-10">
                                    <button type="submit" class="btn btn-info">Salvar alterações</button>
                                </div>
                            </div>
                            <?php endif ?>
                            <?php endif ?>
                        </div>
                    </form>
                </div>
            </div>
            <?php require_once $this->main_layouts . "footer.phtml"; ?>
        </div>
        <?php require_once $this->main_layouts."plugins.phtml"; ?>
        <script type="text/javascript">
            $(document).ready(function(){
            });
            angular.module('nova', ['novaServices'])
            .controller('Ctrl', function($scope, $http, $sce, NS, $window) {   
                this.registro = <?= json_encode($this->registro); ?>;
                this.estados = <?= json_encode($this->estados->rows) ?>;
                this.onInit = () => {
                    $('body').show();
                    this.findCidades();
                }
                this.submitForm = async () => {
                    if(this.registro.novaSenha !== this.registro.novaSenha2) return NS.notifInfo("Senhas divergentes");
                    let res = await NS.actionHandler($http.post(`<?= $this->getPath();?>/save`,this.registro));
                    window.location = "<?= $this->getPath(); ?>/edit/id/"+res.data;
                }
                this.buscaCEP = async (cep) => {
                    if(cep.length < 9) return;
                    let data = (await NS.actionHandler($http.get(`https://viacep.com.br/ws/${cep.replace('-','').replace('.','')}/json/`), '#tab-associado', 'Cep consultado')).data;
                    this.registro.rua = data.logradouro;
                    if (!this.registro.complemento) this.registro.complemento = data.complemento;
                    this.registro.bairro = data.bairro;
                    this.registro.id_estado = parseInt(this.estados.find(x => x.uf == data.uf).id);
                    await this.findCidades(this.registro.id_estado);
                    this.registro.id_cidade = this.cidades.find(x => x.cidade == data.localidade).id;
                    
                    $scope.$digest();
                }
                this.findCidades = async () => {
                    if(!this.registro.id_estado) return;
                    this.cidades = [];
                    this.cidades = (await $http.post(`main/general/getCidadesByEstadoId`, { id:this.registro.id_estado })).data;
                    $scope.$digest();
                }
            })
        </script>
    </body>
</html>
