<?php require_once $this->main_layouts . "headers.phtml";?>
    <script type="text/javascript">
        var pagina = "<?= $this->getPath(); ?>";
        var permissao = "<?= $this->permissao_ref; ?>";
        var controller = "<?= $this->getPath(); ?>/save";
        var retorno = "<?= $this->retorno; ?>";
		var itemContrller = "<?= $this->getPath();?>/item";
    </script>
    </head>
    <body ng-app='nova' ng-controller="EditCtrl as ctrl" ng-init='ctrl.onInit()' style='display:none;'>
		<?php require_once $this->main_layouts . "header.phtml"; ?>
		<div id="wrapper">
			<?php require_once $this->main_layouts . "sidebar.phtml"; ?>
				<div id="content" class="page-content clearfix">
					<div class="contentwrapper">
						<div class="heading">
                        <h3><?= $this->module_title; ?></h3>
                        <ul class="breadcrumb">
                            <li>Você está aqui:</li>
                            <li> <a href="#" class="tip" title="Painel"> <i class="s16 icomoon-icon-screen-2"></i> </a> <span class="divider"> <i class="s16 icomoon-icon-arrow-right-3"></i> </span> </li>
                            <li> <a class="tip" title="<?= $this->module_title; ?>" href="<?= $this->module_link;?>"> <i class="s16 <?= $this->module_icon; ?>"></i> </a> </li>
                            <span class="divider">
                                <i class="s16 icomoon-icon-arrow-right-3"></i>
                            </span>
                            <li class="active">Registro</li>
                        </ul>
                    </div>
                    <form ng-submit='ctrl.submitMain()' name="formplano" class="form-horizontal group-border" novalidate>
					<div class="row">
						<div class="col-md-12">
							<div class="tabs mb20">
								<ul id="myTab" class="nav nav-tabs">
									<li class="active">
										<a href="#tab-detalhes" data-toggle="tab">Detalhes</a>
									</li>
									<li class="">
										<a href="#tab-compartilhamento" data-toggle="tab">Compartilhamento</a>
									</li>
								</ul>
								<div id="myTabContent2" class="tab-content">
									<div class="tab-pane fade active in" id="tab-detalhes">
										<div class="panel-body">
											<div class="form-group area">
												<label class="col-lg-2 control-label">Nome</label>
												<div class="col-lg-10">
													<input class="form-control" required ng-model='ctrl.data.titulo' />
												</div>
											</div>
											<div class='form-group'>
												<label class='col-lg-2 control-label'>Regionais</label>
												<div class='col-lg-10'>
													<select class='form-control select2' required multiple="multiple" ng-model='ctrl.data.regionais' >
														<?php foreach($this->regionais as $row):?>
														<option value='<?= $row['id'] ?>'><?= $row['titulo'] ?></option>
														<?php endforeach ?>
													</select>
												</div>
											</div>
											<div class='form-group'>
												<label class='col-lg-2 control-label'>Modelo de Contratos</label>
												<div class='col-lg-10'>
													<select class='form-control' ng-model='ctrl.data.contratos'>
														<?php foreach($this->modelo_contrato->rows as $row):?>
															<option ng-value='<?= $row['id'] ?>'><?= $row['titulo'] ?></option>
														<?php endforeach ?>
													</select>
												</div>
											</div>
	                                        <div class="form-group"> 
												<label class="col-lg-2 control-label">Descrição</label> 
												<div class="col-lg-10"> 
														<textarea class="form-control" ng-model='ctrl.data.descricao' cols="30" rows="5"></textarea>	
												</div> 
											</div>															

											<div class='form-group'>
											<label class='col-lg-2 control-label' >Valor</label>
											<div class='col-lg-10'>
												<div class='input-group'>
													<span class='input-group-addon'>R$</span>
													<input class='form-control' required mask-money ng-model='ctrl.data.valor'/>
												</div>
											</div>
										</div>
										</div>
									</div>
									<div class="tab-pane fade" id="tab-compartilhamento">
										<div class="panel-body">
											<div class="form-group">
												<label class="col-lg-2 control-label" for="shared_msg">Whatsapp<br><small>
													<a href="#" class="btn btn-xs btn-default pull-right" data-toggle="modal" data-target="#modalvariaveis">Palavras-chaves</a>
													</small>
													<br>
													<div class="toggle-custom">
                                                        <label class="toggle" data-on="ON" data-off="OFF" >
                                                            <input type="checkbox" ng-model='ctrl.data.shared_msg_status'  ng-true-value="1" ng-false-value="0">
                                                            <span class="button-checkbox"></span>
                                                        </label>
                                                    </div>
												</label>
												<div class="col-lg-10">
													<textarea name="shared_msg" class="form-control" rows="11"><?= stripslashes($this->registro['shared_msg']) ?></textarea>
												</div>
											</div>
											<div class="form-group">
												<label class="col-lg-2 control-label" for="shared_msg">PDF<br><small>
													<a href="#" class="btn btn-xs btn-default pull-right" data-toggle="modal" data-target="#modalvariaveis">Palavras-chaves</a>
													</small>
													<br>
													<div class="toggle-custom">
                                                        <label class="toggle" data-on="ON" data-off="OFF" >
                                                            <input type="checkbox" ng-model='ctrl.data.shared_pdf_status' ng-change='ctrl.changeDados(row)' ng-true-value="1" ng-false-value="0">
                                                            <span class="button-checkbox"></span>
                                                        </label>
                                                    </div>
													<?php if((bool)$this->id) : ?>
													<a href="<?= $this->getPath(); ?>/previewPDF/<?= $this->id ?>" target='_blank' type="button" class="btn btn-success btn-xs mr5 mb10">Visualizar</a>
													<?php endif ?>
												</label>
												<div class="col-lg-10">
													<textarea tinymce class="form-control" style="height:500px"><?= stripslashes($this->registro['shared_pdf']) ?></textarea>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-12">
							<div class="panel panel-default toggle">
								<div class="panel-heading">
									<h4 class="panel-title"> Benefícios do plano</h4>
								</div>
								<div class="panel-body form-horizontal">
									<div class="form-group">
										<label class="col-lg-2 col-md-3 control-label">Benefícios</label>
										<div class="col-lg-10 col-md-9">
											<?php foreach ($this->beneficios->rows as $beneficio) : ?>
											<div class="checkbox-custom">
										
												<input type="checkbox" name='beneficios[]' value="<?=$beneficio['id']?>" id="checkbox<?=$beneficio['id']?>" <?= ($this->id && ($beneficio['id_plano'] == $this->id)) ? 'checked' : '' ?>>
                                                <label for="checkbox<?=$beneficio['id']?>"><?=$beneficio['nome']?></label>

											</div>
											<?php endforeach ?>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="form-group">
						<div class="col-lg-offset-2">
							<button type="submit" class="btn btn-info">Salvar</button>
							<?php if ($this->permissions($this->permissao_ref,'excluir') && (bool)$this->registro['id']): ?>
							<?php endif ?>
						</div>
					</div>
					</form>
				</div>
			</div>
			<?php require_once $this->main_layouts . "footer.phtml"; ?>
        </div>
		<div id="modalvariaveis" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title">Palavras chaves</h4>
                    </div>
                    <div class="modal-body">
                        <ul class="list-group">
                            <?php foreach($this->variaveis as $row) : ?>
                            <li ng-click='ctrl.copy("<?= $row['variavel'] ?>")' class="cursor list-group-item"><strong><?= $row['variavel'] ?></strong> - <?= $row['descricao'] ?></li>
                            <?php endforeach ?>
                        </ul>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                    </div>
                </div>
            </div>
        </div>
		<div id="modalVarPart" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title">Palavras chaves</h4>
                    </div>
                    <div class="modal-body">
                        <ul class="list-group">
                            <?php foreach($this->variaveisPart as $row) : ?>
                            <li ng-click='ctrl.copy("<?= $row['variavel'] ?>")' class="cursor list-group-item"><strong><?= $row['variavel'] ?></strong> - <?= $row['descricao'] ?></li>
                            <?php endforeach ?>
                        </ul>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                    </div>
                </div>
            </div>
        </div>
		<?php require_once $this->main_layouts . "plugins.phtml"; ?>
		<script type="text/javascript" src="<?php echo $this->main_template;?>plugins/forms/dualselect/jquery.dualListBox-1.3.min.js"></script>
		<script src="<?= $this->main_template;?>plugins/forms/autosize/jquery.autosize.js"></script>
		<script type="text/javascript" src="<?php echo $this->main_template; ?>plugins/forms/select/select2.js"></script>
		<script src="<?php echo $this->main_template; ?>plugins/forms/tiny_mce/tinymce.min.js"></script>
		<script type="text/javascript">
            $(document).ready(function(){
				$.configureBoxes();
				$(".select2").select2();
				tinymceInit2({css:'tinymce-a4.css'});
			});
			angular.module('nova', ['novaServices'])
            .controller('EditCtrl',function($scope, $http, $sce, NS, $window) {
				<?php unset($this->registro['shared_msg']) ?>
				<?php unset($this->registro['shared_pdf']) ?>
				this.data = <?= (bool)$this->registro ? json_encode($this->registro) : '{}' ?>;
				this.planItems = <?= json_encode(array_values($this->planItems->rows)); ?>;
				this.onInit = () => {
					$('body').show();
					this.planItemsFilter = Array.from(this.planItems || []);
					this.id_categoria = 'todos';
					if(this.data.regionais) this.data.regionais = JSON.parse(this.data.regionais).map(x => String(x));
					// if(this.data.contratos) this.data.contratos = JSON.parse(this.data.contratos).map(x => String(x));
					// if(this.data.Benefícios) this.data.Benefícios = JSON.parse(this.data.Benefícios).map(x => String(x));
				}
				this.submitMain = async () => {
					if ($scope.formplano.$invalid) return NS.validateForm($scope.formplano);
					tinymce.triggerSave();
					this.data.shared_pdf = $('[tinymce]').val();
					this.data.shared_msg = $('[name=shared_msg]').val();
					this.data.beneficios = $.map($('[name^=beneficios]:checked'), e => $(e).val())
					let res = await NS.actionHandler($http.post("<?= $this->getPath(); ?>/save", this.data));
					if(!this.data.id) location.href = `${retorno}/edit/id/${res.data}`;
					else location.reload();
				}

				this.deletePlan = async (id) => {
					if(!confirm('Deletar plano?')) return;
					await NS.actionHandler($http.delete("<?= $this->getPath(); ?>/deletePlan/"+id));
					location.href = pagina;
				}

				this.copy = async (toCopy) => {
                    await navigator.clipboard.writeText(toCopy);
                    NS.notifSucess('Variável copiada');
                    $('.modal').modal('hide')
                }
			});
        </script>
		<style>
			.participacao option h1{
				color: red;
			}
		</style>
    </body>
</html>
