<?php
require_once $this->main_layouts . "headers.phtml";
?>
<script type="text/javascript">
    var pagina = "<?php echo $this->getPath(); ?>";
    var permissao = "<?php echo $this->permissao_ref; ?>";
    var controller = "<?php echo $this->getPath(); ?>";
</script>
</head>
<body ng-app='nova' ng-controller="IndexCtrl as ctrl" style='display:none' ng-init='ctrl.onInit()'>
    <?php require_once $this->main_layouts . "header.phtml"; ?>
    <div id="wrapper">
        <?php require_once $this->main_layouts . "sidebar.phtml"; ?>
        <div id="content" class="page-content clearfix">
            <div class="contentwrapper">
                <div class="heading">
                    <h3><?php echo $this->module_title; ?></h3>
                    <ul class="breadcrumb">
                        <li>Você está aqui:</li>
                        <li>
                            <a href="#" class="tip" title="Painel">
                                <i class="s16 icomoon-icon-screen-2"></i>
                            </a>
                            <span class="divider">
                                <i class="s16 icomoon-icon-arrow-right-3"></i>
                            </span>
                        </li>
                        <li class="active"><?php echo $this->module_title; ?></li>
                    </ul>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <a href="<?php echo $this->getPath(); ?>/edit"><button type="button" class="btn btn-default mr5 mb10"><i class="glyphicon glyphicon-plus mr5"></i> Novo plano</button></a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="panel panel-default toggle">
                            <div class="panel-heading">
                                <h4 class="panel-title"><i class="<?php echo $this->module_icon ?>"></i> Tabela de planos
                                <i class="fa fa-question-circle cursor" data-container="body" data-toggle="popover" data-placement="top" data-content="Apenas os 3 primeiros da ordem apareceram no site." ></i>
                                </h4>
                            </div>
                            <div class="panel-body">
                                <table cellpadding="0" cellspacing="0" border="0" class="tabletools table table-striped table-bordered sortable" width="100%">
                                    <thead>
                                        <tr>
                                            <th width="100px" class="tal">Ordem</th>
                                            <th class="tal">Nome</th>
                                            <th class="tal">Regionais</th>
                                            <th width='150px' class="center">Ação</th>
                                            <th style="display:none">Ação</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr ng-repeat='row in ctrl.list' id='{{row.id}}'>
                                            <td class="center"><a href="<?php echo $this->getPath() ?>/edit/id/{{row.id}}">{{$index+1}}</a></td>
                                            <td class="tal"><a href="<?php echo $this->getPath() ?>/edit/id/{{row.id}}">{{row.titulo}}</a></td>
                                            <td class="tal"><a href="<?php echo $this->getPath() ?>/edit/id/{{row.id}}">{{row.regionais}}</a></td>
                                            <td style="display:none" class="tal"><a>{{row.stats}}</a></td>
                                            <td class="center" >
                                                <a class='cursor' ng-if='row.stats === "0"' ng-click='ctrl.stats(row)' title="Ativar"><img src="<?php echo $this->main_template; ?>images/status_vermelho.png"></a>
                                                <a class='cursor' ng-if='row.stats === "1"' ng-click='ctrl.stats(row)' title="Desativar"><img src="<?php echo $this->main_template; ?>images/status_verde.png"></a>
                                                <a class="cursor" ng-click='ctrl.clone(row.id)' title="Clonar"><i class="s12 icomoon-icon-copy"></i></a>
                                                <a href="<?php echo $this->getPath() ?>/edit/id/{{row.id}}"><i class="s12 icomoon-icon-pencil"></i></a>
                                                <a class="cursor" ng-click='ctrl.delete(row)'><i class="s12 icomoon-icon-remove"></i></a>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <?php require_once $this->main_layouts . "options.phtml"; ?>
            </div>
        </div>
        <?php require_once $this->main_layouts . "footer.phtml"; ?>
    </div>
    <?php require_once $this->main_layouts . "plugins.phtml"; ?>
    <script src="<?php echo $this->main_template; ?>plugins/tables/dataTables/jquery.dataTables.js"></script>
    <script src="<?php echo $this->main_template; ?>plugins/tables/dataTables/dataTables.tableTools.js"></script>
    <script src="<?php echo $this->main_template; ?>plugins/tables/dataTables/dataTables.bootstrap.js"></script>
    <script src="<?php echo $this->main_template; ?>plugins/tables/dataTables/dataTables.responsive.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            if ($('table').hasClass('tabletools')) {
                $('.tabletools').dataTable({
                    "pageLength": 25,
                    "oLanguage": { "sSearch": "", "sLengthMenu": "<span>_MENU_</span>", "sProcessing": "Processando...", "sZeroRecords": "Não foram encontrados resultados", "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros", "sInfoEmpty": "Mostrando de 0 até 0 de 0 registros", "sInfoFiltered": "", "sInfoPostFix": "", "sUrl": "", "oPaginate": { "sFirst": "Primeiro", "sPrevious": "Anterior", "sNext": "Seguinte", "sLast": "Último" } },
                    "sDom": "T<'row'<'col-md-6 col-xs-12 'l><'col-md-6 col-xs-12'f>r>t<'row'<'col-md-4 col-xs-12'i><'col-md-8 col-xs-12'p>>",
                    "aaSorting": [ [0, "asc"] ],
                    tableTools: { "sSwfPath": "http://cdn.datatables.net/tabletools/2.2.2/swf/copy_csv_xls_pdf.swf", "aButtons": [] }
                });
            }
        });
        angular.module('nova', ['novaServices'])
            .controller('IndexCtrl', function($scope, $http, $sce, NS, $window) {
                this.list = <?= json_encode($this->list->rows) ?>;
                this.stats = async (row) => {
                    await NS.actionHandler($http.put("<?php echo $this->system_path . $this->getPath(); ?>/changestatus", row));
                    row.stats = row.stats === '1' ? '0' : '1';
                    $scope.$digest();
                }
                this.delete = async (row) => {
                    if (!confirm('Deletar plano?')) return;
                    await NS.actionHandler($http.delete("<?php echo $this->system_path . $this->getPath(); ?>/deletePlan/" + row.id));
                    location.reload()
                }
                this.onInit = () => {
                    $('body').show();
                }
                this.clone = async (id) => {
                    if (!confirm('Clonar plano?')) return;
                    await NS.actionHandler($http.post("<?php echo $this->system_path . $this->getPath() ?>/clone", { id }));
                    location.reload();
                }
            });
    </script>
</body>
</html>