<?php require_once $this->main_layouts."headers.phtml"; ?>
    <script type="text/javascript">
        var pagina = "<?= $this->getPath(); ?>";
        var permissao = "<?= $this->permissao_ref; ?>";
        var controller = "<?= $this->getPath(); ?>";
    </script>
    </head>  
    <body ng-app='nova' ng-controller="Ctrl as ctrl" style='display:none' ng-init='ctrl.onInit()'>
        <?php require_once $this->main_layouts."header.phtml"; ?>
        <div id="wrapper">
        <?php require_once $this->main_layouts."sidebar.phtml"; ?>
            <div id="content" class="page-content clearfix">
                <div class="contentwrapper">
                    <div class="heading">
                        <h3><?= $this->module_title; ?></h3>
                        <ul class="breadcrumb">
                            <li>Você está aqui:</li>
                            <li><a href="#" class="tip" title="Painel"><i class="s16 icomoon-icon-screen-2"></i></a>
                                <span class="divider"><i class="s16 icomoon-icon-arrow-right-3"></i></span>
                            </li>
                            <li class="active"><?= $this->module_title;?></li>
                        </ul>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <a href="<?= $this->getPath();?>/edit"><button type="button" class="btn btn-default mr5 mb10"><i class="glyphicon glyphicon-plus mr5"></i> Novo registro</button></a>
                        </div>
                    </div> 
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="panel panel-default toggle ">
                                <div class="panel-heading">
                                    <h4 class="panel-title"><i class="<?= $this->module_icon ?>"></i> Tabela de Situações</h4>
                                </div>
                                <div class="panel-body">
                                    <table cellpadding="0" cellspacing="0" border="0" class="tabletools table table-striped table-bordered sortable" width="100%">
                                        <thead>
                                            <tr>
                                                <th width='100px' class="center">Ordem</th>
                                                <th class="tal">Nome</th>
                                                <th width="120px" class="tal">Complementar dados</th>
                                                <th width="120px" class="tal">Vistoria</th>
                                                <th width="120px" class="tal">Termo de filiação</th>
                                                <!-- <th width="120px" class="center">WhatsApp</th> -->
                                                <th width="120px" class="center">Ação</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr ng-repeat='row in ctrl.list' id='{{row.id}}'>
                                                <td class="center">{{$index + 1}}</td>
                                                <td class="tal"><a href="<?= $this->getPath()?>/edit/id/{{row.id}}">{{row.titulo}}</a></td>
                                                <td class="tal">
                                                    <div class="toggle-custom">
                                                        <label class="toggle" data-on="SIM" data-off="NÃO" >
                                                            <input type="checkbox" ng-model='row.dados' ng-change='ctrl.changeDados(row)' ng-true-value="1" ng-false-value="0">
                                                            <span class="button-checkbox"></span>
                                                        </label>
                                                    </div>
                                                </td>                                             
                                                <td class="tal">
                                                    <div class="toggle-custom">
                                                        <label class="toggle" data-on="SIM" data-off="NÃO" >
                                                            <input type="checkbox" ng-model='row.vistoria' ng-change='ctrl.changeVistoria(row)' ng-true-value="1" ng-false-value="0">
                                                            <span class="button-checkbox"></span>
                                                        </label>
                                                    </div>
                                                </td>
                                                <td class="tal">
                                                    <div class="toggle-custom">
                                                        <label class="toggle" data-on="SIM" data-off="NÃO" >
                                                            <input type="checkbox" ng-model='row.contrato' ng-change='ctrl.changeContrato(row)' ng-true-value="1" ng-false-value="0">
                                                            <span class="button-checkbox"></span>
                                                        </label>
                                                    </div>
                                                </td>   
                                                <!-- <td class="tal">
                                                    <div class="toggle-custom">
                                                        <label class="toggle" data-on="SIM" data-off="NÃO" >
                                                            <input type="checkbox" ng-model='row.whastapp' ng-change='ctrl.changeWhats(row)' ng-true-value="1" ng-false-value="0">
                                                            <span class="button-checkbox"></span>
                                                        </label>
                                                    </div>
                                                </td> -->
                                                <td class="center">
                                                    <a href="<?= $this->getPath()?>/edit/id/{{row.id}}"><i class="s12 icomoon-icon-pencil"></i></a>
                                                    <?php if ($this->permissions[$this->permissao_ref]['excluir']): ?>
                                                    <a ng-click='ctrl.deleteItem(row)' class="bt_system_delete cursor" ><i class="s12 icomoon-icon-remove"></i></a>
                                                    <?php endif ?>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="fixed_option_space"></div>

                    <div class="fixed_options_footer">
                        <div class="flex-main">
                            <div class="flex-div vistoria-dado" style='display:none'>
                                <?php if (!$this->permissions($this->permissao_ref,'editar')): ?>
                                <span class="label label-warning"><i class="s24 icomoon-icon-warning"></i>Você não tem permissão para reordenar esta tabela.</span>
                                <?php else: ?>
                                <button style="vertical-align:top" type="button" class="btn btn-info" ng-click='ctrl.saveTable()'>Salvar</button>
                                <?php endif ?>
                            </div>
                        </div>
                        <div class="flex-div sortable_save" style='display:none'>
                            <?php if (!$this->permissions($this->permissao_ref,'editar')): ?>
                            <span class="label label-warning"><i class="s24 icomoon-icon-warning"></i>Você não tem permissão para reordenar esta tabela.</span>
                            <?php else: ?>
                            <button style="vertical-align:top" type="button" class="btn btn-info sortablesubmit">Salvar Ordenação</button>
                            <?php endif ?>
                        </div>
                    </div>
                </div>
            </div>

            <?php require_once $this->main_layouts."footer.phtml"; ?>

        </div>
        
        <?php require_once $this->main_layouts."plugins.phtml"; ?>

        <script src="<?= $this->main_template;?>plugins/tables/dataTables/jquery.dataTables.js"></script>
        <script src="<?= $this->main_template;?>plugins/tables/dataTables/dataTables.tableTools.js"></script>
        <script src="<?= $this->main_template;?>plugins/tables/dataTables/dataTables.bootstrap.js"></script>
        <script src="<?= $this->main_template;?>plugins/tables/dataTables/dataTables.responsive.js"></script>

        <script type="text/javascript">
            $(document).ready(function(){
                if($('table').hasClass('tabletools')){
                    $('.tabletools').dataTable( {
                        "oLanguage": { "sSearch": "", "sLengthMenu": "<span>_MENU_</span>", "sProcessing": "Processando...", "sZeroRecords": "Não foram encontrados resultados", "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros", "sInfoEmpty": "Mostrando de 0 até 0 de 0 registros", "sInfoFiltered": "", "sInfoPostFix": "", "sUrl": "", "oPaginate": { "sFirst": "Primeiro", "sPrevious": "Anterior", "sNext": "Seguinte", "sLast": "Último" } },
                        "sDom": "T<'row'<'col-md-6 col-xs-12 'l><'col-md-6 col-xs-12'f>r>t<'row'<'col-md-4 col-xs-12'i><'col-md-8 col-xs-12'p>>",
                        "aaSorting":[[0,"asc"]],
                        tableTools: { "sSwfPath": "http://cdn.datatables.net/tabletools/2.2.2/swf/copy_csv_xls_pdf.swf", "aButtons": [ ] }
                    });
                }
            });

            angular.module('nova', ['novaServices'])
            .controller('Ctrl',function($scope, $http, $sce, NS, $window) {
                this.list = <?= json_encode($this->list->rows) ?>;

                this.onInit = () => {
                    $('body').show();
                }

                this.changeVistoria = (item) => {
                    this.list.forEach(x => { if(item.id != x.id) x.vistoria = 0; })
                    $(".fixed_options_footer, .vistoria-dado").fadeIn();
                }

                this.changeDados = (item) => {
                    this.list.forEach(x => { if(item.id != x.id) x.dados = 0; })
                    $(".fixed_options_footer, .vistoria-dado").fadeIn();
                }

                this.saveTable = async ()  => {
                    await NS.actionHandler($http.post(`<?= $this->getPath();?>/savetable`,this.list));
                    location.reload();
                }

                this.deleteItem = async (item) => {
                    if(!confirm(`Deletar situação ${item.nome}?`)) return;
                    await NS.actionHandler($http.delete(`<?= $this->getPath();?>/del/id/${item.id}`));
                    location.reload();
                }

                this.changeWhats = async (row) => {
                    await NS.actionHandler($http.post(`<?= $this->getPath();?>/changeWhats`,row));
                    row.whatsapp = !row.whatsapp;
                    $scope.$digest();
                }

                this.changeContrato = async (item) => {
                    this.list.forEach(x => {
                        if(item.id != x.id) x.contrato = 0;
                    })
                    $(".fixed_options_footer, .vistoria-dado").fadeIn();
                }

            })
        </script>
    </body>
</html>
