<?php
    require_once $this->main_layouts . "headers.phtml";
?>
    <script type="text/javascript">
        var pagina = "<?php echo $this->getPath(); ?>";
        var permissao = "<?php echo $this->permissao_ref; ?>";
        var controller = "<?php echo $this->getPath(); ?>";
    </script>
    
    </head>  
    
    
    <body>
<?php  require_once $this->main_layouts . "header.phtml"; ?>

        <!-- / #header -->
        <div id="wrapper">
        <!-- #wrapper -->

<?php  require_once $this->main_layouts . "sidebar.phtml"; ?>
            
            <!--Body content-->
            <div id="content" class="page-content clearfix">
                <div class="contentwrapper">
                    <!--Content wrapper-->
                    <div class="heading">
                        <!--  .heading-->
                        <h3><?php echo $this->module_title; ?></h3>

                        <ul class="breadcrumb">
                            <li>Você está aqui:</li>
                            <li>
                                <a href="#" class="tip" title="Painel">
                                    <i class="s16 icomoon-icon-screen-2"></i>
                                </a>
                                <span class="divider">
                                    <i class="s16 icomoon-icon-arrow-right-3"></i>
                                </span>
                            </li>
                            <li class="active"><?php echo $this->module_title;?></li>
                        </ul>
                    </div>
                    <!-- End  / heading-->
                    <!-- Start .row -->
                    <?php if($this->permissions[$this->permissao_ref]['gravar']) :?>
                    <div class="row">
                        <div class="col-lg-12">
                            <a href="<?php echo $this->getPath();?>/edit"><button type="button" class="btn btn-default mr5 mb10"><i class="glyphicon glyphicon-plus mr5"></i> Novo registro</button></a>
                        </div>
                    </div>
                    <?php endif; ?>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="panel panel-default toggle panelClose">
                                <!-- Start .panel -->
                                <div class="panel-heading">
                                    <h4 class="panel-title"><i class="<?php echo $this->module_icon ?>"></i> Tabela de Clientes
                                        <label class="select-all">Selecionar estes <input type="checkbox" id="apagar_todos"></label>
                                    </h4>
                                </div>
                                <div class="panel-body">
                                    <div class="row">
                                        <div class="col-lg-1">
                                            <form method="POST">
                                                <label for="">Mês/Ano</label>
                                                <select name="date" class="select2 form-control">
                                                    <?php foreach ($this->months->rows as $item): ?>
                                                        <?php if($item['month'] == $this->month && $item['year'] === $this->year): ?>
                                                            <option value="<?php echo $item['label'] ?>" selected><?php echo $item['label'] ?></option>
                                                        <?php else: ?>
                                                            <option value="<?php echo $item['label'] ?>"><?php echo $item['label'] ?></option>
                                                        <?php endif ?>
                                                    <?php endforeach ?>
                                                </select>
                                            </form>
                                        </div>
                                    </div>
                                    <table cellpadding="0" cellspacing="0" border="0" class="tabletools table table-striped table-bordered" width="100%">
                                        <thead>
                                            <tr>
                                                <th style="display:none;"></th>
                                                <th width="10%" class="tal">Venc.</th>
                                                <th width="10%" class="tal">Status</th>
                                                <th width="30%" class="tal">Cliente</th>
                                                <th width="30%" class="tal">Descrição</th>
                                                <th width="10%" class="tal">Valor</th>
                                                <th width="5%" class="tal">Tipo</th>
                                                <th style="min-width: 120px" class="center">Ação</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php if ($this->list->num_rows) : ?>
                                                <?php foreach($this->list->rows as $registro):?>
                                                    <tr>
                                                        <td style="display:none;"><?php echo $registro['data_vencimento'] ?></td>
                                                        <td class="tal"><a href="<?php echo $this->getPath()?>/edit/id/<?php echo $registro['id']; ?>"><?php echo date('d/m/Y', strtotime($registro['data_vencimento'])) ?></a></td>
                                                        <td class="tal">
                                                            <a href="<?php echo $this->getPath()?>/edit/id/<?php echo $registro['id']; ?>">
                                                                <?php echo $registro['data_pagamento'] ? 'Faturado' : 'Em aberto' ?>
                                                            </a>
                                                        </td>
                                                        <td class="tal"><a href="<?php echo $this->getPath()?>/edit/id/<?php echo $registro['id']; ?>"><?php echo $registro['cliente'] ?></a></td>
                                                        <td class="tal"><a href="<?php echo $this->getPath()?>/edit/id/<?php echo $registro['id']; ?>"><?php echo $registro['descricao'] ?></a></td>
                                                        <td class="tal"><a href="<?php echo $this->getPath()?>/edit/id/<?php echo $registro['id']; ?>"><?php echo number_format($registro['valor'], 2, ',', '.') ?></a></td>
                                                        <td class="center">
                                                            <a href="<?php echo $this->getPath()?>/edit/id/<?php echo $registro['id']; ?>">
                                                                <span style="color:<?php echo $registro['tipo'] == 'R' ? 'green' : 'red' ?>;"><?php echo $registro['tipo'] ?></span>
                                                            </a>
                                                        </td>
                                                        <td class="center">
                                                            <a href="<?php echo $this->getPath()?>/edit/id/<?php echo $registro['id']; ?>"><i class="s12 icomoon-icon-pencil"></i></a>
                                                            <?php if ($this->permissions[$this->permissao_ref]['excluir']): ?>
                                                                <a class="bt_system_delete" data-controller="<?php echo $this->getPath()?>" data-id="<?php echo $registro['id']; ?>" href="#"><i class="s12 icomoon-icon-remove"></i></a>
                                                                <input type="checkbox" id="del_<?php echo $registro['id']; ?>" value="<?php echo $registro['id']; ?>" class="del-this">
                                                            <?php endif ?>
                                                        </td>
                                                    </tr>
                                                <?php endforeach; ?>
                                            <?php endif; ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div><!-- End .row -->
                    <?php require_once $this->main_layouts . "options.phtml"; ?>
                </div>
                <!-- End contentwrapper -->
            </div>
            <!-- End #content -->
            
            
<?php  require_once $this->main_layouts . "footer.phtml"; ?>
        
        </div>
        
<?php  require_once $this->main_layouts . "plugins.phtml"; ?>

        <!-- Table plugins -->
        <script src="<?php echo $this->main_template;?>plugins/tables/dataTables/jquery.dataTables.js"></script>
        <script src="<?php echo $this->main_template;?>plugins/tables/dataTables/dataTables.tableTools.js"></script>
        <script src="<?php echo $this->main_template;?>plugins/tables/dataTables/dataTables.bootstrap.js"></script>
        <script src="<?php echo $this->main_template;?>plugins/tables/dataTables/dataTables.responsive.js"></script>
        <script src="<?php echo $this->main_template; ?>plugins/forms/select2/select2.js"></script>

        <!-- Init plugins only for page -->
        <script type="text/javascript">
            $(document).ready(function(){
                $('.select2').select2();

                $('body').on('click', '.bt_client_stats', function (e) {
                    var $this = $(this);
                    var db = ($this.data("db")) ? $this.data("db") : "";
                    $.post("main/client/status", { "t": $(this).attr('data-table'), "a": $(this).attr("data-action"), "i": $(this).attr("data-id"), "p": $(this).attr("data-permit"), "db": db }, function (data) {
                        if (data == "ativar") {
                            $this.html('<img src="' + main_template + 'images/status_vermelho.png" alt="Ativar">');
                            $this.attr("data-action", "ativar");
                        } else if (data == "desativar") {
                            $this.html('<img src="' + main_template + 'images/status_verde.png" alt="Ativar">');
                            $this.attr("data-action", "desativar");
                        } else {
                            alert(data);
                        }
                    });
                });

                //--------------- Data tables ------------------//
                if($('table').hasClass('tabletools')){
                    $('.tabletools').dataTable( {
                        "oLanguage": {
                            "sSearch": "",
                            "sLengthMenu": "<span>_MENU_</span>",
                            "sProcessing":   "Processando...",                    
                            "sZeroRecords":  "Não foram encontrados resultados",
                            "sInfo":         "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                            "sInfoEmpty":    "Mostrando de 0 até 0 de 0 registros",
                            "sInfoFiltered": "",
                            "sInfoPostFix":  "",
                            "sUrl":         "",

                            "oPaginate": {
                                "sFirst":    "Primeiro",
                                "sPrevious": "Anterior",
                                "sNext":     "Seguinte",
                                "sLast":     "Último"
                            }
                        },
                        "sDom": "T<'row'<'col-md-6 col-xs-12 'l><'col-md-6 col-xs-12'f>r>t<'row'<'col-md-4 col-xs-12'i><'col-md-8 col-xs-12'p>>",
                        "aaSorting":[[0,"asc"]],
                        tableTools: {
                            "sSwfPath": "http://cdn.datatables.net/tabletools/2.2.2/swf/copy_csv_xls_pdf.swf",
                            "aButtons": [
                          ]
                        }


                    });

                }

                $('select[name=date]').change(function () {
                    $(this).parent().trigger('submit');
                });

            });
        </script>
    </body>
</html>
