<?php
 $data = $this->DB_fetch_array("SELECT * FROM hbrd_adm_company where id = 1", 'string')->rows[0]['logo'];
 $base64 = $data;
?>
<html>
<head>
	<style>
		table {
			border-collapse: collapse;
			width: 100%;
		}
		td, th {
			border: 1px solid #dddddd;
			text-align: center;
			padding: 3px;
		}
		tr:nth-child(even) {
			background-color: #dddddd;
		}
		table *{
			vertical-align: middle;
		}
		.footer-table td {
			font-weight: bold;
		}
		.main div img {
			float: left;
		}
		.blue th, .blue td {
			background : #0f243f;
			color: white;
			height: 30px;
		}
		.main div {
			padding : 20px;
		}
		.linhas td {
			height: 20px;
		}
		.logo{
			margin-right: 10px;
		}
	</style>
</head>
<body>
	<div class='main'>
		<div>
			<img class="logo" src="<?= $base64; ?>" alt="Página Inicial" />
			<h2>Relatório consultores por equipe <?= " de ".$_GET['datade']; ?><?= " até ".$_GET['dataate']; ?></h2>
			<i>Emitido em <b><?= date("d/m/Y H:i:s"); ?></b> por <b><?= $_SESSION["admin_nome"]; ?></b>.</i>
		</div>
		<table>
			<tr class='blue'>
				<th style='width: 40%;'>Equipe</th>
				<th style='width: 20%;'>Meta</th>
				<th style='width: 20%;'>Novos consultores</th>
				<th style='width: 20%;'>Diferença</th>
			</tr>
			<?php
				$meta = 0;
				$ativadas = 0;
				$diferenca = 0;
				foreach ($this->dados as $item) {
					$meta = $meta + (int)$item['meta'];
					$ativadas = $ativadas + (int)$item['ativadas'];
					$diferenca = $diferenca + (int)$item['diferenca'];
					?>
					<tr class='linhas'>
						<td><?= ($item["equipe"]); ?></td>
						<td ><?= ($item["meta"]); ?></td>
						<td ><?= $item["ativadas"]; ?></td>
						<td ><?= $item['diferenca']; ?></td>
					</tr>
					<?php
				}
			?>
			<tr class='footer-table blue'>
				<td></td>
				<td ><?= $meta; ?></td>
				<td ><?= $ativadas; ?></td>
				<td ><?= $diferenca; ?></td>
			</tr>
		</table>
	</div>
	<br>
	<br>
	<i>Gerenciado por <b><?= $this->root_path ?></b></i>
</body>
</html>