<?php
use function GuzzleHttp\json_encode;
require_once $this->main_layouts."headers.phtml"; ?>
<link href="<?= $this->main_template; ?>plugins/tables/dataTables/jquery.dataTables.css" type="text/css" rel="stylesheet" />
<link href="<?= $this->main_template; ?>plugins/tables/dataTables/TableTools.css" type="text/css" rel="stylesheet" />
<script type="text/javascript">
    var pagina = "<?= $this->getPath(); ?>";
    var permissao = "<?= $this->permissao_ref; ?>";
    var controller = "<?= $this->getPath(); ?>";
</script>
</head>  
<body ng-app='nova' ng-controller="IndexCtrl as ctrl" style='display:none' ng-init='ctrl.onInit()'>
    <?php require_once $this->main_layouts."header.phtml"; ?>
    <div id="wrapper">
        <?php require_once $this->main_layouts."sidebar.phtml"; ?>
        <div id="content" class="page-content clearfix">
            <div class="contentwrapper">
                <div class="heading">
                    <h3><?= $this->module_title; ?></h3>
                    <ul class="breadcrumb">
                        <li>Você está aqui:</li>
                        <li> <a href="#" class="tip" title="Painel"> <i class="s16 icomoon-icon-screen-2"></i> </a> <span class="divider"> <i class="s16 icomoon-icon-arrow-right-3"></i> </span> </li>
                        <li class="active"><?= $this->module_title;?></li>
                    </ul>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="panel panel-default toggle">
                            <div class="panel-heading">
                                <h4 class="panel-title"><i class="<?= $this->module_icon ?>"></i> Whatsapp Consultor
                                </h4>
                            </div>
                            <div class="panel-body">
                                <table cellpadding="0" cellspacing="0" border="0" class="tabletools table table-striped table-bordered" width="100%">
                                    <thead>
                                        <tr>                                              
                                            <th width='30%' class="tal">Descrição</th>
                                            <th class="tal">Contexto</th>
                                            <th width='5%' class="tal">Status</th>
                                            <th style="display:none"></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach($this->notificacoes->rows as $row) : ?>
                                        <?php if($row['local'] != 'Consultor') continue; ?>
                                        <tr>
                                            <td class="tal"><a href="<?= $this->getPath()?>/edit/id/<?= $row['id'] ?>"><?= $row['descricao'] ?></a></td>
                                            <td class="tal"><a href="<?= $this->getPath()?>/edit/id/<?= $row['id'] ?>"><?= $row['contexto'] ?></a></td>
                                            <td style="display:none"><a><?= $row['desativado'] ?></a></td>
                                            <td class="center">
                                                <?php if(!(bool)$row['desativado']) : ?>
                                                <a class='cursor' ng-click='ctrl.chgStatus(<?= $row['id'] ?>)' title="Desativar"><img src="<?= $this->main_template;?>images/status_verde.png" ></a>
                                                <?php else : ?>
                                                <a class='cursor' ng-click='ctrl.chgStatus(<?= $row['id'] ?>)' title="Ativar"><img src="<?= $this->main_template;?>images/status_vermelho.png"></a>
                                                <?php endif ?>
                                            </td>
                                        </tr>
                                        <?php endforeach ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="panel panel-default toggle">
                            <div class="panel-heading">
                                <h4 class="panel-title"><i class="<?= $this->module_icon ?>"></i> Whatsapp Associado
                                </h4>
                            </div>
                            <div class="panel-body">
                                <table cellpadding="0" cellspacing="0" border="0" class="tabletools table table-striped table-bordered" width="100%">
                                    <thead>
                                        <tr>                                              
                                            <th width='30%' class="tal">Descrição</th>
                                            <th class="tal">Contexto</th>
                                            <th width='5%' class="tal">Status</th>
                                            <th style="display:none"></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach($this->notificacoes->rows as $row) : ?>
                                        <?php if($row['local'] != 'Associado') continue; ?>
                                        <tr>
                                            <td class="tal"><a href="<?= $this->getPath()?>/edit/id/<?= $row['id'] ?>"><?= $row['descricao'] ?></a></td>
                                            <td class="tal"><a href="<?= $this->getPath()?>/edit/id/<?= $row['id'] ?>"><?= $row['contexto'] ?></a></td>
                                            <td style="display:none"><a><?= $row['desativado'] ?></a></td>
                                            <td class="center">
                                                <?php if(!(bool)$row['desativado']) : ?>
                                                <a class='cursor' ng-click='ctrl.chgStatus(<?= $row['id'] ?>)' title="Desativar"><img src="<?= $this->main_template;?>images/status_verde.png" ></a>
                                                <?php else : ?>
                                                <a class='cursor' ng-click='ctrl.chgStatus(<?= $row['id'] ?>)' title="Ativar"><img src="<?= $this->main_template;?>images/status_vermelho.png"></a>
                                                <?php endif ?>
                                            </td>
                                        </tr>
                                        <?php endforeach ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="panel panel-default toggle">
                            <div class="panel-heading">
                                <h4 class="panel-title"><i class="<?= $this->module_icon ?>"></i> Whatsapp Clinica
                                </h4>
                            </div>
                            <div class="panel-body">
                                <table cellpadding="0" cellspacing="0" border="0" class="tabletools table table-striped table-bordered" width="100%">
                                    <thead>
                                        <tr>                                              
                                            <th width='30%' class="tal">Descrição</th>
                                            <th class="tal">Contexto</th>
                                            <th width='5%' class="tal">Status</th>
                                            <th style="display:none"></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach($this->notificacoes->rows as $row) : ?>
                                        <?php if($row['local'] != 'Clinica') continue; ?>
                                        <tr>
                                            <td class="tal"><a href="<?= $this->getPath()?>/edit/id/<?= $row['id'] ?>"><?= $row['descricao'] ?></a></td>
                                            <td class="tal"><a href="<?= $this->getPath()?>/edit/id/<?= $row['id'] ?>"><?= $row['contexto'] ?></a></td>
                                            <td style="display:none"><a><?= $row['desativado'] ?></a></td>
                                            <td class="center">
                                                <?php if(!(bool)$row['desativado']) : ?>
                                                <a class='cursor' ng-click='ctrl.chgStatus(<?= $row['id'] ?>)' title="Desativar"><img src="<?= $this->main_template;?>images/status_verde.png" ></a>
                                                <?php else : ?>
                                                <a class='cursor' ng-click='ctrl.chgStatus(<?= $row['id'] ?>)' title="Ativar"><img src="<?= $this->main_template;?>images/status_vermelho.png"></a>
                                                <?php endif ?>
                                            </td>
                                        </tr>
                                        <?php endforeach ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php require_once $this->main_layouts."footer.phtml"; ?>
    </div>
    <?php require_once $this->main_layouts."plugins.phtml"; ?>
    <script src="<?= $this->main_template; ?>plugins/tables/dataTables/jquery.dataTables.js"></script>
    <script src="<?= $this->main_template; ?>plugins/tables/dataTables/dataTables.tableTools.js"></script>
    <script src="<?= $this->main_template; ?>plugins/tables/dataTables/dataTables.bootstrap.js"></script>
    <script src="<?= $this->main_template; ?>plugins/tables/dataTables/dataTables.responsive.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            if($('table').hasClass('tabletools')){
                $('.tabletools').dataTable({
                    "oLanguage": {
                        "sSearch": "",
                        "sLengthMenu": "<span>_MENU_</span>",
                        "sProcessing":   "Processando...",                    
                        "sZeroRecords":  "Não foram encontrados resultados",
                        "sInfo":         "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                        "sInfoEmpty":    "Mostrando de 0 até 0 de 0 registros",
                        "sInfoFiltered": "",
                        "sInfoPostFix":  "",
                        "sUrl":         "",
                        "oPaginate": {
                            "sFirst":    "Primeiro",
                            "sPrevious": "Anterior",
                            "sNext":     "Seguinte",
                            "sLast":     "Último"
                        }
                    },
                    "sDom": "T<'row'<'col-md-6 col-xs-12 'l><'col-md-6 col-xs-12'f>r>t<'row'<'col-md-4 col-xs-12'i><'col-md-8 col-xs-12'p>>",
                    "aaSorting":[[0,"asc"]],
                    tableTools: {
                        "sSwfPath": "http://cdn.datatables.net/tabletools/2.2.2/swf/copy_csv_xls_pdf.swf",
                        "aButtons": []
                    }
                });
            }
        });
        angular.module('nova', ['novaServices'])
        .controller('IndexCtrl',function($scope, $http, $sce, NS, $window) {
            this.onInit = () => {
                $('body').show();
            }
            this.chgStatus = async (id) => {
                await NS.actionHandler($http.post("<?= $this->system_path.$this->getPath();?>/changestatus", { id: id }));
                location.reload();
            }
        });
    </script>
</body>
</html>
