<?php require_once $this->main_layouts . "headers.phtml";?>

    <script type="text/javascript">
        var pagina = "<?php echo $this->getPath(); ?>";
        var permissao = "<?php echo $this->permissao_ref; ?>";
        var controller = "<?php echo $this->getPath(); ?>/save";
        var retorno = "<?php echo $this->retorno; ?>";
    </script>
    </head>  

    <body ng-app='nova' ng-controller="EditCtrl as ctrl" ng-init='ctrl.onInit()' style='display:none'>
        <?php require_once $this->main_layouts."header.phtml"; ?>
        <div id="wrapper">
            <?php require_once $this->main_layouts."sidebar.phtml"; ?>
            <div id="content" class="page-content clearfix">
                <div class="contentwrapper">
                    <div class="heading">
                        <h3><?= $this->module_title ?></h3>
                        <ul class="breadcrumb">
                            <li>Você está aqui:</li>
                            <li><a href="#" class="tip" title="Painel"><i class="s16 icomoon-icon-screen-2"></i></a><span class="divider"><i class="s16 icomoon-icon-arrow-right-3"></i></span></li>
                            <li><a class="tip" title="<?php echo $this->module_title; ?>" href="<?php echo $this->module_link;?>"><i class="s16 <?php echo $this->module_icon; ?>"></i></a></li>
                            <span class="divider"><i class="s16 icomoon-icon-arrow-right-3"></i></span>
                            <li class="active">Registro</li>
                        </ul>
                    </div>

                    <form class="form-horizontal group-border" ng-submit='ctrl.submitForm()'>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="panel panel-default toggle">
                                <div class="panel-heading">
                                    <h4 class="panel-title">Mensagem</h4>
                                </div>
                                <div class="panel-body">
                                    <div class='col-md-12'>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="descricao">Para</label>
                                            <div class="col-lg-10">
                                                <input disabled class="form-control" value='{{ctrl.data.local}}'/>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="descricao">Descrição</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" ng-model='ctrl.data.descricao'/>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="contexto">Contexto</label>
                                            <div class="col-lg-10">
                                                <textarea class="form-control elastic" ng-model='ctrl.data.contexto'></textarea>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="relato">Mensagem
                                            <br><small><a href="#" class="btn btn-xs btn-default pull-right" data-toggle="modal" data-target="#modalvariaveis">Palavras-chaves</a></small>
                                            </label>
                                            <div class="col-lg-10">
                                                <textarea class="form-control elastic" rows='3' ng-model='ctrl.data.mensagem'></textarea>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <?php if($this->registro['local'] == 'Associado') : ?>
                                <div class="panel panel-default toggle">
                                    <div class="panel-heading">
                                        <h4 class="panel-title">Email</h4>
                                    </div>
                                    <div class="panel-body">
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label">
                                                Enviar Email 
                                                <i class="fa fa-question-circle cursor" data-container="body" data-toggle="popover" data-placement="top" data-content="Ativar ou desativar envio de e-mail" title="" data-original-title="Funcionamento" ></i>
                                            </label>
                                            <div class="col-lg-10 col-md-9">
                                                <div class="toggle-custom">
                                                    <label class="toggle" data-on="ON" data-off="OFF">
                                                        <input type="checkbox" ng-model='ctrl.data.envia_email' ng-true-value="1" ng-false-value="0">
                                                        <span class="button-checkbox"></span>
                                                    </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="template">Template
                                                <br><small><a href="#" class="btn btn-xs btn-default pull-right" data-toggle="modal" data-target="#modalvariaveis">Palavras-chaves</a></small>
                                            </label>
                                            <div class="col-lg-10">
                                                <textarea class="form-control" rows="30" name="template_email" id="template_email" tinymce><?= $this->registro['template_email'] ?></textarea>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="assunto">Assunto</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" ng-model='ctrl.data.assunto'/>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php endif ?>

                        </div>
                    </div>
                    
                    <div class='col-md-12'>
                        <?php if (!$this->permissions[$this->permissao_ref]['editar']): ?>
                        <div class="form-group" >
                            <div class="col-lg-offset-2 col-lg-10">
                                <span class="label label-warning"><span class="icon24 icomoon-icon-warning "></span>Você não tem permissão para editar esta função.</span>
                            </div>
                        </div>
                        <?php else: ?>
                        <div class="form-group" style='padding-top: 0px;'>
                            <div class="col-lg-offset-2 col-lg-10">
                                <button type="submit" class="btn btn-info">Salvar alterações</button>
                            </div>
                        </div>
                        <?php endif ?>
                    </div>
                    </form>
                </div>
            </div>
            <?php require_once $this->main_layouts . "footer.phtml"; ?>
        </div>

        <div id="modalvariaveis" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title">Palavras-chaves</h4>
                    </div>
                    <div class="modal-body">
                        <ul class="list-group">
                            <?php foreach($this->items as $item) : ?>
                            <li ng-click='ctrl.copy("<?= $item['variavel'] ?>")' class="cursor list-group-item"><strong><?= $item['variavel'] ?></strong> - <?= $item['descricao'] ?></li>
                            <?php endforeach ?>
                        </ul>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                    </div>
                </div>
            </div>
        </div>

        <?php require_once $this->main_layouts . "plugins.phtml"; ?>
        <script src="<?php echo $this->main_template;?>plugins/forms/autosize/jquery.autosize.js"></script>
        <script src="<?php echo $this->main_template;?>plugins/forms/tiny_mce/tinymce.min.js"></script>
        <style>
            
        </style>
        <script type="text/javascript">
            $(document).ready(function(){
                tinymceInit2({ css: 'tinymce-a4.css' }); 
                $('.elastic').autosize();
            });

            angular.module('nova', ['novaServices'])
            .controller('EditCtrl',function($scope, $http, $sce, NS) {
               this.data = <?php echo json_encode($this->registro) ?>;

               this.submitForm = async () => {
                    tinymce.triggerSave();
                    this.data.template_email = $("#template_email").val();
                    let res = await NS.actionHandler($http.post("<?php echo $this->getPath(); ?>/leadszappSave", this.data));
                    window.location.href = retorno;
               }
               this.copy = async (toCopy) => {
                   debugger
                    await navigator.clipboard.writeText(toCopy);
                    NS.notifSucess('Variável copiada');
                    $('#modalvariaveis').modal('toggle')
               }
               this.onInit = () => {
                   $('body').show();
               }
            })
        </script>
    </body>
</html>