<form name="edita_imagem" enctype="multipart/form-data" method="post" class="form-horizontal group-border">
    <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default toggle panelClose">
                <!-- Start .panel -->
                <div class="panel-heading">
                    <h4 class="panel-title"><i class="iconic-icon-brush"></i>Editar Imagem</h4>
                </div>

                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <div class="col-lg-12">
                                    <div class="center"><img src="<?php echo $this->foto['url'] ?>" alt="<?php echo $this->foto['legenda'] ?>" class="maxwmaxh pad-radius-img"></div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-lg-2 control-label" for="legenda">Legenda:</label>
                                <div class="col-lg-10">
                                    <input class="form-control" name="legenda" id="legenda" maxlength="60" type="text" value="<?php echo $this->foto['legenda'] ?>" />
                                </div>
                            </div><!-- End .form-group  -->
                        </div><!-- End .span12 -->
                    </div><!-- End .row -->
                    <div class="row">
                        <div class="col-lg-12">
                            <?php if ($this->id == ""): ?>
                                <?php if (!$this->permissions[$this->permissao_ref]['gravar']): ?>
                                    <div class="form-group">
                                        <div class="col-lg-12">
                                            <div class="center"><span class="label label-warning "><span class="s24 typ-icon-warning"></span>Você não tem permissão para gravar esta função.</span></div>
                                        </div>
                                    </div><!-- End .form-group  -->   
                                <?php else: ?>
                                    <div class="form-group">
                                        <div class="col-lg-12">
                                            <div class="center"><button type="button" class="btn btn-info clickformsubmit">Gravar</button></div>
                                        </div>
                                    </div><!-- End .form-group  -->
                                <?php endif ?>
                            <?php else: ?>
                                <?php if (!$this->permissions[$this->permissao_ref]['editar']): ?>
                                    <div class="form-group">
                                        <div class="col-lg-12">
                                            <div class="center"><span class="label label-warning"><span class="s24 icomoon-icon-warning "></span>Você não tem permissão para editar esta função.</span></div>
                                        </div>
                                    </div><!-- End .form-group  -->   
                                <?php else: ?>
                                    <div class="form-group">
                                        <div class="col-lg-12">
                                            <div class="center"><button type="button" class="btn btn-info clickformsubmit">Salvar alterações</button></div>
                                        </div>
                                    </div><!-- End .form-group  -->
                                <?php endif ?>
                            <?php endif ?>
                        </div><!-- End .span12 -->
                    </div><!-- End .row -->  
                </div>
            </div>
        </div>
    </div>
</form>

<script type="text/javascript">

    $("form[name=edita_imagem]").clickform({"validateUrl": "<?php echo $this->getPath();?>/editPhoto"}, function (data) {
        if (data.type == "success") {
            $("#edita_imagem").slideUp(function () {
                $(this).empty();
            });
        }
    });

</script>
