<?php require_once $this->main_layouts . "headers.phtml"; ?>
    <script type="text/javascript">
        var pagina = "<?= $this->getPath(); ?>";
        var permissao = "<?= $this->permissao_ref; ?>";
        var controller = "<?= $this->getPath(); ?>/save";
        var retorno = "<?= $this->retorno; ?>";
    </script>
    </head>  
    <body ng-app='nova' ng-controller="EditCtrl as ctrl" ng-init='ctrl.onInit()' style='display:none;'>
        <?php require_once $this->main_layouts . "header.phtml"; ?>
        <div id="wrapper">
        <?php require_once $this->main_layouts . "sidebar.phtml"; ?>
            <div id="content" class="page-content clearfix">
                <div class="contentwrapper">
                    <div class="heading">
                        <h3><?= $this->module_title; ?></h3>
                        <ul class="breadcrumb">
                            <li>Você está aqui:</li>
                            <li> <a href="#" class="tip" title="Painel"> <i class="s16 icomoon-icon-screen-2"></i> </a> <span class="divider"> <i class="s16 icomoon-icon-arrow-right-3"></i> </span> </li>
                            <li> <a class="tip" title="<?= $this->module_title; ?>" href="<?= $this->module_link;?>"> <i class="s16 <?= $this->module_icon; ?>"></i> </a> </li>
                            <span class="divider">
                                <i class="s16 icomoon-icon-arrow-right-3"></i>
                            </span>
                            <li class="active">Registro</li>
                        </ul>
                    </div>
                    <form ng-submit='ctrl.submit()' class="form-horizontal group-border">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default toggle">
                                    <div class="panel-heading">
                                        <h4 class="panel-title">Dados da Regional</h4>
                                    </div>
                                    <div class="panel-body">
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="nome">Nome:</label>
                                            <div class="col-lg-10">
                                                <input required class="form-control" ng-model='ctrl.data.titulo' />
                                            </div>
                                        </div>                                 
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?php if($this->registro['id']) : ?>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default toggle">
                                    <div class="panel-heading">
                                        <h4 class="panel-title">Gestores</h4>
                                    </div>
                                    <div class="panel-body">
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="">Consultores:</label>
                                            <div class="col-lg-10">
                                                <div class="leftBox" style="margin:0;">
                                                    <div class="searchBox">
                                                        <input type="text" id="box1Filter" class="searchField form-control" style="margin:0;" placeholder="filtrar ..."/>
                                                        <button id="box1Clear" type="button" class="btn">
                                                            <span class="s14  entypo-icon-close "></span>
                                                        </button>
                                                    </div>
                                                    <select id="box1View" multiple="multiple" class="multiple nostyle form-control" style="height:300px;">
                                                        <?php foreach ($this->consultores as $row): ?>
                                                        <?php if((bool)$row['gestor']) continue ?>
                                                        <option value="<?= $row['id'] ?>"><?= $row['nome'] ?></option>
                                                        <?php endforeach ?>
                                                    </select>
                                                    <br>
                                                    <span>Consultores que <span class="label-warning" style="padding:0 2px;">não são gestores</span> desta regional </span>
                                                    <br>
                                                    <span id="box1Counter" class="count"></span>
                                                    <div class="dn"><select id="box1Storage" name="box1Storage" class="nostyle"></select></div>
                                                </div>
                                                <div class="dualBtn">
                                                    <button id="to2" type="button" class="btn" ><span class="icon12 minia-icon-arrow-right-3"></span></button>
                                                    <button id="allTo2" type="button" class="btn" ><span class="icon12 iconic-icon-last"></span></button>
                                                    <button id="to1" type="button" class="btn marginT5"><span class="icon12 minia-icon-arrow-left-3"></span></button>
                                                    <button id="allTo1" type="button" class="btn marginT5" ><span class="icon12 iconic-icon-first"></span></button>
                                                </div>
                                                <div class="rightBox" style="margin:0;">
                                                    <div class="searchBox">
                                                        <input type="text" id="box2Filter" class="searchField form-control" style="margin:0;" placeholder="filtrar ..." />
                                                        <button id="box2Clear"  type="button" class="btn" >
                                                            <span class="s14  entypo-icon-close "></span>
                                                        </button>
                                                    </div>
                                                    <select id="box2View" multiple="multiple" name="cartoes[]" class="multiple nostyle form-control" style="height:300px;">
                                                        <?php foreach ($this->consultores as $row): ?>
                                                        <?php if(!(bool)$row['gestor']) continue ?>
                                                        <option value="<?= $row['id'] ?>"><?= $row['nome'] ?></option>
                                                        <?php endforeach ?>
                                                    </select>
                                                    <br>
                                                    <span>Consultores que <span class="label-success white" style="padding:0 2px;">são gestores</span> desta regional</span>
                                                    <br>
                                                    <span id="box2Counter" class="count"></span>
                                                    <div class="dn"><select id="box2Storage" class="nostyle"></select></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?php endif ?>
                        <div class="row">
                            <?php if ($this->id==""): ?>
                                <?php if (!$this->permissions[$this->permissao_ref]['gravar']): ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <span class="label label-warning "><span class="icon24 typ-icon-warning"></span>Você não tem permissão para gravar esta função.</span>
                                        </div>
                                    </div>   
                                <?php else: ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <button type="submit" class="btn btn-info">Salvar novo</button>
                                        </div>
                                    </div>
                                <?php endif ?>
                            <?php else: ?>
                                <?php if (!$this->permissions[$this->permissao_ref]['editar']): ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <span class="label label-warning"><span class="icon24 icomoon-icon-warning "></span>Você não tem permissão para editar esta função.</span>
                                        </div>
                                    </div>   
                                <?php else: ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <button type="submit" class="btn btn-info">Salvar alterações</button>
                                        </div>
                                    </div>
                                <?php endif ?>
                            <?php endif ?>
                        </div>
                    </form>
                </div>
            </div>
            <?php require_once $this->main_layouts . "footer.phtml"; ?>
        </div>
        <?php require_once $this->main_layouts . "plugins.phtml"; ?>
        <script src="<?= $this->main_template;?>plugins/forms/autosize/jquery.autosize.js"></script>
        <script type="text/javascript" src="<?= $this->main_template;?>plugins/forms/dualselect/jquery.dualListBox-1.3.min.js"></script>
        <script type="text/javascript">
            $(document).ready(function(){
                $.configureBoxes();
            });
            angular.module('nova', ['novaServices'])
            .controller('EditCtrl', function($scope, $http, $sce, NS, $window) {
                this.data = <?= json_encode($this->registro); ?>;
                this.onInit = () => {
                    $('body').show();
                }
                this.submit = async () => {
                    const data = Object.assign({gestores : []}, this.data);
                    $("#box2View option").each(function(){data.gestores.push($(this).val())});
                    let res = await NS.actionHandler($http.post("<?= $this->getPath(); ?>/save", data));
                    location.href = `${retorno}/edit/id/${res.data}`;
                }
            });
        </script>
    </body>
</html>
