<?php require_once $this->main_layouts."headers.phtml"; ?>
<script type="text/javascript">
    var pagina = "<?= $this->getPath(); ?>";
    var permissao = "<?= $this->permissao_ref; ?>";
    var controller = "<?= $this->getPath(); ?>";
</script>
</head>
<body ng-app='nova' ng-controller="IndexCtrl as ctrl" style='display:none' ng-init='ctrl.onInit()'>
    <?php require_once $this->main_layouts."header.phtml"; ?>
    <div id="wrapper">
        <?php require_once $this->main_layouts."sidebar.phtml"; ?>
        <div id="content" class="page-content clearfix">
            <div class="contentwrapper">
                <div class="heading">
                    <h3><?= $this->module_title; ?></h3>
                    <ul class="breadcrumb">
                        <li>Você está aqui:</li>
                        <li> <a href="#" class="tip" title="Painel"> <i class="s16 icomoon-icon-screen-2"></i> </a> <span class="divider"> <i class="s16 icomoon-icon-arrow-right-3"></i> </span> </li>
                        <li class="active"><?= $this->module_title; ?></li>
                    </ul>
                </div>
                <div class="row">
                    <div class="col-lg-6">
                        <?php if ($this->permissions($this->permissao_ref,'gravar')): ?>
                        <a href="<?= $this->getPath();?>/edit"><button type="button" class="btn btn-default mr5 mb10"><i class="glyphicon glyphicon-plus mr5"></i> Novo registro</button></a>
                        <?php endif ?>
                    </div>
                    <div class="col-lg-6">
                        <?php if ($this->custompermissions($this->permissao_ref,'relatorio')): ?>
                        <div class="text-right" >
                            <button class="btn btn-info mr5 mb10" ng-click="ctrl.modalRelatorio(true)"><span class="s14 icomoon-icon-file-pdf color-white" ></span>Ativações com equipes</button>
                            <button class="btn btn-info mr5 mb10" ng-click="ctrl.modalRelatorio()"><span class="s14 icomoon-icon-file-pdf color-white" ></span>Ativações</button>
                        </div>
                        <?php endif ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="panel panel-default toggle ">
                            <div class="panel-heading">
                                <h4 class="panel-title"><i class="<?= $this->module_icon ?>"></i> Tabela de Regionais</h4>
                            </div>
                            <div class="panel-body">
                                <table cellpadding="0" cellspacing="0" border="0" class="tabletools table table-striped table-bordered " width="100%">
                                    <thead>
                                        <tr>
                                            <th class="tal">Nome</th>
                                            <th class="tal">Equipes</th>
                                            <th class="tal">Gestores</th>
                                            <th class="tal">Ind. Pendentes</th>
                                            <th class="tal">Ind. Arquivadas</th>
                                            <th class="tal">Ind. Ativas</th>
                                            <th class="tal">Ind. Totais</th>
                                            <th class="tal">Conversão (%)</th>
                                            <th width="120px" class="center">Ação</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr ng-repeat='row in ctrl.list'>
                                            <td class="tal"><a href="<?= $this->getPath() ?>/edit/id/{{row.id}}">{{row.titulo}}</a></td>
                                            <td class="tal"><a href="<?= $this->getPath() ?>/edit/id/{{row.id}}">{{row.equipes}}</a></td>
                                            <td class="tal"><a href="<?= $this->getPath() ?>/edit/id/{{row.id}}">{{row.gestores}}</a></td>
                                            <td class="tal"><a href="<?= $this->getPath() ?>/edit/id/{{row.id}}">{{row.pendentes}}</a></td>
                                            <td class="tal"><a href="<?= $this->getPath() ?>/edit/id/{{row.id}}">{{row.arquivadas}}</a></td>
                                            <td class="tal"><a href="<?= $this->getPath() ?>/edit/id/{{row.id}}">{{row.ativadas}}</a></td>
                                            <td class="tal"><a href="<?= $this->getPath() ?>/edit/id/{{row.id}}">{{row.total}}</a></td>
                                            <td class="tal"><a href="<?= $this->getPath() ?>/edit/id/{{row.id}}">{{row.converted}}</a></td>
                                            <td class="center">
                                                <a class='cursor' ng-if='row.stats == "0"' ng-click='ctrl.stats(row)' title="Ativar"><img src="<?= $this->main_template; ?>images/status_vermelho.png"></a>
                                                <a class='cursor' ng-if='row.stats == "1"' ng-click='ctrl.stats(row)' title="Desativar"><img src="<?= $this->main_template; ?>images/status_verde.png"></a>
                                                <a href="<?= $this->getPath() ?>/edit/id/{{row.id}}"><i class="s12 icomoon-icon-pencil"></i></a>
                                                <a class="cursor" ng-click='ctrl.delete(row)'><i class="s12 icomoon-icon-remove"></i></a>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <?php require_once $this->main_layouts."options.phtml"; ?>
            </div>
        </div>
        <?php require_once $this->main_layouts."footer.phtml"; ?>
        <div id="modalRelatorios" class="modal fade" tabindex="-1" role="dialog">
            <form class="form-horizontal mt20 formrelatorio" ng-submit="ctrl.submitModal()">
                <div class="modal-dialog" >
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <h4 class="modal-title">Relatório de indicações ativadas por regiões</h4>
                        </div>
                        <div class="modal-body">
                            <label class="col-lg-2 control-label" for="equipe">Período:</label>
                            <div class="col-lg-10">
                                <input class="form-control datemodal date datepicker" required id="datade" name="datade" maxlength="10" autocomplete="off" placeholder="De:">
                                <input class="form-control datemodal date datepicker" required id="dataate" name="dataate" maxlength="10" autocomplete="off" placeholder="Até:">
                            </div>
                            <label class="col-lg-2 control-label" for="equipe">Metas:</label>
                            <div class="col-lg-10">
                                <div ng-repeat='row in ctrl.regionaisRel'>
                                    <input class="form-control datemodal" disabled type="text" value="{{row.titulo}}">
                                    <input class="form-control datemodal" type="number" name="reg_meta[{{row.id}}]" value="{{row.meta}}">
                                    <div ng-if="ctrl.relatorioCompleto">
                                        <div ng-repeat='row2 in row.equipes_list' style="margin-left: 20px">
                                            <input style="width: 190px;" class="form-control datemodal" disabled type="text" value="{{row2.nome}}">
                                            <input style="width: 190px;" class="form-control datemodal" type="number" name="reg_{{row.id}}[{{row2.id}}]" value="{{row2.meta}}">
                                        </div>
                                    </div>
                                </div>
                                <aviso>Regionais com metas vazias não aparecem no relatório.</aviso>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-primary ">Gerar</button>
                            <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <?php require_once $this->main_layouts."plugins.phtml"; ?>
    <script src="<?= $this->main_template; ?>plugins/tables/dataTables/jquery.dataTables.js"></script>
    <script src="<?= $this->main_template; ?>plugins/tables/dataTables/dataTables.tableTools.js"></script>
    <script src="<?= $this->main_template; ?>plugins/tables/dataTables/dataTables.bootstrap.js"></script>
    <script src="<?= $this->main_template; ?>plugins/tables/dataTables/dataTables.responsive.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $(".datepicker").mask("##/##/####");
                $(".datepicker").datepicker({});
            $('.tabletools').dataTable({
                "oLanguage": { "sSearch": "", "sLengthMenu": "<span>_MENU_</span>", "sProcessing": "Processando...", "sZeroRecords": "Não foram encontrados resultados", "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros", "sInfoEmpty": "Mostrando de 0 até 0 de 0 registros", "sInfoFiltered": "", "sInfoPostFix": "", "sUrl": "", "oPaginate": { "sFirst": "Primeiro", "sPrevious": "Anterior", "sNext": "Seguinte", "sLast": "Último" } },
                "sDom": "T<'row'<'col-md-6 col-xs-12 'l><'col-md-6 col-xs-12'f>r>t<'row'<'col-md-4 col-xs-12'i><'col-md-8 col-xs-12'p>>",
                "aaSorting": [ [0, "asc"] ],
                tableTools: { "sSwfPath": "http://cdn.datatables.net/tabletools/2.2.2/swf/copy_csv_xls_pdf.swf", "aButtons": [] }
            });
        });
        angular.module('nova', ['novaServices'])
        .controller('IndexCtrl', function($scope, $http, $sce, NS, $window) {
            this.list = <?= json_encode($this->list) ?>;
            this.onInit = () => {
                $('body').show();
                this.regionaisRel = this.list.filter(x => x.stats == 1);
            }
            this.stats = async (row) => {
                await NS.actionHandler($http.put("<?= $this->system_path.$this->getPath(); ?>/changestatus", row));
                row.stats = row.stats == '1' ? '0' : '1';
                $scope.$digest();
            }
            this.delete = async (row) => {
                if (!confirm('Deletar regional?')) return;
                await NS.actionHandler($http.delete("<?= $this->system_path.$this->getPath(); ?>/deleteSectional/" + row.id));
                location.reload()
            }
            this.modalRelatorio = (completo = false) => {
                this.relatorioCompleto = completo;
                $('#modalRelatorios').modal('show');
            }
            this.submitModal = async () => {
                let data = $('.formrelatorio').serialize();
                if(this.relatorioCompleto) window.open("<?= $this->system_path.$this->getPath(); ?>/exportWithTeam?"+data, "_blank");
                else window.open("<?= $this->system_path.$this->getPath(); ?>/export?"+data, "_blank");
            }
        });
    </script>
    <style>
        .datemodal {
            float: left;
            width: 200px;
        }
    </style>
</body>
</html>