<?php require_once $this->main_layouts."headers.phtml"; ?>
    <script type="text/javascript">
        var pagina = "<?php echo $this->getPath(); ?>";
        var permissao = "<?php echo $this->permissao_ref; ?>";
        var controller = "<?php echo $this->getPath(); ?>/saveDoc";
        var retorno = "<?php echo $this->retorno; ?>";
    </script>
    </head>  
    <body ng-app='nova' ng-controller="Ctrl as ctrl" ng-init='ctrl.onInit()' style='display:none'>
        <?php require_once $this->main_layouts."header.phtml"; ?>
        <div id="wrapper">
            <?php require_once $this->main_layouts."sidebar.phtml"; ?>
            <div id="content" class="page-content clearfix">
                <div class="contentwrapper">
                    <div class="heading">
                        <h3><?php echo $this->module_title; ?></h3>
                        <ul class="breadcrumb">
                            <li>Você está aqui:</li>
                            <li> <a href="#" class="tip" title="Painel"> <i class="s16 icomoon-icon-screen-2"></i> </a> <span class="divider"> <i class="s16 icomoon-icon-arrow-right-3"></i> </span> </li>
                            <li> <a class="tip" title="<?php echo $this->module_title; ?>" href="<?php echo $this->getPath();?>"> <i class="s16 <?php echo $this->module_icon; ?>"></i> </a> </li>
                            <span class="divider"> <i class="s16 icomoon-icon-arrow-right-3"></i> </span>
                            <li class="active">Registro</li>
                        </ul>
                    </div>
                    <div class="form-horizontal group-border">
                        <form ng-submit="ctrl.submitMain()">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default toggle">
                                    <div class="panel-heading">
                                        <h4 class="panel-title">Dados do Template</h4>
                                    </div>
                                    <div class="panel-body">
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="descricao">Descrição</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" ng-model="ctrl.data.titulo" />
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="contexto">Contexto</label>
                                            <div class="col-lg-10">
                                                <textarea class="form-control" rows="5" ng-model="ctrl.data.contexto"></textarea>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="template">Template
                                                <br><small><a href="#" class="btn btn-xs btn-default pull-right" data-toggle="modal" data-target="#modalvariaveis">Palavras chaves sistema</a></small>
                                            </label>
                                            <div class="col-lg-10">
                                                <textarea id="template" name="template" class="form-control" tinymce rows="30"><?php echo stripslashes($this->template) ?></textarea>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="col-lg-offset-2 col-lg-10">
                                                <button type="submit" class="btn btn-info">Salvar</button>
                                                <?php if ((bool)$this->registro['id']): ?> 
                                                    <a type="button" class="btn btn-success" target="_blank" href="<?php echo $this->getPath()?>/exemplo/<?php echo $this->registro['id']; ?>">Visualizar</a> 
                                                <?php endif ?> 
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        </form>
                        <!-- <?php if((bool)$this->registro['id']) : ?>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <h4 class="panel-title">Perguntas chaves formulario</h4>
                                        <div style='float:right' data-toggle="tooltip" data-placement="top" data-original-title="Ordenar">
                                            <a href="<?= $this->retorno; ?>/ordenarItems/id/<?= $this->id ?>"><i class="s16 icomoon-icon-move cursor" style='margin: 8px 11px;'></i></a>
                                        </div>
                                    </div>
                                    <div class="panel-body form-horizontal" >
                                        <table class="tabletools table table-striped table-bordered " width="100%">
                                            <thead>
                                                <tr>
                                                    <th width="60px" class="tal">Ordem</th>
                                                    <th width='60%' class="tal">Pergunta</th>
                                                    <th class="tal">Palavra chave</th>
                                                    <th width="120px" class="tal">Ação</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <form ng-submit="ctrl.varSubmit()">
                                                    <td class="tal"><input class="form-control" disabled /></td>
                                                    <td class="tal"><input class="form-control" required ng-model='ctrl.variavel.descricao' /></td>
                                                    <td class="tal"> <div class="input-group"> <span class="input-group-addon">{[</span> 
                                                        <input class="form-control" maxlength="21" required ng-model='ctrl.variavel.variavel' /> <span class="input-group-addon">]}</span> </div> 
                                                    </td>
                                                    <td class="center">
                                                        <button type="submit" class="btn btn-sm btn-info">Adicionar</button>
                                                    </td>
                                                    </form>
                                                </tr>
                                                <tr ng-repeat="row in ctrl.variaveis">
                                                    <td class="tal">{{row.ordem}}</td>
                                                    <td class="tal">{{row.descricao}}</td>
                                                    <td class="tal link" ng-click="ctrl.copy(row.variavel)">{{row.variavel}}</td>
                                                    <td class="center"><button type="button" ng-click='ctrl.varRemove(row)' class="btn btn-sm btn-danger">Remover</button></td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?php endif ?> -->
                    </div>
                </div>
            </div>
            <?php require_once $this->main_layouts."footer.phtml"; ?>
        </div>

        <div id="modalvariaveis" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title">Palavras chaves sistema</h4>
                    </div>
                    <div class="modal-body">
                        <ul class="list-group">
                            <?php foreach($this->items as $item) : ?>
                            <li ng-click='ctrl.copy("<?= $item['variavel'] ?>")' class="cursor list-group-item"><strong><?= $item['variavel'] ?></strong> - <?= $item['descricao'] ?></li>
                            <?php endforeach ?>
                        </ul>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                    </div>
                </div>
            </div>
        </div>

        <?php require_once $this->main_layouts."plugins.phtml"; ?>
        <script src="<?php echo $this->main_template; ?>plugins/forms/tiny_mce/tinymce.min.js"></script>
        <script type="text/javascript">
            $(document).ready(function(){
                // tinymceInit({css:'tinymce-a4.css'});
                tinymceInit2({css:'tinymce-a4.css'});
            });

            angular.module('nova', ['novaServices'])
            .controller('Ctrl',function($scope, $http, $sce, NS) {
                this.data = <?= json_encode($this->registro); ?>;
                this.variaveis = <?= json_encode(array_values($this->variaveis)); ?>;

                this.onInit = () => {
                    $('body').show();
                }

                this.copy = async (toCopy) => {
                    await navigator.clipboard.writeText(toCopy);
                    NS.notifSucess('Variável copiada');
                    if($('#modalvariaveis').hasClass('in')) $('#modalvariaveis').modal('toggle')
                }

                this.submitMain = async () => {
                    tinymce.triggerSave();
                    this.data.template = $('[tinymce]').val();
                    let res = await NS.actionHandler($http.post("<?php echo $this->getPath(); ?>/save",this.data));
                    if(this.data.id) location.reload();
                    else location.href = "<?php echo $this->retorno; ?>/edit/id/"+res.data;
                }

                this.varSubmit = async () => {
                    this.variavel.id_termo = "<?= $this->registro['id'] ?>";
                    let res = await NS.actionHandler($http.post("<?php echo $this->getPath(); ?>/saveVariable",this.variavel));
                    if(!this.variaveis) this.variaveis = [];
                    this.variaveis.push(res.data);
                    this.variavel = {};
                    $scope.$digest();
                }

                this.varRemove = async (row) => {
                    if(!confirm(`Remover variavel ${row.descricao}?`)) return;
                    await NS.actionHandler($http.delete("<?php echo $this->getPath(); ?>/removeVariable/"+row.id));
                    this.variaveis.splice(this.variaveis.indexOf(row), 1);
                    $scope.$digest();
                }
            })
        </script>
        <style>
            .link {
                color: -webkit-link;
                cursor: pointer;
                text-decoration: underline;
            }

        </style>
    </body>
</html>