<?php require_once $this->main_layouts . "headers.phtml"; ?>
    <link href="<?php echo $this->main_template; ?>plugins/tables/dataTables/jquery.dataTables.css" type="text/css" rel="stylesheet" />
    <link href="<?php echo $this->main_template; ?>plugins/tables/dataTables/TableTools.css" type="text/css" rel="stylesheet" />
    <script type="text/javascript">
        var pagina = "<?php echo $this->getPath(); ?>";
        var permissao = "<?php echo $this->permissao_ref; ?>";
        var controller = "<?php echo $this->getPath(); ?>";
    </script>
    </head>  
    <body ng-app='nova' ng-controller="IndexCtrl as ctrl" style='display:none' ng-init='ctrl.onInit()'>
        <?php require_once $this->main_layouts . "header.phtml"; ?>
        <div id="wrapper">
            <?php require_once $this->main_layouts . "sidebar.phtml"; ?>
            <div id="content" class="page-content clearfix">
                <div class="contentwrapper">
                    <div class="heading">
                        <h3><?php echo $this->module_title; ?></h3>
                        <ul class="breadcrumb">
                            <li>Você está aqui:</li>
                            <li> <a href="#" class="tip" title="Painel"> <i class="s16 icomoon-icon-screen-2"></i> </a> <span class="divider"> <i class="s16 icomoon-icon-arrow-right-3"></i> </span> </li>
                            <li class="active"><?php echo $this->module_title;?></li>
                        </ul>
                    </div>
                    <div class="row">
                        <div class="col-lg-6">
                            <a href="<?php echo $this->getPath();?>/edit"><button type="button" class="btn btn-default mr5 mb10"><i class="glyphicon glyphicon-plus mr5"></i> Novo registro</button></a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="panel panel-default toggle">
                                <div class="panel-heading">
                                    <h4 class="panel-title"><i class="<?php echo $this->module_icon ?>"></i> Modelo de Termo de Filiação
                                    </h4>
                                </div>
                                <div class="panel-body">
                                    <table cellpadding="0" cellspacing="0" border="0" class="tabletools table table-striped table-bordered" width="100%">
                                        <thead>
                                            <tr>                                              
                                                <th width='30%' class="tal">Descrição</th>
                                                <th class="tal">Contexto</th>
                                                <th width='150px' class="center">Ações</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php foreach($this->docs->rows as $row):?>
                                            <tr id="<?= $row['id'];?>">
                                                <td class="tal"><a href="<?php echo $this->getPath()?>/edit/id/<?php echo $row['id']; ?>"><?php echo $row['titulo'];?></a></td>
                                                <td class="tal"><a href="<?php echo $this->getPath()?>/edit/id/<?php echo $row['id']; ?>"><?php echo $row['contexto'];?></a></td>
                                                <td class="center">
                                                    <a target="_blank" href="<?php echo $this->getPath()?>/exemplo/<?php echo $row['id']; ?>" title="Visualizar"><span class="icon12 icomoon-icon-eye"></span></a> 
                                                    <a class='cursor' ng-click="ctrl.copyTermo(<?= $row['id'] ?>)" title="Clonar"><span class="icon12 icomoon-icon-copy"></span></a> 
                                                    <a href="<?php echo $this->getPath()?>/edit/id/<?php echo $row['id']; ?>" title="Editar"><span class="icon12 icomoon-icon-pencil"></span></a> 
                                                    <span title="Apagar" style="cursor:pointer" class="bt_system_delete" data-controller="<?= $this->getPath() ?>" data-id="<?= $row['id']; ?>"><span class="icon12 icomoon-icon-remove"></span></span>
                                                </td>
                                            </tr>
                                            <?php endforeach; ?>
                                        </tbody>                                        
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>

                    <?php require_once $this->main_layouts . "options.phtml"; ?>
                </div>
            </div>            
            <?php require_once $this->main_layouts . "footer.phtml"; ?>        
        </div>        
        <?php require_once $this->main_layouts . "plugins.phtml"; ?>
        <script src="<?php echo $this->main_template; ?>plugins/tables/dataTables/jquery.dataTables.js"></script>
        <script src="<?php echo $this->main_template; ?>plugins/tables/dataTables/dataTables.tableTools.js"></script>
        <script src="<?php echo $this->main_template; ?>plugins/tables/dataTables/dataTables.bootstrap.js"></script>
        <script src="<?php echo $this->main_template; ?>plugins/tables/dataTables/dataTables.responsive.js"></script>

        <script type="text/javascript">
            $(document).ready(function(){
                if($('table').hasClass('tabletools')){
                    $('.tabletools').dataTable( {
                        "oLanguage": {
                            "sSearch": "",
                            "sLengthMenu": "<span>_MENU_</span>",
                            "sProcessing":   "Processando...",                    
                            "sZeroRecords":  "Não foram encontrados resultados",
                            "sInfo":         "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                            "sInfoEmpty":    "Mostrando de 0 até 0 de 0 registros",
                            "sInfoFiltered": "",
                            "sInfoPostFix":  "",
                            "sUrl":         "",

                            "oPaginate": {
                                "sFirst":    "Primeiro",
                                "sPrevious": "Anterior",
                                "sNext":     "Seguinte",
                                "sLast":     "Último"
                            }
                        },
                        "sDom": "T<'row'<'col-md-6 col-xs-12 'l><'col-md-6 col-xs-12'f>r>t<'row'<'col-md-4 col-xs-12'i><'col-md-8 col-xs-12'p>>",
                        "aaSorting":[[0,"asc"]],
                        tableTools: {
                            "sSwfPath": "http://cdn.datatables.net/tabletools/2.2.2/swf/copy_csv_xls_pdf.swf",
                            "aButtons": []
                        }
                    });
                }
            });
            angular.module('nova', ['novaServices'])
            .controller('IndexCtrl',function($scope, $http, $sce, NS, $window) {
                
                this.onInit = () => {
                    $('body').show();
                }

                this.copyTermo = async (id) => {
                    if(!confirm('Clonar termo de filiação')) return;
                    await NS.actionHandler($http.post("<?php echo $this->system_path . $this->getPath() ?>/clone", { id }));
                    location.reload();
                }
            });
        </script>
    </body>
</html>
