<div id="modal_solicitacao" class="modal fade modal-style2" >
    <form class="form-horizontal mt20" ng-submit='ctrl.submitSolArq()' ng-init='ctrl.solArq = {arqs:[{}]}'>
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">
                        <span aria-hidden="true">&times;</span>
                        <span class="sr-only">Close</span>
                    </button>
                    <h4 class="modal-title" >Nova Conta</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group" >
                    <label class="col-lg-2 col-md-3 control-label ng-binding" for="">CPF/CNPJ: </label>
                        <div class="col-lg-10 col-md-9">
                            <input class="form-control" cpf_cnpj ng-model='ctrl.solArq.cpf_cnpj' />
                        </div>
                    </div>
                    <div class="form-group">
                    <label class="col-lg-2 col-md-3 control-label ng-binding" for="">Banco: </label>
                        <div class="col-lg-10 col-md-9">
                            <input required class="form-control" ng-model='ctrl.solArq.banco' />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-2 col-md-3 control-label ng-binding" for="">Conta: </label>
                        <div class="col-lg-10 col-md-9">
                            <input required class="form-control" ng-model='ctrl.solArq.conta' />
                        </div>
                    </div>
                    <div class="form-group">
                    <label class="col-lg-2 col-md-3 control-label ng-binding" for="">Agência: </label>
                        <div class="col-lg-10 col-md-9">
                            <input required class="form-control" ng-model='ctrl.solArq.agencia' />
                        </div>
                    </div>
                    <div class="form-group">
                    <label class="col-lg-2 col-md-3 control-label ng-binding" for="">Operação: </label>
                        <div class="col-lg-10 col-md-9">
                            <input class="form-control" ng-model='ctrl.solArq.operacao' />
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" data-dismiss="modal" class="btn btn-default">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Salvar</button>
                </div>
            </div>
        </div>
    </form>
</div>

<div id="modal_arquivos" class="modal fade modal-style2" >
    <form class="form-horizontal mt20" ng-submit='ctrl.submitEditarConta()' ng-init='ctrl.anexos'>
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">
                        <span aria-hidden="true">&times;</span>
                        <span class="sr-only">Close</span>
                    </button>
                    <h4 class="modal-title" >Nova Conta</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group" >
                    <label class="col-lg-2 col-md-3 control-label ng-binding" for="">CPF/CNPJ: </label>
                        <div class="col-lg-10 col-md-9">
                            <input class="form-control" cpf_cnpj ng-model='ctrl.anexos.cpf_cnpj' />
                        </div>
                    </div>
                    <div class="form-group">
                    <label class="col-lg-2 col-md-3 control-label ng-binding" for="">Banco: </label>
                        <div class="col-lg-10 col-md-9">
                            <input required class="form-control" ng-model='ctrl.anexos.banco' />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-2 col-md-3 control-label ng-binding" for="">Conta: </label>
                        <div class="col-lg-10 col-md-9">
                            <input required class="form-control" ng-model='ctrl.anexos.conta' />
                        </div>
                    </div>
                    <div class="form-group">
                    <label class="col-lg-2 col-md-3 control-label ng-binding" for="">Agência: </label>
                        <div class="col-lg-10 col-md-9">
                            <input required class="form-control" ng-model='ctrl.anexos.agencia' />
                        </div>
                    </div>
                    <div class="form-group">
                    <label class="col-lg-2 col-md-3 control-label ng-binding" for="">Operação: </label>
                        <div class="col-lg-10 col-md-9">
                            <input class="form-control" ng-model='ctrl.anexos.operacao' />
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" data-dismiss="modal" class="btn btn-default">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Salvar</button>
                </div>
            </div>
        </div>
    </form>
</div>