<?php
    require_once $this->main_layouts . "headers.phtml";
?>
    <script type="text/javascript">
        var pagina = "<?php echo $this->getPath(); ?>";
        var permissao = "<?php echo $this->permissao_ref; ?>";
        var controller = "<?php echo $this->getPath(); ?>/save";
        var retorno = "<?php echo $this->retorno; ?>";
    </script>
    </head>  
    <body>
<?php require_once $this->main_layouts . "header.phtml"; ?>
        <!-- / #header -->
        <div id="wrapper">
        <!-- #wrapper -->
<?php require_once $this->main_layouts . "sidebar.phtml"; ?>
            <!--Body content-->
            <div id="content" class="page-content clearfix">
                <div class="contentwrapper">
                    <!--Content wrapper-->
                    <div class="heading">
                        <!--  .heading-->
                        <h3><?php echo $this->module_title; ?></h3>
                        <ul class="breadcrumb">
                            <li>Você está aqui:</li>
                            <li>
                                <a href="#" class="tip" title="Painel">
                                    <i class="s16 icomoon-icon-screen-2"></i>
                                </a>
                                <span class="divider">
                                    <i class="s16 icomoon-icon-arrow-right-3"></i>
                                </span>
                            </li>
                            <li>
                                <a class="tip" title="<?php echo $this->module_title; ?>" href="<?php echo $this->getPath();?>">
                                    <i class="s16 <?php echo $this->module_icon; ?>"></i>                                    
                                </a>
                            </li>
                            <span class="divider">
                                <i class="s16 icomoon-icon-arrow-right-3"></i>
                            </span>
                            <li class="active">Registro</li>
                        </ul>
                    </div>
                    <!-- End  / heading-->
                    <!-- Start .row -->
                    <form name="main" enctype="multipart/form-data" method="post" class="form-horizontal group-border">
                        <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
                        <input type="hidden" name="retorno" value="<?php echo $this->retorno; ?>">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default toggle">
                                    <!-- Start .panel -->
                                    <div class="panel-heading">
                                        <h4 class="panel-title">Dados do Usuário</h4>
                                    </div>
                                    <div class="panel-body">
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="nome">Nome Completo:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="nome" id="nome" type="text" value="<?php echo $this->registro['nome'] ?>" />
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="apelido">Apelido:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="apelido" id="apelido" type="text" value="<?php echo $this->registro['apelido'] ?>" />
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="email">E-mail:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="email" id="email" type="text" value="<?php echo $this->registro['email'] ?>" />
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="telefone">Telefone:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="telefone" id="telefone" type="text" value="<?php echo $this->registro['telefone'] ?>" />
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="data_nascimento">Data Nascimento:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="data_nascimento" id="data_nascimento" type="text" value="<?php echo $this->registro['data_nascimento'] ?>" />
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="fileupload">Avatar:</label>
                                            <div class="col-lg-10">
                                                <label class="fileupload" for="fileupload">
                                                    <?php if ($this->registro['avatar'] == ""): ?>
                                                        <img src="http://placehold.it/40x40" alt="" class="image marginR10"/>
                                                    <?php else: ?>
                                                        <img src="<?php echo $this->getImageFileSized($this->registro['avatar'],40,40); ?>" alt="" class="image marginR10"/>
                                                    <?php endif ?>                                                    
                                                </label>
                                                <input type="file" name="fileupload" id="fileupload" class="files btn btn-default"/>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default toggle">
                                    <!-- Start .panel -->
                                    <div class="panel-heading">
                                        <h4 class="panel-title">Endereço</h4>
                                    </div>
                                    <div class="panel-body">
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="cep">CEP:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="cep" id="cep" type="text" value="<?php echo $this->registro['cep'] ?>" />
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="endereco">Logradouro:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="endereco" id="endereco" type="text" value="<?php echo $this->registro['endereco'] ?>" />
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="numero">Número:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="numero" id="numero" type="text" value="<?php echo $this->registro['numero'] ?>" />
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="complemento">Complemento:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="complemento" id="complemento" type="text" value="<?php echo $this->registro['complemento'] ?>" />
                                            </div>
                                        </div>
                                       
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="id_estado">Estado:</label>
                                            <div class="col-lg-10">
                                                <select class="form-control select2" id="id_estado" name="id_estado">
                                                    <option value="">Selecione..</option>
                                                    <?php if ($this->estados->num_rows) : ?>
                                                        <?php foreach ($this->estados->rows as $estado) : ?>
                                                            <option <?php if ($estado['id'] == $this->registro['id_estado']) echo "selected"; ?> value="<?php echo $estado['id']; ?>"><?php echo $estado['estado']; ?></option>
                                                        <?php endforeach; ?>
                                                    <?php endif; ?>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="id_cidade">Cidade:</label>
                                            <div class="col-lg-10">
                                                <select class="form-control select2" id="id_cidade" name="id_cidade">
                                                    <option value="">Selecione..</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default toggle">
                                    <!-- Start .panel -->
                                    <div class="panel-heading">
                                        <h4 class="panel-title">Dados de Acesso</h4>
                                    </div>
                                    <div class="panel-body">
                                        <div class="form-group form-group-vertical">
                                            <label class="col-lg-2 col-md-3 control-label" for="id_grupo">Grupo</label>
                                            <div class="col-lg-10 col-md-9">
                                                <select class="form-control input-sm" id="id_grupo" name="id_grupo">
                                                    <option value="">Selecione..</option>
                                                    <?php if ($this->grupos->num_rows) : ?>
                                                        <?php foreach ($this->grupos->rows as $grupo) : ?>
                                                            <option <?php if ($grupo['id'] == $this->registro['id_grupo']) echo "selected"; ?> value="<?php echo $grupo['id']; ?>"><?php echo $grupo['nome']; ?></option>
                                                        <?php endforeach; ?>
                                                    <?php endif; ?>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="usuario">Usuário</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="usuario" id="usuario" type="text" value="<?php echo $this->registro['usuario'] ?>" />
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="senha">Senha</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="senha" id="senha" type="password" value="" />
                                            </div>
                                        </div>
                             
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?php if($this->registro["id"] !="" AND $this->level["nivel"] <= $this->registro["nivel"]) :?>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default toggle">
                                    <!-- Start .panel -->
                                    <div class="panel-heading">
                                        <h4 class="panel-title">Anotações</h4>
                                    </div>
                                    <div class="panel-body">
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="anotacoes">Anotações:</label>
                                            <div class="col-lg-10">
                                                <textarea class="form-control tinymce" name="anotacoes" id="anotacoes"><?php echo $this->registro['anotacoes'] ?></textarea>
                                            </div>
                                        </div>                  
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?php endif; ?>
                        <?php if ($this->permissions['group']['ler']): ?>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default ">
                                    <!-- Start .panel -->
                                    <div class="panel-heading">
                                        <h4 class="panel-title">
                                            <label class="pointer">Permissões de Serviço Individuais
                                                <input <?php if ($this->registro['pi2']==1) echo 'checked'; ?> class="" name="pi2" id="pi2" type="checkbox" value="1"> <span class="small help-block">selecione para salvar as permissões individuais de serviço</span>
                                            </label>
                                        </h4>
                                    </div>
                                    <div class="panel-body pi2" style="display:none">
                                        <div class="form-group" id="servicos">
                                            <label class="col-lg-2 control-label" for="">Serviços:</label>
                                            <div class="col-lg-10">
                                                <div class="leftBox" style="margin:0;">
                                                    <div class="searchBox">
                                                        <input type="text" id="box7Filter" class="searchField form-control" style="margin:0;" placeholder="filtrar ..."/>
                                                        <button id="box7Clear" type="button" class="btn">
                                                            <span class="s14  entypo-icon-close "></span>
                                                        </button>
                                                    </div>
                                                    <select id="box7View" multiple="multiple" class="multiple nostyle form-control" style="height:300px;">
                                                        <?php if ($this->servicos->num_rows): ?>
                                                            <?php foreach ($this->servicos->rows as $servico): ?>
                                                                <?php if ($servico['id_servico'] == "") : ?>
                                                                    <option value="<?php echo $servico['id'] ?>"><?php echo $servico['nome'] ?></option>
                                                                <?php endif ?>
                                                            <?php endforeach ?>
                                                        <?php endif ?>
                                                    </select>
                                                    <br>
                                                    <span>Serviços <span class="label-warning" style="padding:0 2px;">não relacionados</span> a este usuário</span>
                                                    <br>
                                                    <span id="box7Counter" class="count"></span>
                                                    <div class="dn"><select id="box7Storage" name="box7Storage" class="nostyle"></select></div>
                                                </div>
                                                <div class="dualBtn">
                                                    <button id="to8" type="button" class="btn" ><span class="icon12 minia-icon-arrow-right-3"></span></button>
                                                    <button id="allTo8" type="button" class="btn" ><span class="icon12 iconic-icon-last"></span></button>
                                                    <button id="to7" type="button" class="btn marginT5"><span class="icon12 minia-icon-arrow-left-3"></span></button>
                                                    <button id="allTo7" type="button" class="btn marginT5" ><span class="icon12 iconic-icon-first"></span></button>
                                                </div>
                                                <div class="rightBox" style="margin:0;">
                                                    <div class="searchBox">
                                                        <input type="text" id="box8Filter" class="searchField form-control" style="margin:0;" placeholder="filtrar ..." />
                                                        <button id="box8Clear"  type="button" class="btn" >
                                                            <span class="s14  entypo-icon-close "></span>
                                                        </button>
                                                    </div>
                                                    <select id="box8View" multiple="multiple" name="servicos[]" class="multiple nostyle form-control" style="height:300px;">
                                                        <?php if ($this->servicos->num_rows): ?>
                                                            <?php foreach ($this->servicos->rows as $servico): ?>
                                                                <?php if ($servico['id_servico'] != "") : ?>
                                                                    <option value="<?php echo $servico['id'] ?>"><?php echo $servico['nome'] ?></option>
                                                                <?php endif ?>
                                                            <?php endforeach ?>
                                                        <?php endif ?>
                                                    </select>
                                                    <br>
                                                    <span>Serviços <span class="label-success white" style="padding:0 2px;">relacionados</span> a este usuário</span>
                                                    <br>
                                                    <span id="box8Counter" class="count"></span>
                                                    <div class="dn"><select id="box8Storage" class="nostyle"></select></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default ">
                                    <!-- Start .panel -->
                                    <div class="panel-heading">
                                        <h4 class="panel-title">
                                            <label class="pointer">Permissões Individuais do Gerenciador
                                                <input <?php if ($this->registro['pi']==1) echo 'checked'; ?> class="" name="pi" id="pi" type="checkbox" value="1"> <span class="small help-block">selecione para salvar as permissões individuais do usuário</span>
                                            </label>
                                        </h4>
                                    </div>
                                    <div class="panel-body pi" style="display:none">
                                        <div class="form-group">
                                            <div class="col-lg-12">
                                                <div class="alert alert-warning fade in">
                                                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                                    <i class="glyphicon glyphicon-warning-sign alert-icon "></i>
                                                    <strong>Aviso!</strong> Estas permissões irão sobrepor as permissões do grupo ao qual este usuário pertence, desmarque a opção acima caso não queira continuar.
                                                </div>
                                                <table class=" table table-striped table-bordered">
                                                    <thead>
                                                        <tr>
                                                            <th>Função</th>
                                                            <th class="center">                                                                
                                                                <input type="checkbox" id="ler_todas">
                                                                <label class="checkbox-inline" for="ler_todas"><b>Ler</b></label>
                                                            </th>
                                                            <th class="center">
                                                                <input type="checkbox" id="gravar_todas">
                                                                <label class="checkbox-inline" for="gravar_todas"><b>Gravar</b></label>
                                                            </th>
                                                            <th class="center">
                                                                <input type="checkbox" id="editar_todas">
                                                                <label class="checkbox-inline" for="editar_todas"><b>Editar</b></label>
                                                            </th>
                                                            <th class="center">
                                                                <input type="checkbox" id="excluir_todas">
                                                                <label class="checkbox-inline" for="excluir_todas"><b>Excluir</b></label>
                                                            </th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        <?php if ($this->funcoes->num_rows): ?>
                                                            <?php foreach ($this->funcoes->rows as $funcao): ?>
                                                                <tr>
                                                                    <td class="tal"><label class="pointer"><input type="checkbox" class="esta_funcao"><span class="esta_funcao_txt"><?php echo $funcao['nome'] ?></span></label></td>
                                                                    <td class="center">
                                                                        <label class="checkbox-inline">
                                                                            <input type="checkbox" name="ler[]" class="leitura" value="<?php echo $funcao['id'] ?>" <?php if($this->id!=""){ if($funcao['ler']) echo ' checked="checked"'; } ?>>
                                                                        </label>
                                                                    </td>
                                                                    <td class="center">
                                                                        <label class="checkbox-inline">
                                                                            <input type="checkbox" name="gravar[]" class="gravacao" value="<?php echo $funcao['id'] ?>" <?php if($this->id!=""){ if($funcao['gravar']) echo ' checked="checked"'; } ?>>
                                                                        </label>
                                                                    </td>
                                                                    <td class="center">
                                                                        <label class="checkbox-inline">
                                                                            <input type="checkbox" name="editar[]" class="edicao" value="<?php echo $funcao['id'] ?>" <?php if($this->id!=""){ if($funcao['editar']) echo ' checked="checked"'; } ?>>
                                                                        </label>
                                                                    </td>
                                                                    <td class="center">
                                                                        <label class="checkbox-inline">
                                                                            <input type="checkbox" name="excluir[]" class="exclusao" value="<?php echo $funcao['id'] ?>" <?php if($this->id!=""){ if($funcao['excluir']) echo ' checked="checked"'; } ?>>
                                                                        </label>
                                                                    </td>
                                                                </tr>
                                                            <?php endforeach ?>
                                                        <?php endif ?>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?php endif; ?>
                        <div class="row">
                            <?php if ($this->id==""): ?>
                                <?php if (!$this->permissions[$this->permissao_ref]['gravar']): ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <span class="label label-warning "><span class="icon24 typ-icon-warning"></span>Você não tem permissão para gravar esta função.</span>
                                        </div>
                                    </div>   
                                <?php else: ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <button type="button" class="btn btn-info clickformsubmit">Salvar novo</button>
                                        </div>
                                    </div>
                                <?php endif ?>
                            <?php else: ?>
                                <?php if (!$this->permissions[$this->permissao_ref]['editar']): ?>
                                <?php if ($_SESSION['admin_id'] != $this->id) : ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <span class="label label-warning"><span class="icon24 icomoon-icon-warning "></span>Você não tem permissão para editar esta função.</span>
                                        </div>
                                    </div>
                                <?php else:?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <button type="button" class="btn btn-info clickformsubmit">Salvar alterações</button>
                                        </div>
                                    </div>
                                <?php endif; ?>
                                <?php else: ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <button type="button" class="btn btn-info clickformsubmit">Salvar alterações</button>
                                        </div>
                                    </div>
                                <?php endif ?>
                            <?php endif ?>
                        </div><!-- End .row -->  
                    </form>
                </div>
                <!-- End contentwrapper -->
            </div>
            <!-- End #content -->
<?php require_once $this->main_layouts . "footer.phtml"; ?>
        </div>
<?php require_once $this->main_layouts . "plugins.phtml"; ?>
        <!-- Init plugins only for page -->
        <script type="text/javascript" src="<?php echo $this->main_template;?>plugins/forms/dualselect/jquery.dualListBox-1.3.min.js"></script>
        <script src="<?php echo $this->main_template; ?>plugins/forms/tiny_mce/tinymce.min.js"></script>
        <script src="<?php echo $this->main_template; ?>plugins/forms/select2/select2.js"></script>
        <script type="text/javascript">
            $(document).ready(function(){
                $(".select2").select2();
                tinymceInit({'galeria':true});
                $.configureBoxes();
                $.configureBoxes1();
                $.configureBoxes2();
                $.configureBoxes3();
                
                if ("<?php echo $this->registro['pi'];?>" != "") {
                    $(".pi").css("display","block");
                }
                if ("<?php echo $this->registro['pi2'];?>" != "") {
                    $(".pi2").css("display","block");
                }
                $("#data_nascimento").datepicker({
                    dateFormat: 'dd/mm/yy',
                    dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'],
                    dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
                    dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
                    monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
                    monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
                    nextText: 'Próximo',
                    prevText: 'Anterior'
                });
                $('#data_nascimento').mask('##/##/####');
                $('#cep').mask('##.###-###');
                $('#cep').on("focusout",function() {
                    let estados = <?php echo json_encode($this->estados->rows) ?>
                    
                    var cep = $(this).val().replace('-','').replace('.','');
                    if(cep.length == 8) {
                        $.get(`https://viacep.com.br/ws/${cep}/json/`)
                        .then(data => {
                            $('#endereco').val(data.logradouro);
                            $('#complemento').val(data.complemento);
                            $('#bairro').val(data.bairro);
                            let id_estado = estados.find(x => x.uf == data.uf).id;
                            $("select[name=id_estado]").val(id_estado).change();

                            let id_cidade = $(`select[name=id_cidade] option[data-name='${data.localidade}']`).val();
                            $("select[name=id_cidade]").val(id_cidade).change();
                        })
                    }
                })
                $("#id_estado").on("change",function () {
                    var id = $(this).val();
                    if(id !== ""){
                        $.ajax({
                            method:"POST",
                            url:"main/general/getCidadesByEstado",
                            data:{id:id},
                            async:false
                        }).done(function(data){
                            $("select[name=id_cidade]").html(data);
                            $("select[name=id_cidade]").select2();
                        });
                    }
                });
                $(window).load(function () {
                    var id = $('#id_estado').val();
                    if(id !== ""){
                        $.ajax({
                            method:"POST",
                            url:"main/general/getCidadesByEstado",
                            data:{id:id},
                            async:false
                        }).done(function(data){
                            $("select[name=id_cidade]").html(data);
                            $("select[name=id_cidade]").select2();

                            $("select[name=id_cidade]").val(<?= $this->registro['id_cidade'] ?>).change();
                        })
                    }
                });
                $("#id_nivel").on("change", function(){
                    if(this.value != "")
                    $.post("<?php echo $this->getPath(); ?>/getSelect", {id : this.value, id_register : "<?php echo $this->id; ?>"}, function(data){
                        $("#empresas").html(data);
                    });
                });
                $("#estado").on("change",function () {
                    var id = $(this).val();
                    if(id !== ""){
                        $.ajax({
                            method:"POST",
                            url:"main/general/getCidadesByEstado",
                            data:{id:id},
                            async:false
                        }).done(function(data){
                            $("select[name=id_cidade]").html(data);
                            $("select[name=id_cidade]").select2();
                        });
                    }
                });
                <?php if($this->id != "") :?>
                $("#estado").trigger("change");
                $("#id_cidade").val("<?php echo $this->registro['id_cidade'] ?>").trigger("change");
                <?php endif; ?>
            });
        </script>
    </body>
</html>
