<?php require_once $this->main_layouts . "headers.phtml"; ?>
<script type="text/javascript">
    var pagina = "<?php echo $this->getPath(); ?>";
    var permissao = "<?php echo $this->permissao_ref; ?>";
    var controller = "<?php echo $this->getPath(); ?>/save";
    var retorno = "<?php echo $this->retorno; ?>";
</script>
</head>
<body>
<?php require_once $this->main_layouts . "header.phtml"; ?>
<div id="wrapper">
    <?php require_once $this->main_layouts . "sidebar.phtml"; ?>
    <div id="content" class="page-content clearfix">
        <div class="contentwrapper">
            <div class="heading">
                <h3><?php echo $this->module_title; ?></h3>
                <ul class="breadcrumb">
                    <li>Você está aqui:</li>
                    <li>
                        <a href="#" class="tip" title="Painel">
                            <i class="s16 icomoon-icon-screen-2"></i>
                        </a>
                        <span class="divider">
                            <i class="s16 icomoon-icon-arrow-right-3"></i>
                        </span>
                    </li>
                    <li>
                        <a class="tip" title="<?php echo $this->module_title; ?>" href="<?php echo $this->module_link; ?>">
                            <i class="s16 <?php echo $this->module_icon; ?>"></i>
                        </a>
                    </li>
                    <span class="divider">
                        <i class="s16 icomoon-icon-arrow-right-3"></i>
                    </span>
                    <li class="active">Registro</li>
                </ul>
            </div>
            <form name="main" enctype="multipart/form-data" method="post" class="form-horizontal group-border">
                <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
                <input type="hidden" name="retorno" value="<?php echo $this->retorno; ?>">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="panel panel-default toggle">
                            <div class="panel-heading">
                                <h4 class="panel-title">Dados do SEO</h4>
                            </div>
                            <div class="panel-body">
                                <div class="form-group">
                                    <label class="col-lg-2 control-label" for="seo_title">Título da Página:</label>
                                    <div class="col-lg-10">
                                        <input class="form-control" name="seo_title" id="seo_title" type="text" value="<?php echo $this->registro['seo_title']; ?>" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-lg-2 control-label" for="seo_description">Breve Descrição:</label>
                                    <div class="col-lg-10">
                                        <input class="form-control" name="seo_description" id="seo_description" type="text" value="<?php echo $this->registro['seo_description']; ?>" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-lg-2 control-label" for="seo_keywords">Palavras Chave:</label>
                                    <div class="col-lg-10">
                                        <input class="form-control" name="seo_keywords" id="seo_keywords" type="text" value="<?php echo $this->registro['seo_keywords']; ?>" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-lg-2 control-label" for="seo_url">URL Amigável:</label>
                                    <div class="col-lg-10">
                                        <input class="form-control" name="seo_url" id="seo_url" type="text" value="<?php echo $this->registro['seo_url']; ?>" />
                                    </div>
                                </div>
                                
                                <?php if ($this->registro['seo_url_breadcrumbs'] != "home/") : ?>
                                <div class="form-group target_toggle">
                                    <label class="col-lg-2 control-label" for="fileupload">Imagem:</label>
                                    <div class="col-lg-10">
                                        <label class="fileupload" for="fileupload">
                                            <?php if ($this->registro['imagem'] == "") : ?>
                                                <img src="http://placehold.it/<?php echo $this->width; ?>x<?php echo $this->height; ?>?text=<?php echo $this->width; ?>x<?php echo $this->height; ?>" alt="" class="image marginR10"/>
                                            <?php else : ?>
                                                <img src="<?php echo $this->getImageFileSized($this->registro['imagem'], $this->width, $this->height); ?>" alt="" class="image marginR10"/>
                                            <?php endif; ?>
                                        </label>
                                        <input type="file" name="fileupload" id="fileupload" class="files btn btn-default"/>
                                        <span class="help-block blue">a imagem será apresentada na seguinte proporção <?php echo $this->width; ?>x<?php echo $this->height; ?> pixels.</span>
                                    </div>
                                </div>
                                <?php endif; ?>

                                <?php if ($this->registro['seo_url_breadcrumbs'] != "home/") : ?>                                                
                                    <div class="form-group">
                                        <label class="col-lg-2 control-label" for="seo_pagina_title">Título do Conteúdo:</label>
                                        <div class="col-lg-10">
                                            <input class="form-control" name="seo_pagina_title" id="seo_pagina_title" type="text" value="<?php echo $this->registro['seo_pagina_title']; ?>" />
                                        </div>
                                    </div>

                                    <?php if ($this->registro['seo_url_breadcrumbs'] != "blog/" && $this->registro['seo_url_breadcrumbs'] != "contato/" ) : ?>
                                    <div class="form-group target_toggle">
                                        <label class="col-lg-2 control-label" for="seo_pagina_conteudo">Conteúdo:</label>
                                        <div class="col-lg-10">
                                            <textarea class="form-control summernote"  name="seo_pagina_conteudo" id="seo_pagina_conteudo"  rows="10"><?php echo $this->registro['seo_pagina_conteudo']; ?></textarea>
                                            <!-- <textarea class="form-control elastic tinymce" name="seo_pagina_conteudo" id="seo_pagina_conteudo"></textarea> -->
                                        </div>
                                    </div>
                                    <?php endif; ?>

                                    <?php if ($this->registro['seo_url_breadcrumbs'] != "sobre/" && $this->registro['seo_url_breadcrumbs'] != "blog/"  && $this->registro['seo_url_breadcrumbs'] != "contato/" ) : ?>      
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="link_conteudo">link Conteúdo:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="link_conteudo" id="link_conteudo" type="text" value="<?php echo $this->registro['link_conteudo']; ?>" />
                                            </div>
                                        </div>
                                    <?php endif; ?>

                                <?php endif; ?>   

                                <?php if ($this->registro['seo_url_breadcrumbs'] != "home/" && $this->registro['seo_url_breadcrumbs'] != "sobre/" && $this->registro['seo_url_breadcrumbs'] != "blog/") : ?>     
                                <div class="form-group target_toggle">
                                    <label class="col-lg-2 control-label" for="text_aux">Texto:</label>
                                    <div class="col-lg-10">
                                           <textarea class="form-control summernote"  name="text_aux" id="text_aux"  rows="10"><?php echo $this->registro['text_aux']; ?></textarea>
                                        <!-- <textarea class="form-control elastic tinymce" name="seo_pagina_conteudo" id="seo_pagina_conteudo"></textarea> -->
                                    </div>
                                </div>
                                <?php endif; ?> 
                                
                                <div class="form-group">
                                    <label class="col-lg-2 control-label" for="seo_scripts">Scripts:</label>
                                    <div class="col-lg-10">
                                        <textarea id="seo_scripts" name="seo_scripts" class="form-control elastic" rows="3"><?php echo stripslashes($this->registro['seo_scripts']); ?></textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <?php if ($this->id == "") : ?>
                        <?php if (!$this->permissions[$this->permissao_ref]['gravar']) : ?>
                            <div class="form-group">
                                <div class="col-lg-offset-2 col-lg-10">
                                    <span class="label label-warning "><span class="icon24 typ-icon-warning"></span>Você não tem permissão para gravar esta função.</span>
                                </div>
                            </div>
                        <?php else : ?>
                            <div class="form-group">
                                <div class="col-lg-offset-2 col-lg-10">
                                    <button type="button" class="btn btn-info clickformsubmit">Salvar novo</button>
                                </div>
                            </div>
                        <?php endif; ?>
                    <?php else : ?>
                        <?php if (!$this->permissions[$this->permissao_ref]['editar']) : ?>
                            <div class="form-group">
                                <div class="col-lg-offset-2 col-lg-10">
                                    <span class="label label-warning"><span class="icon24 icomoon-icon-warning "></span>Você não tem permissão para editar esta função.</span>
                                </div>
                            </div>
                        <?php else : ?>
                            <div class="form-group">
                                <div class="col-lg-offset-2 col-lg-10">
                                    <button type="button" class="btn btn-info clickformsubmit">Salvar alterações</button>
                                </div>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>
                </div>
            </form>
        </div>
    </div>
    <?php  require_once $this->main_layouts . "footer.phtml"; ?>
</div>
<?php  require_once $this->main_layouts . "plugins.phtml"; ?>
<script src="<?php echo $this->main_template; ?>plugins/forms/tiny_mce/tinymce.min.js"></script>
<script src="<?php echo $this->main_template; ?>plugins/forms/autosize/jquery.autosize.js"></script>
<script src="<?php echo $this->main_template; ?>plugins/files/plupload/plupload.js"></script>
<script src="<?php echo $this->main_template; ?>plugins/files/plupload/plupload.html4.js"></script>
<script src="<?php echo $this->main_template; ?>plugins/files/plupload/plupload.flash.js"></script>
<script src="<?php echo $this->main_template; ?>plugins/files/plupload/jquery.plupload.queue/jquery.plupload.queue.js"></script>
<script src="<?php echo $this->main_template;?>plugins/forms/summernote/summernote.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        saveKey(true);
        tinymceInit({css:'tinymce.css'});
        //$('.elastic').autosize();
        summernote();
    });
</script>
</body>
</html>
