<div class="document">
    <div class="field_input box_input">
        <div class="col-lg-8 col-lg-offset-2">
            <div class="input-group">
                <input class="form-control inputs_add_rm no-border-right documento" name="documentos[]" type="text" value="" />
                <span class="input-group-addon">
                    <label>Tipo:&nbsp;</label>
                    <select style="border:1px solid #ccc" name="documentos[tipo][]">
                        <option value="">Selecione..</option>
                    </select>
                </span>
                <span class="input-group-addon">
                    <div style="margin-top: 0" class="radio-custom">
                        <input type="radio" id="" class="radio_main" name="documentos[principal]">
                        <label for="">Principal</label>
                    </div>
                </span>
            </div>
        </div>
        <div class="col-lg-1">
            <span class="icomoon-icon-plus-circle btn btn-md btn-default input_add"/></span>
        </div>
        <div class="col-lg-1">
            <span class="icomoon-icon-minus-circle btn btn-md btn-default input_remove"/></span>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {


        $('body').on('click', '#documentos .input_add', function (e) {
            e.preventDefault();

            var $base = $(this).parents('.box_input');

            var last_idx = 0;

            $("#documentos .box_input").find("input[type=radio]").each(function () {
                last_idx++;
            });

            var $template = $("#templates .document").clone();

            var $input_text = $template.find("input[type=text]");
            $input_text.attr("name", "documentos[" + last_idx + "][data]");

            var $input_radio = $template.find("input[type=radio]");
            $input_radio.attr("name", "documentos[" + last_idx + "][principal]");
            $input_radio.attr("id", "doc_" + last_idx);
            $input_radio.next().attr("for", "doc_" + last_idx);

            var $combo_box = $template.find("select");
            $combo_box.attr("name", "documentos[" + last_idx + "][tipo]");
            <?php foreach ($this->documento_tipos as $indice): ?>
                $combo_box.append('<option value="<?php echo $indice['code']; ?>"><?php echo $indice['nome']; ?></option>');
            <?php endforeach; ?>

            $base.after($template.html());

            updateDoc();

        });

        $('body').on('click', '#documentos .input_remove', function (e) {
            e.preventDefault();
            var $input = $(this).parents('#documentos .box_input:first');
            var $inputs = $("#documentos .box_input");

            if ($inputs.length > 1)
                $input.remove();
            else
                $input.find('input').val('');

            if ($(document).find('#documentos .box_input:first').find('.col-lg-8.col-lg-offset-2').length == 1)
                $(document).find('#documentos .box_input:first').find('.col-lg-8').removeClass('col-lg-offset-2');

            if ($inputs.length == 1)
                $(document).find('#documentos').find('.box_input .col-lg-8.col-lg-offset-2').removeClass('col-lg-offset-2');

            if ($(document).find("#documentos").find('input[type=radio]:checked').length == 0)
                $(document).find('#documentos .box_input:first').find('input[type=radio]').prop('checked', true).val("0");

            updateDoc();

        });

        $(document).on('change', "#documentos select", function () {
            updateDoc();
        });

        function updateDoc(init = 0){
            $(document).find("#documentos select").each(function () {
                var $input = $(this).parents('.input-group').find('input');
                if ($(this).val() != '') {
                    $input.prop('disabled', false);
                    $input.filter("[type=text]").attr('placeholder', '');
                    /*
                     if($(document).find("#documentos").find('#documentos input[type=radio]:checked:not([disabled])').length == 0)
                     $input.filter("[type=radio]").prop('checked', true).trigger('change');
                     */
                    if ($(document).find('#documentos input[type=radio]:checked:not([disabled])').length == 0)
                        $input.filter("[type=radio]").prop('checked', true).trigger('change');
                } else {
                    $input.prop('disabled', true);
                    if (!init)
                        $input.filter("[type=text]").val("");
                    $input.filter("[type=text]").attr('placeholder', 'Selecione o Tipo');
                }
                switch ($(this).val()) {
                    case '#000000001':
                        $input.filter("[type=text]").mask("999.999.999-99");
                        break;
                    case '#000000002':
                        $input.filter("[type=text]").mask("99.999.999/9999-99");
                        break;
                    default:
                        $input.unmask();
                }
            });

            uniform();
        }

        updateDoc(1);
    });
</script>