<?php require_once $this->main_layouts . "headers.phtml"; ?>
<script type="text/javascript">
    var pagina = "<?php echo $this->getPath(); ?>";
    var permissao = "<?php echo $this->permissao_ref; ?>";
    var controller = "<?php echo $this->getPath(); ?>/save";
    var retorno = "<?php echo $this->retorno; ?>";
</script>
</head>
<body>
<?php require_once $this->main_layouts . "header.phtml"; ?>
<div id="wrapper">
    <?php require_once $this->main_layouts . "sidebar.phtml"; ?>
    <div id="content" class="page-content clearfix">
        <div class="contentwrapper">
            <div class="heading">
                <h3><?php echo $this->module_title; ?></h3>
                <ul class="breadcrumb">
                    <li>Você está aqui:</li>
                    <li>
                        <a href="#" class="tip" title="Painel">
                            <i class="s16 icomoon-icon-screen-2"></i>
                        </a>
                        <span class="divider">
                            <i class="s16 icomoon-icon-arrow-right-3"></i>
                        </span>
                    </li>
                    <li>
                        <a class="tip" title="<?php echo $this->module_title; ?>" href="<?php echo $this->module_link; ?>">
                            <i class="s16 <?php echo $this->module_icon; ?>"></i>
                        </a>
                    </li>
                    <span class="divider">
                        <i class="s16 icomoon-icon-arrow-right-3"></i>
                    </span>
                    <li class="active">Registro</li>
                </ul>
            </div>
            <div class="row">
                <div class="col-lg-12 ">
                    <form name="main" enctype="multipart/form-data" method="post" class="form-horizontal group-border">
                        <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
                        <input type="hidden" name="retorno" value="<?php echo $this->retorno; ?>">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default toggle">
                                    <div class="panel-heading">
                                        <h4 class="panel-title">Dados da Página
                                        </h4>
                                    </div>
                                    <div class="panel-body">

                                     <div class="form-group">
                                            <label class="col-lg-2 control-label" for="titulo_um">Título 1</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="titulo_um" id="titulo_um" type="text" value="<?php echo $this->registro['titulo_um']; ?>" />
                                            </div>
                                       </div>
                                       <div class="form-group">
                                            <label class="col-lg-2 control-label" for="texto_um">Texto 1:</label>
                                            <div class="col-lg-10">
                                                <textarea class="form-control summernote"  name="texto_um" id="texto_um" rows="5"><?php echo $this->registro['texto_um']; ?></textarea>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="titulo_dois">Título 2</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="titulo_dois" id="titulo_dois" type="text" value="<?php echo $this->registro['titulo_dois']; ?>" />
                                            </div>
                                       </div>
                                       <div class="form-group">
                                            <label class="col-lg-2 control-label" for="texto_dois">Texto 2:</label>
                                            <div class="col-lg-10">
                                                <textarea class="form-control summernote"  name="texto_dois" id="texto_dois" rows="5"><?php echo $this->registro['texto_dois']; ?></textarea>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="titulo_tres">Título 3</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="titulo_tres" id="titulo_tres" type="text" value="<?php echo $this->registro['titulo_tres']; ?>" />
                                            </div>
                                       </div>
                                       <div class="form-group">
                                            <label class="col-lg-2 control-label" for="texto_tres">Texto 3:</label>
                                            <div class="col-lg-10">
                                                <textarea class="form-control summernote"  name="texto_tres" id="texto_tres" rows="5"><?php echo $this->registro['texto_tres']; ?></textarea>
                                            </div>
                                        </div>

                                       <div class="form-group">
                                            <label class="col-lg-2 control-label" for="titulo_quatro">Título 4</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="titulo_quatro" id="titulo_quatro" type="text" value="<?php echo $this->registro['titulo_quatro']; ?>" />
                                            </div>
                                       </div>
                                       <div class="form-group">
                                            <label class="col-lg-2 control-label" for="texto_quatro">Texto 4:</label>
                                            <div class="col-lg-10">
                                                <textarea class="form-control summernote"  name="texto_quatro" id="texto_quatro" rows="5"><?php echo $this->registro['texto_quatro']; ?></textarea>
                                            </div>
                                        </div>

                                        <div class="form-group" id="imagem_target">
                                            <label class="col-lg-2 control-label" for="imagem">Imagem:</label>
                                            <div class="col-lg-10">
                                                <label class="fileupload" for="imagem">
                                                    <?php if ($this->registro['imagem'] == ""): ?>
                                                        <img src="http://placehold.it/<?= $this->w_imagem . "x" . $this->h_imagem ?>" alt="" class="image marginR10"/>
                                                    <?php else : ?>
                                                        <img src="<?php echo $this->getImageFileSized($this->registro['imagem'],$this->w_imagem,$this->h_imagem); ?>" alt="" class="image marginR10"/>
                                                    <?php endif ?>
                                                </label>
                                                <input type="file" name="imagem" id="imagem" class="files btn btn-default"/>
                                                <span class="help-block blue">A imagem será apresentada na proporção de <?php echo $this->w_imagem."x".$this->h_imagem ?> pixels.</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <?php if ($this->id==""): ?>
                                <?php if (!$this->permissions[$this->permissao_ref]['gravar']): ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <span class="label label-warning "><span class="icon24 typ-icon-warning"></span>Você não tem permissão para gravar esta função.</span>
                                        </div>
                                    </div>
                                <?php else: ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <button type="button" class="btn btn-info clickformsubmit">Salvar novo</button>
                                        </div>
                                    </div>
                                <?php endif ?>
                            <?php else: ?>
                                <?php if (!$this->permissions[$this->permissao_ref]['editar']): ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <span class="label label-warning"><span class="icon24 icomoon-icon-warning "></span>Você não tem permissão para editar esta função.</span>
                                        </div>
                                    </div>
                                <?php else: ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <button type="button" class="btn btn-info clickformsubmit">Salvar alterações</button>
                                        </div>
                                    </div>
                                <?php endif ?>
                            <?php endif ?>
                        </div>
                    </form>
                    <?php  require_once $this->main_layouts . "options.phtml"; ?>
                </div>
            </div>
        </div>
    </div>
<?php require_once $this->main_layouts . "footer.phtml"; ?>
</div>
<?php require_once $this->main_layouts . "plugins.phtml"; ?>
<script src="<?php echo $this->main_template; ?>plugins/forms/tiny_mce/tinymce.min.js"></script>
<script src="<?php echo $this->main_template; ?>plugins/ui/tabdrop/bootstrap-tabdrop.js"></script>
<script src="<?php echo $this->main_template; ?>js/pages/tabs.js"></script>
<script type="text/javascript" src="<?php echo $this->main_template; ?>plugins/files/elfinder/elfinder.min.js"></script>
<script type="text/javascript" src="<?php echo $this->main_template; ?>plugins/files/plupload/plupload.full.min.js"></script>
<script type="text/javascript" src="<?php echo $this->main_template; ?>plugins/files/plupload/jquery.plupload.queue/jquery.plupload.queue.js"></script>
<script type="text/javascript" src="<?php echo $this->main_template; ?>plugins/files/plupload/i18n/pt_BR.js"></script>
<script src="<?php echo $this->main_template; ?>plugins/forms/autosize/jquery.autosize.js"></script>
<script src="<?php echo $this->main_template;?>plugins/forms/summernote/summernote.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $('.elastic').autosize();
        tinymceInit({css:'tinymce.css'});
        summernote();
    });
</script>
</body>
</html>
