<?php
    require_once $this->main_layouts . "headers.phtml";
?>

    <script type="text/javascript">
        var pagina = "<?php echo $this->getPath(); ?>";
        var permissao = "<?php echo $this->permissao_ref; ?>";
        var controller = "<?php echo $this->getPath(); ?>/save";
        var retorno = "<?php echo $this->retorno; ?>";
    </script>
    
    </head>  
    
    
    <body>
<?php  require_once $this->main_layouts . "header.phtml"; ?>

        <!-- / #header -->
        <div id="wrapper">
        <!-- #wrapper -->

<?php  require_once $this->main_layouts . "sidebar.phtml"; ?>
            
            <!--Body content-->
            <div id="content" class="page-content clearfix">
                <div class="contentwrapper">
                    <!--Content wrapper-->
                    <div class="heading">
                        <!--  .heading-->
                        <h3><?php echo $this->module_title; ?></h3>

                        <ul class="breadcrumb">
                            <li>Você está aqui:</li>
                            <li>
                                <a href="#" class="tip" title="Painel">
                                    <i class="s16 icomoon-icon-screen-2"></i>
                                </a>
                                <span class="divider">
                                    <i class="s16 icomoon-icon-arrow-right-3"></i>
                                </span>
                            </li>
                            <li>
                                <a class="tip" title="<?php echo $this->module_title; ?>" href="<?php echo $this->getPath();?>">
                                    <i class="s16 <?php echo $this->module_icon; ?>"></i>                                    
                                </a>
                            </li>
                            <span class="divider">
                                <i class="s16 icomoon-icon-arrow-right-3"></i>
                            </span>
                            <li class="active">Registro</li>
                        </ul>
                    </div>
                    <!-- End  / heading-->
                    <!-- Start .row -->
                  
                    <form name="main" enctype="multipart/form-data" method="post" class="form-horizontal group-border">
                        <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
                        <input type="hidden" name="retorno" value="<?php echo $this->retorno; ?>">
                        
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default toggle">
                                    <!-- Start .panel -->
                                    <div class="panel-heading">
                                        <h4 class="panel-title">E-mail</h4>
                                    </div>
                                    <div class="panel-body">
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="autenticado">Autenticação:</label>
                                            <div class="col-lg-10">
                                                <label class="pointer" for="autenticado1">Sim</label><input <?php if ($this->registro['autenticado'] == 1) { echo 'checked'; } ?> class="form-control" name="autenticado" id="autenticado1" type="radio" value="1" /> 
                                                <label class="pointer" for="autenticado2">Não</label><input <?php if ($this->registro['autenticado'] == 0) { echo 'checked'; } ?> class="form-control" name="autenticado" id="autenticado2" type="radio" value="0" />
                                            </div>
                                        </div><!-- End .form-group  -->
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="email_host">Host:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="email_host" id="email_host" type="text" value="<?php echo $this->registro['email_host'] ?>" />
                                            </div>
                                        </div><!-- End .form-group  -->
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="email_port">Port:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="email_port" id="email_port" type="text" value="<?php echo $this->registro['email_port'] ?>" />
                                            </div>
                                        </div><!-- End .form-group  -->
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="email_user">User:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="email_user" id="email_user" type="text" value="<?php echo $this->registro['email_user'] ?>" />
                                            </div>
                                        </div><!-- End .form-group  -->
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="email_password">Password:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="email_password" id="email_password" type="password" value="<?php echo $this->registro['email_password'] ?>" />
                                            </div>
                                        </div><!-- End .form-group  -->
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="email_padrao">E-mail de envio padrão:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="email_padrao" id="email_padrao" type="text" value="<?php echo $this->registro['email_padrao'] ?>" />
                                            </div>
                                        </div><!-- End .form-group  -->                                        
                                    </div>
                                </div><!-- End .panel -->
                            </div><!-- End .span12 -->
                        </div>
                        
                        <div class="row">
                            <?php if ($this->id==""): ?>
                                <?php if (!$this->permissions[$this->permissao_ref]['gravar']): ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <span class="label label-warning "><span class="icon24 typ-icon-warning"></span>Você não tem permissão para gravar esta função.</span>
                                        </div>
                                    </div><!-- End .form-group  -->   
                                <?php else: ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <button type="button" class="btn btn-info clickformsubmit">Salvar novo</button>
                                        </div>
                                    </div><!-- End .form-group  -->
                                <?php endif ?>
                            <?php else: ?>
                                <?php if (!$this->permissions[$this->permissao_ref]['editar']): ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <span class="label label-warning"><span class="icon24 icomoon-icon-warning "></span>Você não tem permissão para editar esta função.</span>
                                        </div>
                                    </div><!-- End .form-group  -->   
                                <?php else: ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <button type="button" class="btn btn-info clickformsubmit">Salvar alterações</button>
                                        </div>
                                    </div><!-- End .form-group  -->
                                <?php endif ?>
                            <?php endif ?>
                        </div><!-- End .row -->  
                    </form>
                </div>
                <!-- End contentwrapper -->
            </div>
            <!-- End #content -->
            
            
<?php  require_once $this->main_layouts . "footer.phtml"; ?>
        
        </div>
        
<?php  require_once $this->main_layouts . "plugins.phtml"; ?>
        <!-- Init plugins only for page -->
        <script type="text/javascript">
            $(document).ready(function(){
                saveKey(true);
            });
        </script>
    </body>
</html>
