<?php require_once $this->main_layouts . "headers.phtml"; ?>

    <script type="text/javascript">
        var pagina = "<?php echo $this->getPath(); ?>";
        var permissao = "<?php echo $this->permissao_ref; ?>";
        var controller = "<?php echo $this->getPath(); ?>/save";
        var retorno = "<?php echo $this->retorno; ?>";
    </script>
    
    </head>      
    
    <body>
        <?php   require_once $this->main_layouts . "header.phtml"; ?>
        <div id="wrapper">
            <?php   require_once $this->main_layouts . "sidebar.phtml"; ?>
            <div id="content" class="page-content clearfix">
                <div class="contentwrapper">
                    <!--Content wrapper-->
                    <div class="heading">
                        <!--  .heading-->
                        <h3><?php echo $this->module_title; ?></h3>

                        <ul class="breadcrumb">
                            <li>Você está aqui:</li>
                            <li>
                                <a href="#" class="tip" title="Painel">
                                    <i class="s16 icomoon-icon-screen-2"></i>
                                </a>
                                <span class="divider">
                                    <i class="s16 icomoon-icon-arrow-right-3"></i>
                                </span>
                            </li>
                            <li>
                                <a class="tip" title="<?php echo $this->module_title; ?>" href="<?php echo $this->module_link;?>">
                                    <i class="s16 <?php echo $this->module_icon; ?>"></i>                                    
                                </a>
                            </li>
                            <span class="divider">
                                <i class="s16 icomoon-icon-arrow-right-3"></i>
                            </span>
                            <li class="active">Registro</li>
                        </ul>
                    </div>
                  
                    <form name="main" enctype="multipart/form-data" method="post" class="form-horizontal group-border">
                        <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
                        <input type="hidden" name="retorno" value="<?php echo $this->retorno; ?>">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default toggle">
                                    <!-- Start .panel -->
                                    <div class="panel-heading">
                                        <h4 class="panel-title">Dados do Banner</h4>
                                    </div>
                                    <div class="panel-body">                                                                               
                                        <div class="form-group target_toggle">
                                            <label class="col-lg-2 control-label" for="nome">Nome</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="nome" id="nome" type="text" value="<?php echo $this->registro['nome'] ?>" />
                                            </div><!-- End .form-group  -->
                                        </div>
                                    
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="descricao">Descrição</label>
                                            <div class="col-lg-10">
                                                <textarea class="form-control elastic summernote" name="descricao" id="descricao"><?php echo $this->registro['descricao'] ?></textarea>
                                            </div><!-- End .form-group  -->
                                        </div>
                                    
                                        <div class="form-group target_toggle">
                                            <label class="col-lg-2 control-label" for="fileupload">Imagem Desktop:</label>
                                            <div class="col-lg-10">
                                                <label class="fileupload" for="fileupload_desktop">
                                                    <?php if ($this->registro['imagem_desktop'] == ""): ?>
                                                        <img src="http://placehold.it/<?php echo $this->w_d;?>x<?php echo $this->h_d;?>?text=<?php echo $this->w_d;?>x<?php echo $this->h_d;?>" alt="" class="image marginR10"/>
                                                    <?php else: ?>
                                                        <img src="<?php echo $this->getImageFileSized($this->registro['imagem_desktop'],$this->w_d,$this->h_d); ?>" alt="" class="image marginR10"/>
                                                    <?php endif ?>
                                                </label>
                                                <input type="file" name="fileupload_desktop" id="fileupload_desktop" class="files btn btn-default"/>
                                                <span class="help-block blue">a imagem será apresentada na seguinte proporção <?php echo $this->w_d;?>x<?php echo $this->h_d;?> pixels.</span>
                                            </div>
                                        </div>

                                        <!-- <div class="form-group target_toggle">
                                            <label class="col-lg-2 control-label" for="fileupload">Imagem Mobile:</label>
                                            <div class="col-lg-10">
                                                <label class="fileupload" for="fileupload_mobile">
                                                    <?php if ($this->registro['imagem_mobile'] == ""): ?>
                                                        <img src="http://placehold.it/<?php echo $this->w_m;?>x<?php echo $this->h_m;?>?text=<?php echo $this->w_m;?>x<?php echo $this->h_m;?>" alt="" class="image marginR10"/>
                                                    <?php else: ?>
                                                        <img src="<?php echo $this->getImageFileSized($this->registro['imagem_mobile'],$this->w_m,$this->h_m); ?>" alt="" class="image marginR10"/>
                                                    <?php endif ?>
                                                </label>
                                                <input type="file" name="fileupload_mobile" id="fileupload_mobile" class="files btn btn-default"/>
                                                <span class="help-block blue">a imagem será apresentada na seguinte proporção <?php echo $this->w_m;?>x<?php echo $this->h_m;?> pixels.</span>
                                            </div>
                                        </div> -->

                                        <div class="form-group target_toggle">
                                            <label class="col-lg-2 control-label" for="link">Link:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="link" id="link" type="text" value="<?php echo $this->registro['link'] ?>" />                                  
                                            </div>
                                        </div><!-- End .form-group  -->
                                        
                                        <div class="form-group target_toggle">
                                            <label class="col-lg-2 control-label noStyle" for="target">Target:</label>
                                            <div class="col-lg-10">
                                                <select name="target" id="target" class="form-control">
                                                    <option value="_blank"<?php if($this->registro['target']=="_blank") echo " selected='selected'" ?>>Nova Janela</option>
                                                    <option value="_self"<?php if($this->registro['target']=="_self") echo " selected='selected'" ?>>Mesma Janela</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default toggle">
                                    <!-- Start .panel -->
                                    <div class="panel-heading">
                                        <h4 class="panel-title">Agendamento</h4>
                                    </div>
                                    <div class="panel-body">
                                        <div class="form-group" style="margin-top: 10px;">
                                            <label class="col-lg-2 control-label" for="agendar_entrada_data">Data de entrada:</label>
                                            <div class="col-lg-4">
                                                <input autocomplete="off" class="form-control data" name="agendar_entrada_data" id="agendar_entrada_data" type="text" value="<?php echo $this->registro['agendar_entrada_data']; ?>" />
                                            </div>
                                            <label class="col-lg-2 control-label" for="agendar_entrada_hora">Hora de entrada:</label>
                                            <div class="col-lg-4">
                                                <input autocomplete="off" class="form-control hora" name="agendar_entrada_hora" id="agendar_entrada_hora" type="text" value="<?php echo $this->registro['agendar_entrada_hora']; ?>" />
                                            </div>
                                        </div>

                                        <div class="form-group" style="margin-top: 10px;">
                                            <label class="col-lg-2 control-label" for="agendar_saida_data">Data de saída:</label>
                                            <div class="col-lg-4">
                                                <input autocomplete="off" class="form-control data" name="agendar_saida_data" id="agendar_saida_data" type="text" value="<?php echo $this->registro['agendar_saida_data']; ?>" />
                                            </div>
                                            <label class="col-lg-2 control-label" for="agendar_saida_hora">Hora de saída:</label>
                                            <div class="col-lg-4">
                                                <input autocomplete="off" class="form-control hora" name="agendar_saida_hora" id="agendar_saida_hora" type="text" value="<?php echo $this->registro['agendar_saida_hora']; ?>" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <?php if ($this->id==""): ?>
                                <?php if (!$this->permissions[$this->permissao_ref]['gravar']): ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <span class="label label-warning "><span class="icon24 typ-icon-warning"></span>Você não tem permissão para gravar esta função.</span>
                                        </div>
                                    </div><!-- End .form-group  -->   
                                <?php else: ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <button type="button" class="btn btn-info clickformsubmit">Salvar novo</button>
                                        </div>
                                    </div><!-- End .form-group  -->
                                <?php endif ?>
                            <?php else: ?>
                                <?php if (!$this->permissions[$this->permissao_ref]['editar']): ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <span class="label label-warning"><span class="icon24 icomoon-icon-warning "></span>Você não tem permissão para editar esta função.</span>
                                        </div>
                                    </div><!-- End .form-group  -->   
                                <?php else: ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <button type="button" class="btn btn-info clickformsubmit">Salvar alterações</button>
                                        </div>
                                    </div><!-- End .form-group  -->
                                <?php endif ?>
                            <?php endif ?>
                        </div><!-- End .row -->  
                    </form>
                </div>
            </div>
            <?php   require_once $this->main_layouts . "footer.phtml"; ?>
        </div>
        
        <?php   require_once $this->main_layouts . "plugins.phtml"; ?>
        <script src="<?php echo $this->main_template;?>plugins/forms/autosize/jquery.autosize.js"></script>
        <script src="<?php echo $this->main_template;?>plugins/forms/summernote/summernote.js"></script>
        <script type="text/javascript">
            $(document).ready(function(){
                $('.elastic').autosize();
                summernote();

                $(".data").datepicker({
                    dateFormat: 'dd/mm/yy',
                    dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'],
                    dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
                    dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
                    monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
                    monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
                    nextText: 'Próximo',
                    prevText: 'Anterior'
                });

                $('.hora').mask('00:00');
                $('.data').mask('00/00/0000');

                $("#id_produto").on("change", function(){
                    if(this.value == "NULL")
                        $(".form-group.target_toggle").show()
                    else
                        $(".form-group.target_toggle").hide()
                });
                $("#id_produto").trigger("change");
            });
        </script>
    </body>
</html>
